// Targeted language edits identified by the native-copy audit.
const exact={
 uk:{'Three portions each weigh 175 g. What is the total?':'Кожна з трьох порцій важить 175 г. Яка їхня загальна маса?'},
 el:{'The Case Room':'Ανάλυση περιπτώσεων','THE CASE ROOM':'ΑΝΑΛΥΣΗ ΠΕΡΙΠΤΩΣΕΩΝ'},
 fil:{'Wing roll-control surface (aileron)':'Aileron sa pakpak','Vertical tail control surface (rudder)':'Rudder sa patayong buntot','Red-cell nuclei':'Mga nucleus ng pulang selula ng dugo','Grammar Check-In':'Panimulang Pagsubok sa Gramatika','GRAMMAR CHECK-IN':'PANIMULANG PAGSUBOK SA GRAMATIKA','Logic Under Pressure':'Mas Mahirap na Hamon sa Lohika','LOGIC UNDER PRESSURE':'MAS MAHIRAP NA HAMON SA LOHIKA','code B7Q dash 4M2 dash K9':'code na B7Q, gitling, 4M2, gitling, K9','MATERNAL BLOOD → PLACENTA → CORD → BABY':'DUGO NG INA → INUNAN → KURDON NG PUSOD → SANGGOL','Vows and Formation':'Mga Panata at Paghahanda','VOWS AND FORMATION':'MGA PANATA AT PAGHAHANDA','MAP SCALE::1 cm = 5 m':'ISKALA NG MAPA::1 cm = 5 m'},
 cs:{'The Early Church':'Raná církev','Which number is not the cube of a whole number?':'Které číslo není třetí mocninou celého čísla?','Which term completes the pattern?':'Který člen doplňuje řadu?','Independent repetitions produce similar results':'Nezávislá opakování dávají podobné výsledky','A prediction sounds plausible':'Předpověď zní věrohodně','The researcher expected it':'Výzkumník to očekával','The value is increasing faster':'Hodnota roste rychleji','Explore faith and tradition.\nHow much will you remember?':'Prozkoumejte víru a tradice.\nKolik si toho vybavíte?','Which sacrament is normally the entry into Christian life?':'Která svátost obvykle představuje vstup do křesťanského života?','Which sacrament concerns reconciliation after sin?':'Která svátost přináší smíření po hříchu?','What does Christmas celebrate in Christian belief?':'Co podle křesťanské víry slavíme o Vánocích?'},
 da:{'After every appeal':'Efter hver appel','Ignore the exception':'Ignorer undtagelsen','EVIDENCE IN FOCUS':'BEVISER I FOKUS','An automatic acquittal':'En automatisk frifindelse','To prevent lawful review':'For at forhindre en lovlig prøvelse','Invent the missing words':'Find på de manglende ord','A difficult timetable':'En vanskelig tidsplan','Legal terms never vary':'Juridiske begreber varierer aldrig','MAP SCALE::1 cm = 5 m':'KORTMÅLESTOK::1 cm = 5 m'},
 de:{'Deine beste Runde':'Ihre beste Runde','Du hast ihn gehen sehen, nicht wahr?':'Sie haben ihn gehen sehen, nicht wahr?','Du blickst nach Norden und drehst dich zweimal nach rechts. In welche Richtung blickst du nun?':'Sie blicken nach Norden und drehen sich zweimal nach rechts. In welche Richtung blicken Sie nun?','Starte in der Mitte. Gehe zweimal nach oben, einmal nach rechts, einmal nach unten und zweimal nach links. Wo landest du?':'Starten Sie in der Mitte. Gehen Sie zweimal nach oben, einmal nach rechts, einmal nach unten und zweimal nach links. Wo befinden Sie sich am Ende?','Warum kommst du nie zurecht?':'Warum kommen Sie nie zurecht?'},
 es:{'Es posible que una tarea no muestre la imagen completa':'Una sola tarea puede no reflejar todo lo que sabe el estudiante'},
 ms:{'STRUCTURES AND SIGNALS':'STRUKTUR DAN ISYARAT','Only the aorta':'Hanya aorta','Only large veins':'Hanya vena besar','Form a blood clot':'Membentuk bekuan darah','SCIENCE IN PRACTICE':'SAINS DALAM AMALAN','Final Birth Centre':'Cabaran Akhir di Pusat Bersalin'},
 nb:{'Logic at the Board':'Logikk ved tavlen','LOGIC AT THE BOARD':'LOGIKK VED TAVLEN','The Final Tutorial':'Den siste veiledningstimen','Which number comes next?':'Hvilket tall kommer etterpå?','Nia attends tutorials':'Nia deltar i veiledningstimer','Nia leads tutorials':'Nia leder veiledningstimer','Omar was invited':'Omar ble invitert','All reviewers are poets':'Alle anmelderne er poeter'},
};

function portuguese(s){
 s=s.replace('Siga o que parece ser você.\nDescubra o seu par inspirado no país.','Siga as suas preferências.\nDescubra o país que combina consigo.')
  .replace('Qual primeira impressão atrai você?','Que primeira impressão mais lhe agrada?')
  .replace('O que faria uma viagem parecer mais com você?','O que tornaria uma viagem mais ao seu estilo?');
 s=s.replace(/\b[Pp]ara você\b/gu,'para si').replace(/\b[Ss]obre você\b/gu,'sobre si').replace(/\b[Cc]om você\b/gu,'consigo').replace(/\b[Vv]ocê\s+/gu,'');
 const words={câmara:'cavidade',oxigênio:'O₂',Oxigênio:'O₂',fato:'dado',factos:'dados',fatos:'dados',Fatos:'Dados',registros:'documentos',Registros:'Documentos',REGISTROS:'DOCUMENTOS',registro:'documento',planejado:'agendado',úmidos:'molhados',automóvel:'carro',planejamento:'preparação',Ímã:'Objeto magnético'};
 s=s.replace(/(?<!\p{L})(?:câmara|[Oo]xigênio|fato|factos|fatos|Fatos|registros|Registros|REGISTROS|registro|planejado|úmidos|automóvel|planejamento|Ímã)(?!\p{L})/gu,w=>words[w]);
 s=s.replace(/Primeiro contato/g,'Primeira interação').replace(/PRIMEIRO CONTATO/g,'PRIMEIRA INTERAÇÃO').replace(/início do contato/g,'início da interação');
 s=s.replace(/Incisivos do bebê/g,'Incisivos de uma criança pequena').replace(/Um tipo de câmera cirúrgica/g,'Um dispositivo para obter imagens durante a cirurgia');
 s=s.replace(/distância de frenagem/g,'distância necessária para parar').replace(/a frenagem/g,'a redução de velocidade').replace(/durante a frenagem/g,'durante a redução de velocidade').replace(/A travagem brusca/g,'A desaceleração brusca');
 s=s.replace(/sempre confiável/g,'sempre digno de confiança');
 s=s.replace(/Compreensão compartilhada/g,'Compreensão comum').replace(/Responsabilidades compartilhadas/g,'Responsabilidades assumidas em conjunto')
  .replace(/um café da manhã compartilhado/g,'uma refeição matinal em conjunto').replace(/no tempo compartilhado/g,'no tempo passado em conjunto').replace(/momentos partilhados/g,'momentos vividos em conjunto')
  .replace(/usadas e compartilhadas/g,'usadas e transmitidas').replace(/poderá ser compartilhado/g,'poderá ser transmitido')
  .replace(/Decisões Compartilhadas/g,'Decisões em Conjunto').replace(/DECISÕES COMPARTILHADAS/g,'DECISÕES EM CONJUNTO');
 return s.replace(/(^|\n)(\p{Ll})/gu,(_,a,b)=>a+b.toUpperCase());
}
export function polishText(locale,value){let s=exact[locale]?.[value]??value;if(locale==='pt')s=portuguese(s);return s;}
