export const originalTitles={
  "airforce": "Only 6% Of Adults Can Pass This Air Force Entrance Exam",
  "anatomy": "Only 8% Pass This Human Anatomy Quiz",
  "barrister": "Only 6% Of Adults Can Pass This Barrister Entrance Exam",
  "bible": "Only 11% Of Adults Pass This Bible Quiz",
  "cambridge": "Only 7% Pass This Cambridge Entrance Exam",
  "catholic": "Only 1/10 Can Pass This Catholic Trivia Quiz",
  "chef": "Only 12% Pass This Chef's Entrance Exam",
  "dentist": "Only 15% Of Adults Can Pass This Dentist Entrance Exam",
  "flightattendant": "Only 12% Of Adults Can Pass This Flight Attendant Entrance Exam",
  "doctor": "Most Adults Cannot Pass This Doctor's Entrance Exam",
  "firefighter": "Only 11% Can Pass This Firefighter Entrance Exam",
  "grammar": "Only 10% Can Pass This Grammar Quiz",
  "harvard": "Only 7% Pass This Harvard Entrance Exam",
  "iq": "Only 7% Pass This Intelligence Test",
  "italian": "Only 3% Can Pass This Italian Cuisine Quiz",
  "medical": "Most Adults Cannot Pass This Medical Entrance Exam",
  "midwifery": "Only 7% Pass This Midwifery Entrance Exam",
  "nursing": "Only 7% Pass This Nursing Entrance Exam",
  "motorbike": "Most Drivers Cannot Pass This Motorcycle Driving Test",
  "nun": "Only 12% Of Adults Can Pass This Nun Entrance Exam",
  "paramedic": "Only 8% Pass This Paramedic Entrance Exam",
  "oxford": "Only 7% Pass This Oxford Entrance Exam",
  "personality": "Which Country Matches Your Personality?",
  "pilot": "Only 3% Of Adults Can Pass This Pilot Entrance Exam",
  "police": "Only 6% Of Adults Can Pass This Police Officer Entrance Exam",
  "raf": "Only 15% Of Adults Can Pass This RAF Entrance Exam",
  "socialworker": "Most Adults Cannot Pass This Social Worker Entrance Exam",
  "teacher": "Most Adults Cannot Pass This Teacher's Entrance Exam",
  "surgeon": "Most Adults Cannot Pass This Surgeon's Entrance Exam",
  "word": "Only 7% Pass This Word Association Test"
};
