// A trial programme, never an aircraft pilot. Same percentages and answer positions.
export const trialCopy={
 ar:['يُقال إن برنامجًا تجريبيًا تسبب في زيادة بنسبة 10%، لكن مجموعة المقارنة سجلت زيادة بنسبة 9%. ما الاستنتاج الحذر؟','البرنامج تسبب في الزيادة الكاملة البالغة 10%','من المستحيل أن يكون للبرنامج أي تأثير'],
 bg:['Твърди се, че пробна програма е причинила увеличение от 10%, но сравнителната група отчита увеличение от 9%. Какъв е предпазливият извод?','Програмата е причинила цялото увеличение от 10%','Невъзможно е програмата да е имала ефект'],
 cs:['Tvrdí se, že zkušební program způsobil nárůst o 10 %, ale srovnávací skupina zaznamenala nárůst o 9 %. Jaký závěr je opatrný?','Program způsobil celý nárůst o 10 %','Program nemohl mít žádný účinek'],
 da:['Det hævdes, at et forsøgsprogram skabte en stigning på 10 %, men sammenligningsgruppen havde en stigning på 9 %. Hvad er den forsigtige konklusion?','Programmet skabte hele stigningen på 10 %','Programmet kan ikke have haft nogen effekt'],
 de:['Einem Versuchsprogramm wird ein Anstieg von 10 % zugeschrieben, doch die Vergleichsgruppe verzeichnete 9 %. Was ist die vorsichtige Schlussfolgerung?','Das Programm verursachte den gesamten Anstieg von 10 %','Das Programm kann keinerlei Wirkung gehabt haben'],
 el:['Υποστηρίζεται ότι ένα δοκιμαστικό πρόγραμμα προκάλεσε αύξηση 10%, αλλά η ομάδα σύγκρισης κατέγραψε αύξηση 9%. Ποιο είναι το προσεκτικό συμπέρασμα;','Το πρόγραμμα προκάλεσε ολόκληρη την αύξηση 10%','Αποκλείεται το πρόγραμμα να είχε οποιαδήποτε επίδραση'],
 es:['Se afirma que un programa de prueba causó un aumento del 10 %, pero el grupo de comparación registró un 9 %. ¿Cuál es la conclusión prudente?','El programa causó todo el aumento del 10 %','El programa no pudo tener ningún efecto'],
 fi:['Kokeiluohjelman väitetään aiheuttaneen 10 %:n nousun, mutta vertailuryhmässä nousu oli 9 %. Mikä on varovainen johtopäätös?','Ohjelma aiheutti koko 10 %:n nousun','Ohjelmalla ei mitenkään voinut olla vaikutusta'],
 fil:['Sinasabing nagdulot ng 10% na pagtaas ang isang programang sinusubukan, ngunit tumaas din ng 9% ang pangkat na pinaghahambingan. Ano ang maingat na konklusyon?','Ang programa ang nagdulot ng buong 10% na pagtaas','Imposibleng nagkaroon ng anumang epekto ang programa'],
 fr:['On affirme qu’un programme expérimental a causé une hausse de 10 %, mais le groupe de comparaison a enregistré une hausse de 9 %. Quelle conclusion prudente faut-il tirer ?','Le programme a causé toute la hausse de 10 %','Le programme ne peut avoir eu aucun effet'],
 he:['נטען שתוכנית ניסיונית גרמה לעלייה של 10%, אך בקבוצת ההשוואה נרשמה עלייה של 9%. מהי המסקנה הזהירה?','התוכנית גרמה לכל העלייה של 10%','לא ייתכן שהייתה לתוכנית השפעה כלשהי'],
 hr:['Tvrdi se da je probni program uzrokovao porast od 10%, ali usporedna skupina bilježi porast od 9%. Koji je oprezan zaključak?','Program je uzrokovao cijeli porast od 10%','Program nikako nije mogao imati učinak'],
 hu:['Egy állítás szerint egy kísérleti program 10%-os növekedést okozott, de az összehasonlító csoportban is 9%-os növekedés volt. Mi az óvatos következtetés?','A program okozta a teljes 10%-os növekedést','A programnak semmilyen hatása nem lehetett'],
 id:['Diklaim bahwa program uji coba menyebabkan kenaikan 10%, tetapi kelompok pembanding juga mencatat kenaikan 9%. Apa kesimpulan yang hati-hati?','Program menyebabkan seluruh kenaikan 10%','Program tidak mungkin memiliki pengaruh apa pun'],
 it:['Si sostiene che un programma sperimentale abbia causato un aumento del 10%, ma il gruppo di confronto ha registrato un aumento del 9%. Qual è la conclusione prudente?','Il programma ha causato l’intero aumento del 10%','Il programma non può aver avuto alcun effetto'],
 ja:['試験的なプログラムが10%の上昇をもたらしたと主張されていますが、比較対象のグループでも9%上昇しました。慎重な結論はどれ？','10%の上昇はすべてプログラムによるものだ','プログラムに効果があった可能性はまったくない'],
 ms:['Didakwa bahawa program percubaan menyebabkan peningkatan 10%, tetapi kumpulan perbandingan juga mencatatkan peningkatan 9%. Apakah kesimpulan yang berhati-hati?','Program menyebabkan keseluruhan peningkatan 10%','Program mustahil memberikan sebarang kesan'],
 nb:['Det hevdes at et forsøksprogram ga en økning på 10 %, men sammenligningsgruppen hadde en økning på 9 %. Hva er den forsiktige konklusjonen?','Programmet ga hele økningen på 10 %','Programmet kan ikke ha hatt noen effekt'],
 nl:['Er wordt beweerd dat een proefprogramma een stijging van 10% veroorzaakte, maar de vergelijkingsgroep steeg met 9%. Wat is de voorzichtige conclusie?','Het programma veroorzaakte de volledige stijging van 10%','Het programma kan geen enkel effect hebben gehad'],
 pl:['Twierdzi się, że program próbny spowodował wzrost o 10%, ale w grupie porównawczej odnotowano wzrost o 9%. Jaki jest ostrożny wniosek?','Program spowodował cały wzrost o 10%','Program nie mógł mieć żadnego wpływu'],
 pt:['Afirma-se que um programa experimental causou uma subida de 10%, mas o grupo de comparação registou uma subida de 9%. Qual é a conclusão prudente?','O programa causou toda a subida de 10%','O programa não pode ter tido qualquer efeito'],
 ro:['Se afirmă că un program experimental a provocat o creștere de 10%, dar grupul de comparație a înregistrat o creștere de 9%. Care este concluzia prudentă?','Programul a provocat întreaga creștere de 10%','Programul nu ar fi putut avea niciun efect'],
 sk:['Tvrdí sa, že skúšobný program spôsobil nárast o 10 %, ale porovnávacia skupina zaznamenala nárast o 9 %. Aký záver je opatrný?','Program spôsobil celý nárast o 10 %','Program nemohol mať žiadny účinok'],
 sr:['Тврди се да је пробни програм изазвао пораст од 10%, али упоредна група бележи пораст од 9%. Који је опрезан закључак?','Програм је изазвао цео пораст од 10%','Програм никако није могао да има утицај'],
 sv:['Det hävdas att ett försöksprogram gav en ökning på 10 %, men jämförelsegruppen hade en ökning på 9 %. Vad är den försiktiga slutsatsen?','Programmet orsakade hela ökningen på 10 %','Programmet kan inte ha haft någon effekt'],
 th:['มีการอ้างว่าโครงการทดลองทำให้เพิ่มขึ้น 10% แต่กลุ่มเปรียบเทียบก็เพิ่มขึ้น 9% ข้อสรุปใดรอบคอบที่สุด?','โครงการทำให้เกิดการเพิ่มขึ้นทั้งหมด 10%','เป็นไปไม่ได้ที่โครงการจะมีผลใด ๆ'],
 tr:['Bir deneme programının %10 artış sağladığı iddia ediliyor, ancak karşılaştırma grubunda da %9 artış var. Temkinli çıkarım hangisidir?','%10 artışın tamamını program sağladı','Programın herhangi bir etkisi olması imkânsızdır'],
 uk:['Стверджують, що експериментальна програма спричинила зростання на 10%, але в групі порівняння зафіксовано зростання на 9%. Який висновок є обережним?','Програма спричинила все зростання на 10%','Програма не могла мати жодного впливу'],
 vi:['Có ý kiến cho rằng một chương trình thử nghiệm tạo ra mức tăng 10%, nhưng nhóm so sánh cũng tăng 9%. Kết luận thận trọng là gì?','Chương trình tạo ra toàn bộ mức tăng 10%','Chương trình không thể có bất kỳ tác động nào'],
};

// Official RAF rank labels remain English, avoiding false equivalence with local ranks.
// Columns: above Flight Lieutenant; higher rank; identical ranks; neither is an RAF rank.
export const rafContext={
 ar:['أي رتبة في سلاح الجو الملكي البريطاني تأتي مباشرةً فوق Flight Lieutenant؟','أيهما أعلى رتبة في سلاح الجو الملكي البريطاني: Squadron Leader أم Wing Commander؟','هما الرتبة نفسها','لا تنتمي أي منهما إلى رتب سلاح الجو الملكي البريطاني'],
 bg:['Кое звание в RAF е непосредствено над Flight Lieutenant?','Кое звание в RAF е по-високо: Squadron Leader или Wing Commander?','Това са еднакви звания','Нито едно от двете не е звание в RAF'],
 cs:['Která hodnost RAF je bezprostředně nad Flight Lieutenant?','Která hodnost RAF je vyšší: Squadron Leader, nebo Wing Commander?','Jde o stejné hodnosti','Ani jedna není hodností RAF'],
 da:['Hvilken RAF-grad ligger umiddelbart over Flight Lieutenant?','Hvilken RAF-grad er højest: Squadron Leader eller Wing Commander?','Det er den samme grad','Ingen af dem er en RAF-grad'],
 de:['Welcher RAF-Dienstgrad steht unmittelbar über Flight Lieutenant?','Welcher RAF-Dienstgrad ist höher: Squadron Leader oder Wing Commander?','Es handelt sich um denselben Dienstgrad','Keiner von beiden ist ein RAF-Dienstgrad'],
 el:['Ποιος βαθμός της RAF βρίσκεται αμέσως πάνω από τον Flight Lieutenant;','Ποιος βαθμός της RAF είναι ανώτερος: Squadron Leader ή Wing Commander;','Είναι ο ίδιος βαθμός','Κανένας από τους δύο δεν είναι βαθμός της RAF'],
 es:['¿Qué rango de la RAF está inmediatamente por encima de Flight Lieutenant?','¿Qué rango de la RAF es superior: Squadron Leader o Wing Commander?','Son el mismo rango','Ninguno de los dos es un rango de la RAF'],
 fi:['Mikä RAF:n sotilasarvo on heti Flight Lieutenant -arvon yläpuolella?','Kumpi RAF:n sotilasarvo on korkeampi: Squadron Leader vai Wing Commander?','Ne ovat sama sotilasarvo','Kumpikaan ei ole RAF:n sotilasarvo'],
 fil:['Aling ranggo sa RAF ang kaagad na mas mataas sa Flight Lieutenant?','Aling ranggo sa RAF ang mas mataas: Squadron Leader o Wing Commander?','Magkapareho ang dalawang ranggo','Wala sa dalawa ang ranggo sa RAF'],
 fr:['Quel grade de la RAF se situe juste au-dessus de Flight Lieutenant ?','Quel grade de la RAF est le plus élevé : Squadron Leader ou Wing Commander ?','Il s’agit du même grade','Aucun des deux n’est un grade de la RAF'],
 he:['איזו דרגה ב־RAF נמצאת מיד מעל Flight Lieutenant?','איזו דרגה ב־RAF גבוהה יותר: Squadron Leader או Wing Commander?','אלה דרגות זהות','אף אחת מהן אינה דרגה ב־RAF'],
 hr:['Koji je čin u RAF-u neposredno iznad čina Flight Lieutenant?','Koji je čin u RAF-u viši: Squadron Leader ili Wing Commander?','To su isti činovi','Nijedan od njih nije čin u RAF-u'],
 hu:['Melyik RAF-rendfokozat áll közvetlenül a Flight Lieutenant felett?','Melyik RAF-rendfokozat magasabb: a Squadron Leader vagy a Wing Commander?','Azonos rendfokozatok','Egyik sem RAF-rendfokozat'],
 id:['Pangkat RAF mana yang tepat satu tingkat di atas Flight Lieutenant?','Pangkat RAF mana yang lebih tinggi: Squadron Leader atau Wing Commander?','Keduanya adalah pangkat yang sama','Keduanya bukan pangkat RAF'],
 it:['Quale grado della RAF si trova immediatamente sopra Flight Lieutenant?','Quale grado della RAF è più alto: Squadron Leader o Wing Commander?','Sono lo stesso grado','Nessuno dei due è un grado della RAF'],
 ja:['イギリス空軍でFlight Lieutenantのすぐ上にあたる階級はどれ？','イギリス空軍でSquadron LeaderとWing Commanderのどちらが上の階級？','どちらも同じ階級','どちらもイギリス空軍の階級ではない'],
 ms:['Pangkat RAF yang manakah berada satu tingkat di atas Flight Lieutenant?','Pangkat RAF yang manakah lebih tinggi: Squadron Leader atau Wing Commander?','Kedua-duanya pangkat yang sama','Kedua-duanya bukan pangkat RAF'],
 nb:['Hvilken grad i RAF er rett over Flight Lieutenant?','Hvilken grad i RAF er høyest: Squadron Leader eller Wing Commander?','Det er samme grad','Ingen av dem er en grad i RAF'],
 nl:['Welke RAF-rang staat direct boven Flight Lieutenant?','Welke RAF-rang is hoger: Squadron Leader of Wing Commander?','Het zijn dezelfde rangen','Geen van beide is een RAF-rang'],
 pl:['Który stopień RAF znajduje się bezpośrednio powyżej Flight Lieutenant?','Który stopień RAF jest wyższy: Squadron Leader czy Wing Commander?','To ten sam stopień','Żaden z nich nie jest stopniem RAF'],
 pt:['Que patente da RAF fica imediatamente acima de Flight Lieutenant?','Que patente da RAF é superior: Squadron Leader ou Wing Commander?','São a mesma patente','Nenhuma das duas é uma patente da RAF'],
 ro:['Ce grad din RAF se află imediat deasupra gradului Flight Lieutenant?','Ce grad din RAF este mai înalt: Squadron Leader sau Wing Commander?','Sunt grade identice','Niciunul nu este un grad din RAF'],
 sk:['Ktorá hodnosť RAF je bezprostredne nad hodnosťou Flight Lieutenant?','Ktorá hodnosť RAF je vyššia: Squadron Leader alebo Wing Commander?','Ide o rovnaké hodnosti','Ani jedna nie je hodnosťou RAF'],
 sr:['Који чин у RAF-у је непосредно изнад чина Flight Lieutenant?','Који чин у RAF-у је виши: Squadron Leader или Wing Commander?','То су исти чинови','Ниједан од њих није чин у RAF-у'],
 sv:['Vilken grad i RAF ligger direkt över Flight Lieutenant?','Vilken grad i RAF är högst: Squadron Leader eller Wing Commander?','Det är samma grad','Ingen av dem är en grad i RAF'],
 th:['ยศใดของกองทัพอากาศอังกฤษอยู่สูงกว่า Flight Lieutenant หนึ่งขั้น?','ยศใดของกองทัพอากาศอังกฤษสูงกว่า: Squadron Leader หรือ Wing Commander?','ทั้งสองเป็นยศเดียวกัน','ทั้งสองไม่ใช่ยศของกองทัพอากาศอังกฤษ'],
 tr:['RAF’ta Flight Lieutenant rütbesinin hemen üstündeki rütbe hangisidir?','RAF’ta hangi rütbe daha yüksektir: Squadron Leader mı, Wing Commander mı?','İkisi de aynı rütbedir','İkisi de RAF rütbesi değildir'],
 uk:['Яке звання в RAF стоїть безпосередньо вище за Flight Lieutenant?','Яке звання в RAF вище: Squadron Leader чи Wing Commander?','Це однакові звання','Жодне з них не є званням RAF'],
 vi:['Trong Không quân Hoàng gia Anh, cấp bậc nào nằm ngay trên Flight Lieutenant?','Trong Không quân Hoàng gia Anh, cấp bậc nào cao hơn: Squadron Leader hay Wing Commander?','Hai cấp bậc này giống nhau','Cả hai đều không phải cấp bậc của Không quân Hoàng gia Anh'],
};
