import {trialCopy,rafContext} from './proofreading-context.mjs';
import {proofreadPuzzles} from './proofreading-puzzles.mjs';
import {proofreadClinical} from './proofreading-clinical.mjs';
import {proofreadHeadings} from './proofreading-headings.mjs';
import {proofreadTerms} from './proofreading-terms.mjs';
import {proofreadVisualLabels,proofreadClearRoutes} from './proofreading-visual-labels.mjs';
import {proofreadSubtitle} from './proofreading-subtitles.mjs';
// Contextual copy corrections: preserve question IDs, answer positions and scoring.
// Columns: funded-project premise; impartial prompt; four choices; anthology prompt;
// concise prompt; four choices; argument/calculation analogy.
export const universityCopy = {
 ar: ['تمت مراجعة جميع المشاريع المموّلة، ومشروع K حصل على تمويل. أي استنتاج يلزم عن ذلك؟','حَكَم لا يفضّل أيًّا من الطرفين. ما الصفة التي تصفه؟',['غير منحاز','غير متأكد','غير مستعد','غير مألوف'],'يضم الأرشيف سجلات. ماذا تضمّ مجموعة مختارات أدبية؟','أي وصف يناسب نصًّا يعبّر عن فكرته بكلمات قليلة؟',['غير مؤكد','مزخرف','موجز','متكرر'],'تقود الحجة إلى استنتاج. وإلى ماذا تقود العملية الحسابية؟'],
 bg: ['Всички финансирани проекти са проверени. Проект K е финансиран. Какъв извод следва?','Съдия не дава предимство на нито една от страните. Какъв е той?',['Безпристрастен','Несигурен','Неподготвен','Необичаен'],'Архивът съдържа документи. Какво съдържа една антология?','Коя дума описва текст, който изразява мисълта с малко думи?',['Несигурен','Декоративен','Кратък','Повтарящ се'],'Аргументацията води до заключение. До какво води изчислението?'],
 cs: ['Všechny financované projekty byly přezkoumány. Projekt K byl financován. Který závěr z toho vyplývá?','Rozhodčí nezvýhodňuje ani jednu stranu. Jaký je?',['Nezaujatý','Nejistý','Nepřipravený','Neobvyklý'],'Archiv obsahuje záznamy. Co obsahuje antologie?','Které slovo popisuje text, který vyjadřuje myšlenku několika málo slovy?',['Nejistý','Ozdobný','Stručný','Opakující se'],'Argumentace vede k závěru. K čemu vede výpočet?'],
 da: ['Alle finansierede projekter blev gennemgået. Projekt K blev finansieret. Hvilken konklusion følger?','En dommer favoriserer ingen af parterne. Hvilket ord beskriver dommeren?',['Upartisk','Usikker','Uforberedt','Usædvanlig'],'Et arkiv indeholder dokumenter. Hvad indeholder en antologi?','Hvilket ord beskriver en tekst, der udtrykker sin pointe med få ord?',['Usikker','Dekorativ','Kortfattet','Gentagende'],'En argumentation fører til en konklusion. Hvad fører en beregning til?'],
 de: ['Alle finanzierten Projekte wurden geprüft. Projekt K wurde finanziert. Welche Schlussfolgerung ergibt sich daraus?','Eine Person urteilt, ohne eine Seite zu bevorzugen. Welches Wort beschreibt sie?',['Unvoreingenommen','Unsicher','Unvorbereitet','Ungewöhnlich'],'Ein Archiv enthält Aufzeichnungen. Was enthält eine Anthologie?','Welches Wort beschreibt einen Text, der seinen Gedanken mit wenigen Worten ausdrückt?',['Unsicher','Dekorativ','Kurz gefasst','Wiederholend'],'Eine Argumentation führt zu einer Schlussfolgerung. Wozu führt eine Berechnung?'],
 el: ['Όλα τα χρηματοδοτούμενα έργα ελέγχθηκαν. Το έργο K χρηματοδοτήθηκε. Ποιο συμπέρασμα προκύπτει;','Ένας κριτής δεν ευνοεί καμία από τις δύο πλευρές. Ποια λέξη τον περιγράφει;',['Αμερόληπτος','Αβέβαιος','Απροετοίμαστος','Ασυνήθιστος'],'Ένα αρχείο περιέχει έγγραφα. Τι περιέχει μια ανθολογία;','Ποια λέξη περιγράφει ένα κείμενο που εκφράζει το νόημά του με λίγες λέξεις;',['Αβέβαιο','Διακοσμητικό','Σύντομο','Επαναλαμβανόμενο'],'Η επιχειρηματολογία οδηγεί σε συμπέρασμα. Σε τι οδηγεί ένας υπολογισμός;'],
 es: ['Todos los proyectos financiados fueron revisados. El proyecto K fue financiado. ¿Qué conclusión se deduce?','Un juez no favorece a ninguna de las partes. ¿Qué palabra lo describe?',['Imparcial','Inseguro','Desprevenido','Inusual'],'Un archivo contiene documentos. ¿Qué contiene una antología?','¿Qué palabra describe un texto que expresa su idea con pocas palabras?',['Incierto','Decorativo','Breve','Repetitivo'],'Una argumentación lleva a una conclusión. ¿A qué lleva un cálculo?'],
 fi: ['Kaikki rahoitetut hankkeet tarkistettiin. Hanke K sai rahoitusta. Mikä johtopäätös tästä seuraa?','Tuomari ei suosi kumpaakaan osapuolta. Mikä sana kuvaa häntä?',['Puolueeton','Epävarma','Valmistautumaton','Epätavallinen'],'Arkisto sisältää asiakirjoja. Mitä antologia sisältää?','Mikä sana kuvaa tekstiä, joka ilmaisee ajatuksensa vähin sanoin?',['Epävarma','Koristeellinen','Lyhytsanainen','Toisteinen'],'Perustelu johtaa johtopäätökseen. Mihin laskutoimitus johtaa?'],
 fil: ['Sinuri ang lahat ng proyektong pinondohan. Pinondohan ang Proyekto K. Anong konklusyon ang tiyak na sumusunod?','Hindi pinapaboran ng isang hukom ang alinmang panig. Alin ang naglalarawan sa kanya?',['Walang kinikilingan','Hindi sigurado','Hindi handa','Hindi karaniwan'],'Naglalaman ng mga dokumento ang isang arkibo. Ano naman ang laman ng isang antolohiya?','Alin ang naglalarawan sa tekstong nagpapahayag ng ideya sa iilang salita?',['Hindi tiyak','Pandekorasyon','Maikli','Paulit-ulit'],'Humahantong sa konklusyon ang pangangatwiran. Saan naman humahantong ang pagkalkula?'],
 fr: ['Tous les projets financés ont été examinés. Le projet K a été financé. Quelle conclusion en découle ?','Un juge ne favorise aucune des parties. Quel mot le décrit ?',['Impartial','Incertain','Non préparé','Inhabituel'],'Des archives contiennent des documents. Que contient une anthologie ?','Quel mot décrit un texte qui exprime son idée en peu de mots ?',['Incertain','Décoratif','Bref','Répétitif'],'Une argumentation mène à une conclusion. À quoi mène un calcul ?'],
 he: ['כל הפרויקטים שקיבלו מימון נבדקו. פרויקט K קיבל מימון. איזו מסקנה נובעת מכך?','שופט אינו מעדיף אף אחד מהצדדים. איזו תכונה מתארת אותו?',['חסר פניות','לא בטוח','לא מוכן','יוצא דופן'],'ארכיון מכיל מסמכים. מה מכילה אנתולוגיה?','איזו מילה מתארת טקסט שמביע את הרעיון במעט מילים?',['לא ודאי','קישוטי','תמציתי','חזרתי'],'טיעון מוביל למסקנה. למה מוביל חישוב?'],
 hr: ['Svi financirani projekti su pregledani. Projekt K je financiran. Koji zaključak slijedi?','Sudac ne daje prednost nijednoj strani. Koja ga riječ opisuje?',['Nepristran','Nesiguran','Nespreman','Neobičan'],'Arhiv sadrži dokumente. Što sadrži antologija?','Koja riječ opisuje tekst koji izražava misao s malo riječi?',['Nesiguran','Ukrasan','Sažet','Ponavljajući'],'Argumentacija vodi do zaključka. Do čega vodi izračun?'],
 hu: ['Minden finanszírozott projektet felülvizsgáltak. A K projektet finanszírozták. Melyik következtetés adódik ebből?','Egy bíró egyik felet sem részesíti előnyben. Melyik szó jellemzi?',['Elfogulatlan','Bizonytalan','Felkészületlen','Szokatlan'],'A levéltár iratokat tartalmaz. Mit tartalmaz egy antológia?','Melyik szó jellemzi azt a szöveget, amely kevés szóval fejezi ki a gondolatot?',['Bizonytalan','Díszítő','Tömör','Ismétlődő'],'Az érvelés következtetéshez vezet. Mihez vezet a számítás?'],
 id: ['Semua proyek yang didanai telah ditinjau. Proyek K didanai. Kesimpulan apa yang pasti benar?','Seorang hakim tidak mengutamakan pihak mana pun. Sifat apa yang menggambarkannya?',['Tidak memihak','Tidak yakin','Tidak siap','Tidak biasa'],'Arsip berisi dokumen. Apa yang terdapat dalam sebuah antologi?','Kata mana yang menggambarkan teks yang menyampaikan gagasan dengan sedikit kata?',['Tidak pasti','Dekoratif','Singkat','Berulang-ulang'],'Penalaran menghasilkan kesimpulan. Perhitungan menghasilkan apa?'],
 it: ['Tutti i progetti finanziati sono stati esaminati. Il progetto K è stato finanziato. Quale conclusione ne consegue?','Un giudice non favorisce nessuna delle parti. Quale parola lo descrive?',['Imparziale','Incerto','Impreparato','Insolito'],'Un archivio contiene documenti. Che cosa contiene un’antologia?','Quale parola descrive un testo che esprime un’idea con poche parole?',['Incerto','Decorativo','Breve','Ripetitivo'],'Un ragionamento porta a una conclusione. A che cosa porta un calcolo?'],
 ja: ['資金提供を受けたプロジェクトはすべて審査済みです。プロジェクトKは資金提供を受けました。必ず成り立つ結論はどれ？','どちらの側にも肩入れせずに判断する人を表す言葉はどれ？',['公平な','自信のない','準備不足の','風変わりな'],'記録保管庫が記録を収めるように、文学作品の選集には何が収められていますか？','少ない言葉で要点を伝える文章を表す言葉はどれ？',['不確かな','装飾的な','簡潔な','繰り返しの多い'],'論証からは結論が導かれます。では、計算から導かれるものは？'],
 ms: ['Semua projek yang dibiayai telah disemak. Projek K telah dibiayai. Apakah kesimpulan yang pasti benar?','Seorang hakim tidak memihak kepada mana-mana pihak. Sifat manakah yang menggambarkannya?',['Tidak berat sebelah','Tidak pasti','Tidak bersedia','Luar biasa'],'Arkib mengandungi dokumen. Apakah kandungan sebuah antologi?','Perkataan manakah yang menggambarkan teks yang menyampaikan idea dengan sedikit perkataan?',['Tidak pasti','Berhias','Ringkas','Berulang-ulang'],'Penghujahan membawa kepada kesimpulan. Pengiraan pula membawa kepada apa?'],
 nb: ['Alle finansierte prosjekter ble gjennomgått. Prosjekt K ble finansiert. Hvilken konklusjon følger?','En dommer favoriserer ingen av partene. Hvilket ord beskriver dommeren?',['Upartisk','Usikker','Uforberedt','Uvanlig'],'Et arkiv inneholder dokumenter. Hva inneholder en antologi?','Hvilket ord beskriver en tekst som uttrykker poenget med få ord?',['Usikker','Dekorativ','Kortfattet','Gjentakende'],'En argumentasjon fører til en konklusjon. Hva fører en beregning til?'],
 nl: ['Alle gefinancierde projecten zijn beoordeeld. Project K is gefinancierd. Welke conclusie volgt daaruit?','Een rechter bevoordeelt geen van beide partijen. Welk woord beschrijft die rechter?',['Onpartijdig','Onzeker','Onvoorbereid','Ongebruikelijk'],'Een archief bevat documenten. Wat bevat een bloemlezing?','Welk woord beschrijft een tekst die zijn gedachte in weinig woorden uitdrukt?',['Onzeker','Decoratief','Beknopt','Herhalend'],'Een redenering leidt tot een conclusie. Waartoe leidt een berekening?'],
 pl: ['Wszystkie finansowane projekty zostały sprawdzone. Projekt K otrzymał finansowanie. Jaki wniosek z tego wynika?','Sędzia nie faworyzuje żadnej ze stron. Jakie słowo go opisuje?',['Bezstronny','Niepewny','Nieprzygotowany','Nietypowy'],'Archiwum zawiera dokumenty. Co zawiera antologia?','Jakie słowo opisuje tekst, który wyraża myśl w niewielu słowach?',['Niepewny','Ozdobny','Zwięzły','Powtarzalny'],'Argumentacja prowadzi do wniosku. Do czego prowadzi obliczenie?'],
 pt: ['Todos os projetos financiados foram analisados. O projeto K foi financiado. Que conclusão se segue?','Um juiz não favorece nenhuma das partes. Que palavra o descreve?',['Imparcial','Incerto','Despreparado','Incomum'],'Um arquivo contém documentos. O que contém uma antologia?','Que palavra descreve um texto que expressa uma ideia com poucas palavras?',['Incerto','Decorativo','Breve','Repetitivo'],'Uma argumentação leva a uma conclusão. A que leva um cálculo?'],
 ro: ['Toate proiectele finanțate au fost verificate. Proiectul K a fost finanțat. Ce concluzie rezultă?','Un judecător nu favorizează niciuna dintre părți. Ce cuvânt îl descrie?',['Imparțial','Nesigur','Nepregătit','Neobișnuit'],'O arhivă conține documente. Ce conține o antologie?','Ce cuvânt descrie un text care exprimă ideea în puține cuvinte?',['Nesigur','Decorativ','Concis','Repetitiv'],'O argumentare conduce la o concluzie. La ce conduce un calcul?'],
 sk: ['Všetky financované projekty boli preskúmané. Projekt K bol financovaný. Ktorý záver z toho vyplýva?','Rozhodca neuprednostňuje ani jednu stranu. Aký je?',['Nestranný','Neistý','Nepripravený','Nezvyčajný'],'Archív obsahuje záznamy. Čo obsahuje antológia?','Ktoré slovo opisuje text, ktorý vyjadruje myšlienku niekoľkými slovami?',['Neistý','Ozdobný','Stručný','Opakujúci sa'],'Argumentácia vedie k záveru. K čomu vedie výpočet?'],
 sr: ['Сви финансирани пројекти су прегледани. Пројекат K је финансиран. Који закључак следи?','Судија не даје предност ниједној страни. Која га реч описује?',['Непристрасан','Несигуран','Неспреман','Необичан'],'Архив садржи документе. Шта садржи антологија?','Која реч описује текст који изражава мисао са мало речи?',['Несигуран','Украсан','Сажет','Понављајући'],'Аргументација води до закључка. До чега води израчунавање?'],
 sv: ['Alla finansierade projekt granskades. Projekt K finansierades. Vilken slutsats följer?','En domare gynnar inte någon av parterna. Vilket ord beskriver domaren?',['Opartisk','Osäker','Oförberedd','Ovanlig'],'Ett arkiv innehåller dokument. Vad innehåller en antologi?','Vilket ord beskriver en text som uttrycker sin poäng med få ord?',['Osäker','Dekorativ','Kortfattad','Upprepande'],'En argumentation leder till en slutsats. Vad leder en beräkning till?'],
 th: ['โครงการที่ได้รับทุนทุกโครงการผ่านการตรวจสอบแล้ว โครงการ K ได้รับทุน ข้อสรุปใดจึงเป็นจริงแน่นอน?','ผู้ตัดสินไม่เข้าข้างฝ่ายใด คำใดอธิบายลักษณะนี้?',['เป็นกลาง','ไม่แน่ใจ','ไม่พร้อม','แปลกไปจากปกติ'],'หอจดหมายเหตุเก็บเอกสาร แล้วหนังสือรวมวรรณกรรมเก็บรวบรวมสิ่งใด?','คำใดอธิบายข้อความที่ใช้คำเพียงเล็กน้อยเพื่อสื่อใจความ?',['ไม่แน่นอน','เน้นการตกแต่ง','กระชับ','ซ้ำไปซ้ำมา'],'การให้เหตุผลนำไปสู่ข้อสรุป แล้วการคำนวณนำไปสู่สิ่งใด?'],
 tr: ['Finanse edilen tüm projeler incelendi. K projesi finanse edildi. Bundan hangi sonuç çıkar?','Bir hakem iki taraftan hiçbirini kayırmıyor. Onu hangi sözcük tanımlar?',['Tarafsız','Kararsız','Hazırlıksız','Sıra dışı'],'Arşiv belgeler içerir. Bir antoloji ne içerir?','Düşüncesini az sözcükle anlatan bir metni hangi sözcük tanımlar?',['Belirsiz','Süslü','Özlü','Tekrarlı'],'Akıl yürütme bir sonuca ulaştırır. Hesaplama neye ulaştırır?'],
 uk: ['Усі профінансовані проєкти перевірено. Проєкт K профінансовано. Який висновок із цього випливає?','Суддя не надає переваги жодній зі сторін. Яке слово його описує?',['Неупереджений','Невпевнений','Непідготовлений','Незвичайний'],'Архів містить документи. Що містить антологія?','Яке слово описує текст, що передає думку небагатьма словами?',['Невизначений','Декоративний','Стислий','Повторюваний'],'Аргументація веде до висновку. До чого веде обчислення?'],
 vi: ['Tất cả các dự án được tài trợ đều đã được xem xét. Dự án K được tài trợ. Kết luận nào chắc chắn đúng?','Một trọng tài không thiên vị bên nào. Từ nào mô tả người đó?',['Công tâm','Không chắc chắn','Chưa chuẩn bị','Khác thường'],'Kho lưu trữ chứa các tài liệu. Vậy một tuyển tập văn học chứa gì?','Từ nào mô tả văn bản diễn đạt ý bằng ít từ?',['Không rõ ràng','Hoa mỹ','Ngắn gọn','Lặp đi lặp lại'],'Lập luận dẫn đến kết luận. Vậy phép tính dẫn đến điều gì?'],
};

export function proofreadCopy(slug, locale, c, english) {
 proofreadSubtitle(locale,c,english);
 proofreadVisualLabels(locale,c,english);
 const qs=Object.assign({},...Object.values(c.stages).map(s=>s.questions));
 proofreadClearRoutes(slug,locale,qs);
 proofreadPuzzles(slug,locale,qs);
 proofreadClinical(slug,locale,qs);
 proofreadHeadings(slug,locale,c);
 proofreadTerms(slug,locale,qs);
 const [funded,impartial,impartialAnswers,anthology,concise,conciseAnswers,calculation]=universityCopy[locale];
 const answers=values=>Object.fromEntries(values.map((v,i)=>[`a${i+1}`,v]));
 if(slug==='harvard'){
  qs['harvard-s2q1'].question=funded;
  qs['harvard-s2q8'].question=impartial;
  qs['harvard-s2q8'].answers=answers(impartialAnswers);
  const [prompt,a1,a2]=trialCopy[locale];
  qs['harvard-s4q4'].question=prompt;
  Object.assign(qs['harvard-s4q4'].answers,{a1,a2});
 }
 if(slug==='raf'){
  const [above,higher,a3,a4]=rafContext[locale];
  qs['raf-q6'].question=above;
  qs['raf-q6'].answers=answers(['Flying Officer','Squadron Leader','Wing Commander','Group Captain']);
  qs['raf-round3-new2'].question=higher;
  qs['raf-round3-new2'].answers={a1:'Wing Commander',a2:'Squadron Leader',a3,a4};
 }
 if(slug==='oxford'){
  qs['oxford-s1q1'].question=anthology;
  qs['oxford-s1q5'].question=concise;
  qs['oxford-s1q5'].answers=answers(conciseAnswers);
  qs['oxford-s4q5'].question=calculation;
  if(locale==='ja')qs['oxford-s1q1'].answers.a2='選び抜かれた文学作品';
  const table={ar:'جدول',da:'Tabel',fil:'Talahanayan',he:'טבלה',ja:'表',pl:'Tabela',sr:'Табела'};
  if(table[locale])qs['oxford-s4q5'].answers.a3=table[locale];
 }
 return c;
}
