const seer = 'https://training.seer.cancer.gov/anatomy/';
export default {
  slug: 'anatomy',
  summary: 'Explore the structures and systems behind everyday movement, breathing and thought.',
  about: 'Explore the human body through organs, bones, movement, circulation and the senses. Each set connects familiar body parts with the jobs they do.\n\nChoose one answer each time, then discover a new topic at the checkpoint. Your final score includes a breakdown of your strongest areas and an optional review of missed answers.\n\nQuestions use standard adult anatomy unless stated otherwise. Natural variation between individuals is possible.',
  sources: {
    body: seer + 'body/', bones: seer + 'skeletal/divisions/appendicular.html',
    skull: seer + 'skeletal/divisions/axial.html', joints: seer + 'skeletal/articulations.html',
    muscle: seer + 'muscular/types.html', attachment: seer + 'muscular/structure.html',
    arms: seer + 'muscular/groups/upper.html', legs: seer + 'muscular/groups/lower.html',
    heart: seer + 'cardiovascular/heart/structure.html', blood: seer + 'cardiovascular/blood/',
    vessels: seer + 'cardiovascular/blood/classification.html', circulation: seer + 'cardiovascular/blood/pathways.html',
    lungs: seer + 'respiratory/passages/bronchi.html', breathing: seer + 'respiratory/mechanics.html',
    airway: seer + 'respiratory/passages/larynx.html', nose: seer + 'respiratory/passages/nose.html',
    digestive: seer + 'digestive/regions/intestine.html', accessory: seer + 'digestive/regions/accessory.html',
    stomach: seer + 'digestive/regions/stomach.html', mouth: seer + 'digestive/regions/mouth.html',
    nerve: seer + 'nervous/tissue.html', brain: seer + 'nervous/organization/cns.html',
    peripheral: seer + 'nervous/organization/pns.html',
    eye: 'https://www.nei.nih.gov/eye-health-information/healthy-vision/how-eyes-work',
    kidney: seer + 'urinary/components/kidney.html', ureters: seer + 'urinary/components/ureters.html',
    bladder: seer + 'urinary/components/bladder.html', pancreas: seer + 'endocrine/glands/pancreas.html',
    adrenal: seer + 'endocrine/glands/adrenal.html', thyroid: seer + 'endocrine/glands/thyroid.html',
    terms: seer + 'body/terminology.html',
  },
  rounds: [
    { title: 'Body Basics', category: 'organs', checkpoint: 'Your anatomy snapshot', feedback: 'Body basics: {profile}. Ready to look closer?', teaser: 'Name the bones behind everyday movements.', questions: [
      ['Which organ pumps blood around the body?', 'Heart', 'Liver', 'Lung', 'Kidney', 'heart'],
      ['How many chambers does the human heart have?', 'Four', 'Two', 'Three', 'Six', 'heart'],
      ['Which pair of organs takes oxygen from the air?', 'Lungs', 'Kidneys', 'Ovaries', 'Adrenal glands', 'lungs'],
      ['The cerebellum belongs to which organ?', 'Brain', 'Heart', 'Liver', 'Stomach', 'brain'],
      ['Which organs filter blood to produce urine?', 'Kidneys', 'Lungs', 'Salivary glands', 'Ovaries', 'kidney'],
      ['Which organ churns food and mixes it with acid?', 'Stomach', 'Gallbladder', 'Spleen', 'Bladder', 'stomach'],
      ['Which organ stores urine before it leaves the body?', 'Bladder', 'Pancreas', 'Liver', 'Stomach', 'bladder'],
    ] },
    { title: 'Bones and Joints', category: 'skeletal', checkpoint: 'The skeleton takes shape', feedback: 'Bones and joints: {profile}. Now add movement.', teaser: 'Find out what makes muscles pull and joints bend.', questions: [
      ['What is the anatomical name for the kneecap?', 'Patella', 'Scapula', 'Clavicle', 'Sternum', 'bones'],
      ['Which bone runs through the upper arm?', 'Humerus', 'Radius', 'Tibia', 'Femur', 'bones'],
      ['Which bone is commonly called the collarbone?', 'Clavicle', 'Mandible', 'Fibula', 'Sacrum', 'bones'],
      ['Which bone forms the lower jaw?', 'Mandible', 'Maxilla', 'Sternum', 'Scapula', 'skull'],
      ['What is the anatomical name for the thigh bone?', 'Femur', 'Tibia', 'Fibula', 'Ulna', 'bones'],
      ['Which type of joint is the hip?', 'Ball-and-socket', 'Hinge', 'Pivot', 'Fixed', 'joints'],
      ['Which group of bones forms the wrist?', 'Carpals', 'Tarsals', 'Metatarsals', 'Vertebrae', 'bones'],
    ] },
    { title: 'Made to Move', category: 'body_systems', checkpoint: 'Movement decoded', feedback: 'Muscles and movement: {profile}. Follow the next connection.', teaser: 'Trace the route that keeps blood moving.', questions: [
      ['What usually connects a skeletal muscle to a bone?', 'Tendon', 'Artery', 'Nerve cell', 'Cartilage disc', 'attachment'],
      ['Which muscle type mainly moves your skeleton?', 'Skeletal muscle', 'Cardiac muscle', 'Smooth muscle', 'Intestinal muscle', 'muscle'],
      ['Which muscle type forms the muscular wall of the heart?', 'Cardiac muscle', 'Skeletal muscle', 'Smooth muscle', 'Tendon tissue', 'muscle'],
      ['Which muscle type moves food through the intestines?', 'Smooth muscle', 'Cardiac muscle', 'Skeletal muscle', 'Bone tissue', 'muscle'],
      ['Which upper-arm muscle helps straighten the elbow?', 'Triceps', 'Biceps', 'Deltoid', 'Trapezius', 'arms'],
      ['The quadriceps mainly straighten which joint?', 'Knee', 'Elbow', 'Wrist', 'Shoulder', 'legs'],
      ['Most skeletal muscle movements are described as what?', 'Voluntary', 'Digestive', 'Cardiac', 'Hormonal', 'muscle'],
    ] },
    { title: 'Heart and Blood', category: 'body_systems', checkpoint: 'Your circulation snapshot', feedback: 'Heart and blood: {profile}. Keep the connections coming.', teaser: 'Follow a breath from the nose to the lungs.', questions: [
      ['Which vessels carry blood away from the heart?', 'Arteries', 'Veins', 'Lymph vessels', 'Venules', 'vessels'],
      ['Which vessels are the main sites of exchange with body tissues?', 'Capillaries', 'Large arteries', 'Large veins', 'Lymph ducts', 'vessels'],
      ['Which blood cells carry most of the oxygen in blood?', 'Red blood cells', 'White blood cells', 'Platelets', 'Stem cells', 'blood'],
      ['Which blood components help form clots?', 'Platelets', 'Red blood cells', 'Antibodies', 'Glucose molecules', 'blood'],
      ['Which heart chamber pumps blood toward the lungs?', 'Right ventricle', 'Left ventricle', 'Right atrium', 'Left atrium', 'circulation'],
      ['Which large artery carries blood from the left ventricle?', 'Aorta', 'Pulmonary artery', 'Vena cava', 'Pulmonary vein', 'heart'],
      ['What is the liquid component of blood called?', 'Plasma', 'Marrow', 'Cartilage', 'Bile', 'blood'],
    ] },
    { title: 'Every Breath', category: 'organs', checkpoint: 'Breathing comes into focus', feedback: 'Breathing: {profile}. Next, follow another journey inside.', teaser: 'See what happens after the first bite.', questions: [
      ['Which major muscle sits beneath the lungs and helps you inhale?', 'Diaphragm', 'Biceps', 'Masseter', 'Deltoid', 'breathing'],
      ['What is the anatomical name for the windpipe?', 'Trachea', 'Larynx', 'Pharynx', 'Bronchiole', 'airway'],
      ['Where does most gas exchange happen in the lungs?', 'Alveoli', 'Vocal folds', 'Nasal passages', 'Main bronchi', 'lungs'],
      ['Which structure contains the vocal folds?', 'Larynx', 'Diaphragm', 'Trachea', 'Alveolus', 'airway'],
      ['The trachea divides into two main tubes called what?', 'Bronchi', 'Ureters', 'Arteries', 'Sinuses', 'lungs'],
      ['How many lobes does the right lung usually have?', 'Three', 'One', 'Two', 'Four', 'lungs'],
      ['What do the nasal passages help do to incoming air?', 'Warm, moisten and filter it', 'Remove all its oxygen', 'Turn it into carbon dioxide', 'Send it into the stomach', 'nose'],
    ] },
    { title: 'The Food Journey', category: 'organs', checkpoint: 'Digestion mapped', feedback: 'Digestion: {profile}. Switch from food to fast signals.', teaser: 'Explore the brain and the messages it sends.', questions: [
      ['Which organ produces bile?', 'Liver', 'Gallbladder', 'Stomach', 'Spleen', 'accessory'],
      ['Which organ stores and concentrates bile?', 'Gallbladder', 'Pancreas', 'Kidney', 'Appendix', 'accessory'],
      ['Where are most nutrients from food absorbed?', 'Small intestine', 'Stomach', 'Large intestine', 'Mouth', 'digestive'],
      ['Which part of the small intestine comes first?', 'Duodenum', 'Jejunum', 'Ileum', 'Colon', 'digestive'],
      ['What do the villi of the small intestine increase?', 'Surface area for absorption', 'Number of teeth', 'Volume of the lungs', 'Thickness of bone', 'digestive'],
      ['Which digestive organ absorbs water from the remaining food residue?', 'Large intestine', 'Gallbladder', 'Salivary gland', 'Pancreas', 'digestive'],
      ['Which glands release saliva into the mouth?', 'Salivary glands', 'Adrenal glands', 'Thyroid glands', 'Sweat glands', 'mouth'],
    ] },
    { title: 'Brain and Signals', category: 'body_systems', checkpoint: 'The signal is clearer', feedback: 'Brain and nerves: {profile}. Put your senses in the spotlight.', teaser: 'Look inside the structures that make sight possible.', questions: [
      ['Which two structures form the central nervous system?', 'Brain and spinal cord', 'Heart and lungs', 'Eyes and ears', 'Muscles and tendons', 'brain'],
      ['What is the main signalling cell of the nervous system?', 'Neuron', 'Platelet', 'Red blood cell', 'Bone cell', 'nerve'],
      ['Which part of a neuron usually carries impulses away from its cell body?', 'Axon', 'Dendrite', 'Nucleus', 'Cell membrane receptor', 'nerve'],
      ['Which brain region helps coordinate balance and movement?', 'Cerebellum', 'Thalamus', 'Hypothalamus', 'Temporal lobe', 'brain'],
      ['What protects the spinal cord along the back?', 'Vertebral column', 'Sternum', 'Pelvis alone', 'Clavicle', 'brain'],
      ['Which division controls many involuntary functions, such as digestion?', 'Autonomic nervous system', 'Somatic nervous system', 'Skeletal system', 'Integumentary system', 'peripheral'],
      ['Which part is the largest region of the human brain?', 'Cerebrum', 'Cerebellum', 'Medulla', 'Pons', 'brain'],
    ] },
    { title: 'Inside the Eye', category: 'organs', checkpoint: 'A closer look', feedback: 'Eye anatomy: {profile}. There is more happening beneath the surface.', teaser: 'Meet the body’s filters and chemical messengers.', questions: [
      ['Which clear structure covers the front of the eye?', 'Cornea', 'Retina', 'Iris', 'Optic nerve', 'eye'],
      ['Which part of the eye gives it its visible colour?', 'Iris', 'Pupil', 'Lens', 'Retina', 'eye'],
      ['Light enters the eye through an opening called what?', 'Pupil', 'Optic nerve', 'Lens', 'Retina', 'eye'],
      ['Which light-sensitive layer lines the back of the eye?', 'Retina', 'Cornea', 'Iris', 'Eyelid', 'eye'],
      ['Which structure changes shape to help focus light on the retina?', 'Lens', 'Optic nerve', 'Eyelash', 'Pupil', 'eye'],
      ['Which nerve carries visual signals toward the brain?', 'Optic nerve', 'Vagus nerve', 'Facial nerve', 'Sciatic nerve', 'eye'],
      ['Which cells turn light into electrical signals in the retina?', 'Photoreceptors', 'Platelets', 'Muscle fibres', 'Red blood cells', 'eye'],
    ] },
    { title: 'Filters and Hormones', category: 'body_systems', checkpoint: 'Hidden systems revealed', feedback: 'Filters and hormones: {profile}. Time to connect the clues.', teaser: 'Use anatomy’s direction words to find your way.', questions: [
      ['What is the basic functional unit of a kidney?', 'Nephron', 'Neuron', 'Alveolus', 'Villus', 'kidney'],
      ['Which tubes carry urine from the kidneys to the bladder?', 'Ureters', 'Bronchi', 'Bile ducts', 'Arteries', 'ureters'],
      ['Which organ produces insulin?', 'Pancreas', 'Spleen', 'Gallbladder', 'Stomach', 'pancreas'],
      ['Where are the adrenal glands located?', 'Above the kidneys', 'Behind the kneecaps', 'Inside the lungs', 'Below the tongue', 'adrenal'],
      ['Which gland lies in the neck, just below the larynx?', 'Thyroid', 'Pineal', 'Adrenal', 'Pituitary', 'thyroid'],
      ['Which pancreatic hormone helps raise blood glucose?', 'Glucagon', 'Insulin', 'Melatonin', 'Thyroxine', 'pancreas'],
      ['Which glands help regulate blood calcium through parathyroid hormone?', 'Parathyroid glands', 'Salivary glands', 'Sweat glands', 'Pineal gland', 'thyroid'],
    ] },
    { title: 'Anatomy Connections', category: 'body_systems', checkpoint: 'Your anatomy result is ready', questions: [
      ['In anatomical language, what does anterior mean?', 'Toward the front', 'Toward the back', 'Farther from the trunk', 'Closer to the feet', 'terms'],
      ['Which term means closer to the body’s midline?', 'Medial', 'Lateral', 'Distal', 'Superficial', 'terms'],
      ['Which term means farther from the trunk along a limb?', 'Distal', 'Proximal', 'Medial', 'Superior', 'terms'],
      ['The elbow is closer to the trunk than the wrist. Which term describes it?', 'Proximal', 'Distal', 'Inferior', 'Superficial', 'terms'],
      ['Which plane divides the body into upper and lower parts?', 'Transverse', 'Sagittal', 'Frontal', 'Coronal', 'terms'],
      ['Which plane divides the body into front and back parts?', 'Frontal', 'Sagittal', 'Transverse', 'Horizontal', 'terms'],
      ['In standard anatomical position, which way do the palms face?', 'Forward', 'Backward', 'Toward the thighs', 'Toward the chest', 'terms'],
    ] },
  ],
};
