export default {
  slug: 'bible',
  summary: 'Follow familiar stories, recognise the people and connect clues from across the Bible.',
  about: 'Explore people, places and events from the Old and New Testaments. Each set brings a fresh group of stories, from Genesis to the early Church.\n\nChoose one answer each time. At the checkpoints, see how you did on the topic and discover what comes next. Reveal your overall score and optionally review missed answers at the end.\n\nQuestions describe the biblical accounts and avoid wording that depends on a particular modern translation. Your result reflects this quiz attempt, not your faith.',
  sourceUrl: reference => `https://bible.usccb.org/bible/${reference}`,
  rounds: [
    { title: 'In the Beginning', category: 'people', checkpoint: 'Your Bible story snapshot', feedback: 'Genesis stories: {profile}. Follow the story into new territory.', teaser: 'A journey out of Egypt brings a fresh set of clues.', questions: [
      ['Who builds the ark in Genesis?', 'Noah', 'Moses', 'Abraham', 'David', 'genesis/6'],
      ['What is the name of the garden where Adam and Eve live?', 'Eden', 'Gethsemane', 'Bethany', 'Carmel', 'genesis/2'],
      ['What sign of a covenant appears after the flood?', 'A rainbow', 'A burning bush', 'A pillar of fire', 'A stone tablet', 'genesis/9'],
      ['Which tower is linked to the confusion of languages?', 'Babel', 'Siloam', 'Jericho', 'Antonia', 'genesis/11'],
      ['Who is the son of Abraham and Sarah?', 'Isaac', 'Ishmael', 'Jacob', 'Esau', 'genesis/21'],
      ['Which brothers are twins?', 'Jacob and Esau', 'Moses and Aaron', 'Cain and Abel', 'Joseph and Benjamin', 'genesis/25'],
      ['Who interprets Pharaoh’s dreams in Genesis?', 'Joseph', 'Daniel', 'Joshua', 'Samuel', 'genesis/41'],
    ] },
    { title: 'Out of Egypt', category: 'people', checkpoint: 'The journey continues', feedback: 'Exodus: {profile}. New leaders bring new challenges.', teaser: 'Meet the judges and kings behind famous moments.', questions: [
      ['Who leads the Israelites out of Egypt?', 'Moses', 'Noah', 'David', 'Solomon', 'exodus/14'],
      ['Who is Moses’ brother and spokesman?', 'Aaron', 'Caleb', 'Joshua', 'Gideon', 'exodus/4'],
      ['What unusual sight draws Moses’ attention in Exodus 3?', 'A burning bush that is not consumed', 'A river flowing uphill', 'A star above a stable', 'A wall falling without a battle', 'exodus/3'],
      ['What marks the Israelites’ doorposts at the first Passover?', 'Blood from the Passover animal', 'Water from the Nile', 'Olive oil', 'Ash from the fire', 'exodus/12'],
      ['What food appears on the ground in the wilderness?', 'Manna', 'Grapes', 'Lentils', 'Figs', 'exodus/16'],
      ['At which mountain does Moses receive the covenant instructions?', 'Sinai', 'Carmel', 'Zion', 'Tabor', 'exodus/19'],
      ['What object do the people make while Moses is on the mountain?', 'A golden calf', 'A silver crown', 'A bronze chariot', 'A wooden throne', 'exodus/32'],
    ] },
    { title: 'Judges and Kings', category: 'people', checkpoint: 'The leaders take shape', feedback: 'Judges and kings: {profile}. Look beyond the battlefield.', teaser: 'Courage and loyalty change the next stories.', questions: [
      ['Who leads Israel after Moses?', 'Joshua', 'Samuel', 'Saul', 'Elijah', 'joshua/1'],
      ['Whose strength is linked to his uncut hair?', 'Samson', 'Gideon', 'David', 'Saul', 'judges/16'],
      ['Which woman serves as a judge in Israel?', 'Deborah', 'Ruth', 'Esther', 'Hannah', 'judges/4'],
      ['Who hears God calling during the night as a boy?', 'Samuel', 'Solomon', 'Elisha', 'Josiah', '1samuel/3'],
      ['Who is anointed as Israel’s first king?', 'Saul', 'David', 'Solomon', 'Rehoboam', '1samuel/10'],
      ['What does David use to strike Goliath?', 'A sling and a stone', 'A spear and a shield', 'A bow and an arrow', 'A sword and a helmet', '1samuel/17'],
      ['What does Solomon ask God to give him to govern well?', 'An understanding heart', 'A larger army', 'A longer coastline', 'A golden palace', '1kings/3'],
    ] },
    { title: 'Courage and Loyalty', category: 'people', checkpoint: 'The people stand out', feedback: 'Courage and loyalty: {profile}. Listen for a different kind of clue.', teaser: 'Poetry and wisdom put familiar words in context.', questions: [
      ['Who is Ruth’s mother-in-law?', 'Naomi', 'Esther', 'Miriam', 'Hannah', 'ruth/1'],
      ['Whom does Ruth marry in Bethlehem?', 'Boaz', 'Obed', 'Jesse', 'Elimelech', 'ruth/4'],
      ['Which queen risks approaching the king to help her people?', 'Esther', 'Jezebel', 'Athaliah', 'Vashti', 'esther/5'],
      ['Who is thrown into a den of lions?', 'Daniel', 'Joseph', 'Jeremiah', 'Ezekiel', 'daniel/6'],
      ['Who is swallowed by a great fish?', 'Jonah', 'Amos', 'Hosea', 'Micah', 'jonah/2'],
      ['Which prophet confronts the prophets of Baal on Mount Carmel?', 'Elijah', 'Isaiah', 'Jeremiah', 'Nathan', '1kings/18'],
      ['Who follows Elijah and receives his cloak?', 'Elisha', 'Samuel', 'Ezra', 'Nehemiah', '2kings/2'],
    ] },
    { title: 'Poetry and Wisdom', category: 'foundations', checkpoint: 'Wisdom comes into focus', feedback: 'Poetry and wisdom: {profile}. A new chapter of stories begins.', teaser: 'Follow the clues around the birth of Jesus.', questions: [
      ['Which book is a collection of prayers and songs?', 'Psalms', 'Numbers', 'Joshua', 'Acts', 'psalms/0'],
      ['Which book centres on a man who suffers and debates with his friends?', 'Job', 'Ruth', 'Esther', 'Jonah', 'job/0'],
      ['Which book is especially associated with short sayings about wise living?', 'Proverbs', 'Exodus', 'Leviticus', 'Revelation', 'proverbs/0'],
      ['Which book says there is a time to be born and a time to die?', 'Ecclesiastes', 'Haggai', 'Malachi', 'Lamentations', 'ecclesiastes/3'],
      ['In Psalm 23, the Lord is compared to which figure?', 'A shepherd', 'A potter', 'A merchant', 'A builder', 'psalms/23'],
      ['Who builds the Temple in Jerusalem in 1 Kings?', 'Solomon', 'Saul', 'Samuel', 'Gideon', '1kings/6'],
      ['Which queen visits Solomon to test his wisdom?', 'The Queen of Sheba', 'The Queen of Egypt', 'Queen Esther', 'Queen Jezebel', '1kings/10'],
    ] },
    { title: 'The Gospel Begins', category: 'new_testament', checkpoint: 'The opening scenes', feedback: 'Gospel beginnings: {profile}. Follow the story beyond Bethlehem.', teaser: 'Meet the disciples and recall the miracles.', questions: [
      ['Which angel tells Mary she will give birth to Jesus?', 'Gabriel', 'Michael', 'Raphael', 'Uriel', 'luke/1'],
      ['In which town is Jesus born?', 'Bethlehem', 'Nazareth', 'Jericho', 'Capernaum', 'matthew/2'],
      ['Where does Mary lay the newborn Jesus in Luke’s account?', 'In a manger', 'In a boat', 'On a throne', 'Beside the Temple altar', 'luke/2'],
      ['Who hear the angels’ announcement while watching their flocks?', 'Shepherds', 'Fishermen', 'Tax collectors', 'Soldiers', 'luke/2'],
      ['Which ruler questions the visitors looking for the newborn king?', 'Herod', 'Pilate', 'Felix', 'Caesar Augustus', 'matthew/2'],
      ['Who takes Mary and Jesus to Egypt after a warning in a dream?', 'Joseph', 'Zechariah', 'Simeon', 'Andrew', 'matthew/2'],
      ['Where do Mary and Joseph find Jesus when he is twelve?', 'In the Temple', 'At the Jordan River', 'In the royal palace', 'On Mount Sinai', 'luke/2'],
    ] },
    { title: 'People and Miracles', category: 'new_testament', checkpoint: 'The connections grow', feedback: 'People and miracles: {profile}. Listen to the stories within the story.', teaser: 'Every parable hides a detail worth remembering.', questions: [
      ['Who baptises Jesus in the Jordan River?', 'John the Baptist', 'Peter', 'James', 'Philip', 'mark/1'],
      ['What is the occupation of Simon Peter and Andrew when Jesus calls them?', 'Fishermen', 'Carpenters', 'Tax collectors', 'Shepherds', 'matthew/4'],
      ['Which disciple is sitting at a tax booth when Jesus calls him in Matthew 9?', 'Matthew', 'Thomas', 'Andrew', 'James', 'matthew/9'],
      ['Who climbs a tree to see Jesus?', 'Zacchaeus', 'Nicodemus', 'Bartimaeus', 'Jairus', 'luke/19'],
      ['At Cana, Jesus turns water into what?', 'Wine', 'Oil', 'Milk', 'Honey', 'john/2'],
      ['Whom does Jesus call out of a tomb at Bethany?', 'Lazarus', 'Stephen', 'Barnabas', 'Zechariah', 'john/11'],
      ['How many loaves are available before the feeding of the five thousand?', 'Five', 'Three', 'Seven', 'Twelve', 'mark/6'],
    ] },
    { title: 'Inside the Parables', category: 'new_testament', checkpoint: 'You followed the clues', feedback: 'Parables: {profile}. The story takes a decisive turn.', teaser: 'Recall the people and places of the Passion accounts.', questions: [
      ['Who helps the injured traveller in the parable in Luke 10?', 'A Samaritan', 'A priest', 'A Levite', 'A Roman governor', 'luke/10'],
      ['What does the father do when the younger son returns in Luke 15?', 'Welcomes him and celebrates', 'Refuses to see him', 'Sends him back to the fields', 'Asks a judge to punish him', 'luke/15'],
      ['In the parable of the sower, what chokes some of the plants?', 'Thorns', 'Snow', 'Sand', 'Vines from a vineyard', 'mark/4'],
      ['Which small seed does Jesus compare with the kingdom?', 'Mustard', 'Olive', 'Fig', 'Date', 'mark/4'],
      ['In the lost sheep parable, how many sheep are missing from the flock?', 'One', 'Two', 'Five', 'Ten', 'luke/15'],
      ['What does the wise builder build his house on?', 'Rock', 'Sand', 'Clay pots', 'Loose branches', 'matthew/7'],
      ['What does the servant with one talent do with it in Matthew 25?', 'Buries it in the ground', 'Buys a vineyard', 'Gives it to a neighbour', 'Exchanges it for livestock', 'matthew/25'],
    ] },
    { title: 'Cross and Resurrection', category: 'new_testament', checkpoint: 'The key moments connect', feedback: 'Passion and resurrection: {profile}. Follow what happened next.', teaser: 'The early Church takes the story into new places.', questions: [
      ['Which disciple betrays Jesus?', 'Judas Iscariot', 'Thomas', 'Philip', 'Andrew', 'matthew/26'],
      ['Where does Jesus pray before his arrest in Matthew 26?', 'Gethsemane', 'Bethlehem', 'Cana', 'Nazareth', 'matthew/26'],
      ['Who denies knowing Jesus three times?', 'Peter', 'John', 'James', 'Matthew', 'luke/22'],
      ['Which Roman governor questions Jesus before the crucifixion?', 'Pontius Pilate', 'Felix', 'Festus', 'Quirinius', 'john/18'],
      ['Who is compelled to carry Jesus’ cross?', 'Simon of Cyrene', 'Simon the Pharisee', 'Joseph of Arimathea', 'Nicodemus', 'mark/15'],
      ['Who asks Pilate for Jesus’ body and places it in a tomb?', 'Joseph of Arimathea', 'Zacchaeus', 'Bartimaeus', 'Cleopas', 'mark/15'],
      ['Who encounters the risen Jesus outside the tomb in John 20?', 'Mary Magdalene', 'Elizabeth', 'Martha', 'Anna', 'john/20'],
    ] },
    { title: 'The Early Church', category: 'new_testament', checkpoint: 'Your Bible result is ready', questions: [
      ['Which event in Acts 2 is associated with the Holy Spirit’s descent?', 'Pentecost', 'Passover in Egypt', 'The Transfiguration', 'The Annunciation', 'acts/2'],
      ['Who is stoned to death after addressing the council in Acts 7?', 'Stephen', 'Philip', 'Timothy', 'Titus', 'acts/7'],
      ['Saul is travelling toward which city when he encounters Jesus?', 'Damascus', 'Athens', 'Rome', 'Corinth', 'acts/9'],
      ['Who travels with Paul on the mission that begins in Acts 13?', 'Barnabas', 'Moses', 'Elijah', 'Solomon', 'acts/13'],
      ['Who is praying and singing in prison with Paul in Acts 16?', 'Silas', 'Apollos', 'Mark', 'Luke', 'acts/16'],
      ['Which seller of purple cloth welcomes Paul’s group in Philippi?', 'Lydia', 'Priscilla', 'Phoebe', 'Dorcas', 'acts/16'],
      ['On which island does John say he received the visions in Revelation?', 'Patmos', 'Crete', 'Cyprus', 'Malta', 'revelation/1'],
    ] },
  ],
};
