import {q, universityPack} from './university-shared.mjs';
export default universityPack('cambridge', 'Follow patterns, compare measurements and test explanations through experiments and spatial puzzles.', [
  ['Find the Pattern', 'pattern_analysis', 'Your first pattern snapshot', 'Next, make sense of the measurements.', [
    q('The gaps increase by 2: 5, 7, 11, 17. What comes next?', '25', '21', '23', '27', 'The gaps are 2, 4, 6, then 8; 17+8=25.'),
    q('Each term is tripled: 2, 6, 18, 54. What comes next?', '162', '108', '144', '216', '54 × 3 = 162.'),
    q('Subtract 2, then 3, then 4: 20, 18, 15, 11. Subtract 5 next. What follows?', '6', '5', '7', '8', '11 − 5 = 6.'),
    q('The group repeats: circle, square, square. What is the seventh shape?', 'Circle', 'Square', 'Triangle', 'Diamond', 'Positions 1, 4 and 7 begin the repeated group.'),
    q('Starting at 3, add 2 then double to get each next term. What comes immediately after 10?', '24', '12', '20', '22', '(10 + 2) × 2 = 24.'),
    q('In 1, 10, 2, 20, 3, 30, the odd positions rise by 1 and even positions by 10. What is the next term?', '4', '40', '31', '10', 'The next position is odd, so 3 increases to 4.'),
    q('Every term is the sum of the previous two: 2, 3, 5, 8. What comes next?', '13', '10', '11', '16', '5 + 8 = 13.'),
  ]],
  ['Measure the Change', 'numerical_reasoning', 'The measurements connect', 'A fair comparison needs more than two different results.', [
    q('Water rises from 40 mL to 55 mL when an object is submerged. What volume is displaced?', '15 mL', '10 mL', '40 mL', '95 mL', '55 − 40 = 15 mL.'),
    q('A timer reads 2 minutes 30 seconds. How many seconds is that?', '150', '130', '120', '230', '2 × 60 + 30 = 150.'),
    q('A length is 1.5 metres. How many centimetres is that?', '150', '15', '1,500', '105', '1 metre is 100 cm; 1.5 × 100 = 150.'),
    q('A sample has mass 24 g and volume 8 cm³. Using density = mass ÷ volume, what is its density?', '3 g/cm³', '16 g/cm³', '32 g/cm³', '192 g/cm³', '24 ÷ 8 = 3.'),
    q('A reading changes from −3 to 5. How much has it increased?', '8', '2', '5', '15', '5 − (−3) = 8.'),
    q('A scale always reads 2 g too high. It shows 18 g. What is the true mass?', '16 g', '18 g', '20 g', '36 g', 'Subtract the known +2 g error.'),
    q('A container holds 0.75 litres. How many millilitres is that?', '750', '75', '7,500', '0.075', '1 litre is 1,000 mL; 0.75 × 1,000 = 750.'),
  ]],
  ['Build a Fair Test', 'experimental_design', 'The experiment takes shape', 'What do the results show before we explain them?', [
    q('To test whether light affects plant growth, which factor should you deliberately vary?', 'The amount of light', 'Every growing condition at once', 'The final measured height', 'The plant labels only', 'Light is the independent variable named in the question.'),
    q('In that light experiment, which is an outcome to measure?', 'Growth over the same period', 'The planned lamp setting', 'The name of the experiment', 'The researcher’s prediction only', 'Growth is the response whose relationship with light is being tested.'),
    q('Two groups receive different light levels. Which should stay alike for a fair comparison?', 'Water, soil and plant type', 'Their final growth', 'The light levels', 'The result of each measurement', 'Other relevant growing conditions should be controlled.'),
    q('Why repeat a measurement under the same conditions?', 'To assess variation and reduce reliance on one reading', 'To guarantee the desired answer', 'To make every reading identical', 'To avoid recording results', 'Repeated measurements reveal variability; they do not guarantee an outcome.'),
    q('A researcher assigns subjects to groups by chance. What is the main purpose?', 'To reduce systematic allocation differences', 'To make all outcomes identical', 'To choose only favourable results', 'To remove the need for a comparison', 'Random assignment limits allocation bias.'),
    q('An experiment changes both temperature and container size. What is hard to identify?', 'Which change caused an observed difference', 'Whether the containers exist', 'The names of the variables', 'Whether any readings were recorded', 'The two changes are confounded.'),
    q('Why record the method in enough detail for another person to repeat it?', 'To let others check the result independently', 'To ensure everyone gets the same answer', 'To replace all observations', 'To prevent any criticism', 'Repeatable methods allow independent testing, not guaranteed agreement.'),
  ]],
  ['Read the Results', 'data_interpretation', 'The data reveals its pattern', 'Turn, reflect and follow the movement.', [
    q('Three readings are 8, 10 and 12. What is their mean?', '10', '8', '12', '30', '(8+10+12) ÷ 3 = 10.'),
    q('Readings range from 4 to 19. What is the range?', '15', '4', '19', '23', 'Range is maximum minus minimum: 19−4=15.'),
    q('Sorted readings are 3, 4, 8, 9 and 11. What is the median?', '8', '4', '7', '9', 'The middle of five sorted readings is the third value.'),
    q('Group A has 16 successes in 20 attempts; B has 18 in 30. Which rate is higher?', 'A: 80%', 'B: 60%', 'Both: 70%', 'Both: 80%', 'A is 80%; B is 60%.'),
    q('A predicted value is 20, and the observed value is 23. What is the absolute error?', '3', '−3', '20', '43', 'Absolute error is |23−20|=3.'),
    q('A reading is 12 at minute 0 and 20 at minute 4. What is the average increase per minute?', '2', '4', '8', '5', '(20−12) ÷ 4 = 2.'),
    q('A graph shows a measured quantity rising with time. Which conclusion goes beyond the graph alone?', 'Time itself caused the rise', 'Later readings are higher', 'The quantity changed', 'A trend is visible', 'The graph shows association with time, not the causal mechanism.'),
  ]],
  ['Space and Movement', 'spatial_reasoning', 'A new viewpoint', 'A simple machine can hide a two-step rule.', [
    q('Move 2 units north, 3 east, then 2 south. Where are you relative to the start?', '3 units east', '3 units west', '2 units north', 'At the start', 'North and south cancel; 3 east remains.'),
    q('Rotate a right-pointing arrow 90° anticlockwise. Where does it point?', 'Up', 'Down', 'Left', 'Right', 'An anticlockwise quarter-turn takes right to up.'),
    q('A mark is in the bottom-left corner of a square. Reflect it across a horizontal line through the centre. Where is it?', 'Top-left', 'Top-right', 'Bottom-right', 'Bottom-left', 'Horizontal reflection exchanges top and bottom but keeps left and right.'),
    q('A square is rotated through four quarter-turns in the same direction. What is its total rotation?', '360°', '90°', '180°', '270°', '4 × 90° = 360°.'),
    q('A point moves from (1, 2) to (4, 2). What changed?', 'It moved 3 units right', 'It moved 3 units up', 'It moved 2 units left', 'It did not move', 'x increases by 3 while y stays the same.'),
    q('Which operation changes a shape’s size while keeping its proportions?', 'Uniform scaling', 'Translation only', 'Rotation only', 'Reflection only', 'Uniform scaling changes every length by the same factor.'),
    q('A cube has opposite faces A–D, B–E and C–F. If A is on top, which face is on the bottom?', 'D', 'B', 'C', 'F', 'The bottom is opposite the top, and A is paired with D.'),
  ]],
  ['Rule Machines', 'pattern_analysis', 'The mechanism is clearer', 'Does a result support the explanation—or prove it?', [
    q('A machine adds 4, then triples. What output comes from input 2?', '18', '10', '12', '24', '(2+4) × 3 = 18.'),
    q('A machine doubles, then subtracts 5. Which input gives 17?', '11', '6', '9', '12', '(17+5) ÷ 2 = 11.'),
    q('Apply y = 3x + 1. What is y when x is 5?', '16', '15', '18', '21', '3 × 5 + 1 = 16.'),
    q('Alternate adding 2 and multiplying by 2: 3, 5, 10, 12, 24. What comes next?', '26', '48', '28', '30', 'The next operation is +2.'),
    q('Every output equals input squared minus 1. What output comes from 4?', '15', '7', '16', '17', '4²−1=15.'),
    q('A rule reverses the digits, then adds 1. What does 24 become?', '43', '25', '42', '52', '24 reverses to 42; 42+1=43.'),
    q('A sequence starts at 1 and repeatedly doubles then adds 1. Which is its fourth term?', '15', '7', '8', '16', 'The terms are 1, 3, 7, 15.'),
  ]],
  ['Cause and Evidence', 'scientific_reasoning', 'The explanation faces a test', 'Ratios reveal what raw totals can hide.', [
    q('A model predicts X under stated conditions, but a valid test finds not-X. What should happen?', 'Reconsider the model or its assumptions', 'Delete the observation', 'Declare the model proven', 'Ignore every future test', 'A contrary valid observation challenges the prediction.'),
    q('Two things change together in a study. What does that alone establish?', 'An association', 'A definite cause', 'No alternative explanation', 'A permanent law', 'Co-variation alone does not identify causality.'),
    q('Which is a testable prediction?', 'The treated sample will grow at least 2 cm taller over 14 days', 'The sample will be more impressive', 'The idea feels right', 'The result will be interesting', 'It specifies a measurable outcome and time.'),
    q('A new result conflicts with earlier results. What is the most useful next step?', 'Check methods and seek replication', 'Discard it because it is new', 'Discard all earlier results immediately', 'Change the numbers to match', 'Method checking and replication investigate the disagreement.'),
    q('A result fits two different explanations. What kind of test would best distinguish them?', 'One where they predict different outcomes', 'One where both predict exactly the same outcome', 'One with no measurements', 'One chosen for its name', 'Divergent predictions allow discriminating evidence.'),
    q('A sensor gives 10, 10, 10 when the true value is 15. What is demonstrated?', 'Consistent readings with a systematic error', 'Perfect accuracy', 'Unpredictable variation only', 'No measurement error', 'The readings are repeatable but consistently too low.'),
    q('Which action preserves the integrity of an unexpected finding?', 'Record it and investigate possible reasons', 'Replace it with the predicted value', 'Hide it without explanation', 'Report only results that fit', 'Transparent recording keeps the evidence available for scrutiny.'),
  ]],
  ['Rates and Ratios', 'numerical_reasoning', 'The proportions line up', 'How well does the model match the real readings?', [
    q('A pump moves 18 litres in 3 minutes at a constant rate. How much moves in 5 minutes?', '30 litres', '24 litres', '36 litres', '90 litres', '18÷3=6 litres per minute; 6×5=30.'),
    q('A mixture is 1 part dye to 4 parts water. In 50 mL of mixture, how much is dye?', '10 mL', '12.5 mL', '20 mL', '40 mL', 'The mixture has five total parts; one fifth of 50 is 10.'),
    q('A count rises from 80 to 100. What is the percentage increase?', '25%', '20%', '80%', '125%', '20÷80×100=25%.'),
    q('An object moves 150 metres in 30 seconds at a constant speed. What is its speed?', '5 m/s', '3 m/s', '30 m/s', '45 m/s', '150÷30=5 metres per second.'),
    q('A sample is 40% red counters. There are 80 counters. How many are red?', '32', '20', '40', '48', '80×0.4=32.'),
    q('A map scale is 1 cm to 2 km. What distance does 3.5 cm represent?', '7 km', '1.75 km', '5.5 km', '14 km', '3.5×2=7 km.'),
    q('A rectangular area is 6 m by 4 m. Both lengths double. What is the new area?', '96 m²', '24 m²', '48 m²', '192 m²', 'The new lengths are 12 and 8; their product is 96.'),
  ]],
  ['Put the Model to Work', 'data_interpretation', 'The model meets the data', 'The final problems combine more than one rule.', [
    q('Predicted values are 12, 18 and 24; observations are 13, 17 and 24. What is the total absolute error?', '2', '0', '1', '3', '|13−12|+|17−18|+|24−24|=2.'),
    q('A model gives output = 2 × input + 3. Which input produces 19?', '8', '7', '9', '11', '(19−3)÷2=8.'),
    q('A sensor reads 3 units below the true value. It displays 14. What is the corrected value?', '17', '11', '14', '42', 'Add 3 to correct a reading that is 3 too low.'),
    q('A line passes through (0, 2) and (2, 6) at a constant rate. What is its value at x = 3?', '8', '6', '9', '10', 'The slope is (6−2)÷2=2; y=2x+2 gives 8.'),
    q('A predicted total is 100 and the measured total is 90. The error as a percentage of the prediction is…', '10%', '9%', '11.1%', '90%', '|90−100|÷100×100=10%.'),
    q('Which is interpolation?', 'Estimating between two measured points', 'Predicting beyond all measured points', 'Deleting an unusual point', 'Changing a unit label only', 'Interpolation estimates within the observed range.'),
    q('A model matches past data exactly. What is the strongest next check?', 'Test its predictions on new data', 'Use a longer model name', 'Hide how it was built', 'Assume all future predictions are correct', 'New data test predictive performance beyond the fitting data.'),
  ]],
  ['The Final System', 'scientific_reasoning', 'Your systems result is ready', '', [
    q('A sensor always reads 2 units high. It shows 26. The true value falls by 5. What will it show next?', '21', '19', '23', '29', 'The fixed offset remains; a true decrease of 5 also lowers the reading by 5.', 'numerical_reasoning'),
    q('Starting at 2, repeat “add 3, then double”. What is the third term?', '26', '10', '16', '20', 'The terms are 2, 10, 26.', 'pattern_analysis'),
    q('Move 3 units east, 2 north, 1 west and 2 south. Where do you finish relative to the start?', '2 units east', '2 units west', '4 units east', 'At the start', 'Vertical moves cancel; horizontal displacement is 3−1=2 east.', 'spatial_reasoning'),
    q('A test changes only temperature, measures output, and repeats each setting. Which part is the dependent variable?', 'The measured output', 'The selected temperature', 'The number of repeats', 'The unchanged container', 'The outcome measured in response to the chosen input is dependent.', 'experimental_design'),
    q('Two equal-volume samples have masses of 12 g and 18 g. Using density = mass ÷ volume, which is denser?', 'The 18 g sample', 'The 12 g sample', 'They have equal density', 'Mass is irrelevant to density', 'With equal volume, greater mass means greater density.', 'numerical_reasoning'),
    q('Model A predicts 5 and 9; Model B predicts 6 and 8. Observed values are 6 and 9. Which has lower total absolute error?', 'They are equal', 'Only A', 'Only B', 'Neither error can be calculated', 'A has errors 1+0; B has 0+1; both total 1.', 'data_interpretation'),
    q('A fair test supports a claim once. Which conclusion is most careful?', 'It provides supporting evidence, with further testing still useful', 'It proves the claim under every possible condition', 'It makes measurement unnecessary', 'It eliminates every alternative explanation', 'One valid result supports a claim without establishing every possible case.'),
  ]],
]);
