const ccc = 'https://www.vatican.va/content/catechism/en/';
export default {
  slug: 'catholic',
  summary: 'Explore Catholic worship, Scripture, prayer and tradition through a fresh set of clues.',
  about: 'Explore Catholic worship, the sacraments, Scripture and familiar devotions. Each set focuses on a different part of Catholic life and tradition.\n\nChoose one answer each time, then see your topic profile at the checkpoint. Your final result includes an optional review of missed answers.\n\nPractices differ between Catholic rites. Questions specify the Roman Rite where relevant. This entertainment score does not measure anyone’s faith, devotion or standing in the Church.',
  sources: {
    sacraments: ccc + 'part_two/section_two.html',
    confirmation: ccc + 'part_two/section_two/chapter_one/article_2/iii_the_effects_of_confirmation.index.html',
    faith: 'https://press.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_en.html',
    prayer: ccc + 'part_four/section_two.html',
    rosary: 'https://www.vatican.va/special/rosary/documents/misteri_en.html',
    luminous: 'https://www.vatican.va/content/john-paul-ii/en/apost_letters/2002/documents/hf_jp-ii_apl_20021016_rosarium-virginis-mariae.html',
    mass: 'https://www.usccb.org/prayer-and-worship/the-mass/general-instruction-of-the-roman-missal/girm-chapter-2',
    church: 'https://www.usccb.org/prayer-and-worship/the-mass/general-instruction-of-the-roman-missal/girm-chapter-5',
    colours: 'https://www.usccb.org/prayer-and-worship/the-mass/general-instruction-of-the-roman-missal/girm-chapter-6',
    calendar: 'https://www.usccb.org/prayer-and-worship/liturgical-year-and-calendar',
    code: 'https://www.vatican.va/archive/cod-iuris-canonici/eng/documents/cic_lib2-cann368-430_en.html',
    parish: 'https://www.vatican.va/archive/cod-iuris-canonici/eng/documents/cic_lib2-cann515-552_en.html',
  },
  sourceUrl: reference => `https://bible.usccb.org/bible/${reference}`,
  rounds: [
    { title: 'Catholic Foundations', category: 'prayer_devotion', checkpoint: 'Your Catholic knowledge snapshot', feedback: 'Catholic foundations: {profile}. Explore the signs at the heart of worship.', teaser: 'Connect each sacrament with its meaning.', questions: [
      ['What is the central celebration of the Eucharist commonly called in the Roman Rite?', 'Mass', 'The Rosary', 'Vespers', 'A novena', 'mass', 'worship_sacraments'],
      ['How many sacraments does the Catholic Church recognise?', 'Seven', 'Five', 'Six', 'Twelve', 'sacraments', 'worship_sacraments'],
      ['The Pope is the bishop of which city?', 'Rome', 'Jerusalem', 'Bethlehem', 'Assisi', 'faith', 'church_leadership'],
      ['Which prayer is also called the Lord’s Prayer?', 'The Our Father', 'The Hail Mary', 'The Glory Be', 'The Angelus', 'prayer'],
      ['What is a creed?', 'A statement of belief', 'A book of parish accounts', 'A liturgical vessel', 'A type of vestment', 'faith'],
      ['In Catholic teaching, the Trinity is Father, Son and whom?', 'Holy Spirit', 'Saint Peter', 'Virgin Mary', 'Archangel Michael', 'faith'],
      ['Which book comes first in the Catholic Bible?', 'Genesis', 'Exodus', 'Psalms', 'Matthew', 'genesis/1', 'scripture'],
    ] },
    { title: 'The Sacraments', category: 'worship_sacraments', checkpoint: 'The sacraments connect', feedback: 'Sacraments: {profile}. Step inside the celebration.', teaser: 'Recognise the words and actions of the Roman Rite Mass.', questions: [
      ['Which sacrament uses water to mark entry into Christian life?', 'Baptism', 'Matrimony', 'Holy Orders', 'Anointing of the Sick', 'sacraments'],
      ['Which sacrament is also known as Penance or Confession?', 'Reconciliation', 'Confirmation', 'Matrimony', 'Holy Orders', 'sacraments'],
      ['Which sacrament concerns the marriage covenant?', 'Matrimony', 'Confirmation', 'Baptism', 'Anointing of the Sick', 'sacraments'],
      ['Which sacrament is associated with ordained ministry?', 'Holy Orders', 'Matrimony', 'Reconciliation', 'Baptism alone', 'sacraments'],
      ['Which sacrament is especially associated with strengthening baptismal grace?', 'Confirmation', 'Matrimony', 'Penance', 'Anointing of the Sick', 'confirmation'],
      ['Which sacrament is given for the spiritual support of the seriously ill?', 'Anointing of the Sick', 'Holy Orders', 'Matrimony', 'Confirmation', 'sacraments'],
      ['Which group consists of the sacraments of Christian initiation?', 'Baptism, Confirmation and Eucharist', 'Penance, Matrimony and Holy Orders', 'Eucharist, Matrimony and Penance', 'Confirmation, Holy Orders and Anointing', 'sacraments'],
    ] },
    { title: 'Inside the Mass', category: 'worship_sacraments', checkpoint: 'Worship comes into focus', feedback: 'The Mass: {profile}. Turn to the places and objects around it.', teaser: 'Can you name what you would find inside a church?', questions: [
      ['At a Roman Rite Mass, which part includes the Scripture readings?', 'Liturgy of the Word', 'Concluding Rites', 'Preparation of the Gifts only', 'Dismissal', 'mass'],
      ['What is the homily intended to explain?', 'Scripture and the mysteries of faith', 'Only the parish finances', 'Only the building’s history', 'The seating plan', 'mass'],
      ['Which profession of faith is normally recited on Sundays at Mass?', 'The Creed', 'The Angelus', 'The Litany of Saints', 'The Stations of the Cross', 'mass'],
      ['Which prayer begins with words meaning “Holy, holy, holy”?', 'The Sanctus', 'The Gloria', 'The Confiteor', 'The Kyrie', 'mass'],
      ['What does the phrase “Kyrie eleison” mean?', 'Lord, have mercy', 'Thanks be to God', 'Peace be with you', 'Lift up your hearts', 'mass'],
      ['In the Roman Rite, which prayer immediately introduces the Communion Rite?', 'The Lord’s Prayer', 'The Hail Mary', 'The Angelus', 'The Memorare', 'mass'],
      ['Which part of Mass sends the congregation out to live the faith?', 'The dismissal', 'The first reading', 'The preparation of gifts', 'The entrance chant', 'mass'],
    ] },
    { title: 'Inside the Church', category: 'worship_sacraments', checkpoint: 'The details stand out', feedback: 'Church spaces: {profile}. Next, follow the calendar.', teaser: 'Match the seasons with their celebrations.', questions: [
      ['From which raised place are readings proclaimed at a Roman Rite Mass?', 'The ambo', 'The font', 'The tabernacle', 'The sacristy cupboard', 'church'],
      ['What is the table used for the Eucharistic celebration called?', 'The altar', 'The pew', 'The lectern shelf', 'The choir stall', 'church'],
      ['Where is the consecrated Eucharist reserved?', 'The tabernacle', 'The baptismal font', 'The ambo', 'The collection box', 'church'],
      ['What does the sanctuary lamp near the tabernacle indicate?', 'The presence of the reserved Eucharist', 'That a wedding is planned', 'That the church is closed', 'That a sermon is about to begin', 'church'],
      ['What is the cup used for the Eucharistic wine called?', 'Chalice', 'Thurible', 'Monstrance', 'Crosier', 'colours'],
      ['Which garment is normally the priest’s outer vestment at a Roman Rite Mass?', 'Chasuble', 'Mitre', 'Cope', 'Cassock', 'colours'],
      ['Which colour is normally used for Ordinary Time in the Roman Rite?', 'Green', 'Violet', 'Red', 'Rose', 'colours'],
    ] },
    { title: 'Seasons and Celebrations', category: 'liturgical_year', checkpoint: 'The year takes shape', feedback: 'Liturgical seasons: {profile}. Follow the calendar into prayer.', teaser: 'Look closely at familiar Catholic devotions.', questions: [
      ['Which Roman Rite season prepares for Christmas?', 'Advent', 'Lent', 'Easter Time', 'Ordinary Time after Easter', 'calendar'],
      ['Which event does Christmas celebrate?', 'The birth of Jesus', 'The Ascension', 'The Transfiguration', 'The descent of the Holy Spirit', 'luke/2'],
      ['Which day begins Lent in the Roman Rite?', 'Ash Wednesday', 'Palm Sunday', 'Holy Thursday', 'Good Friday', 'calendar'],
      ['What does Easter Sunday celebrate?', 'The Resurrection of Jesus', 'The Nativity of Mary', 'The calling of Peter', 'The baptism of Jesus', 'john/20'],
      ['Which event is remembered on Palm Sunday?', 'Jesus’ entry into Jerusalem', 'Jesus’ birth in Bethlehem', 'The wedding at Cana', 'The flight into Egypt', 'matthew/21'],
      ['What does the Ascension celebrate?', 'Jesus being taken up into heaven', 'Mary visiting Elizabeth', 'Moses receiving the Law', 'Peter leaving his fishing boat', 'acts/1'],
      ['Which event is associated with Pentecost?', 'The descent of the Holy Spirit', 'The birth of John the Baptist', 'The Last Supper', 'The Annunciation', 'acts/2'],
    ] },
    { title: 'Prayer and the Rosary', category: 'prayer_devotion', checkpoint: 'Prayer in focus', feedback: 'Prayer and devotion: {profile}. Meet the people behind the prayers.', teaser: 'Follow Mary and the Gospel stories.', questions: [
      ['How many Hail Marys form one decade of the Rosary?', 'Ten', 'Seven', 'Twelve', 'Fifteen', 'luminous'],
      ['Which pope proposed the Luminous Mysteries in 2002?', 'John Paul II', 'John XXIII', 'Paul VI', 'Benedict XVI', 'luminous'],
      ['Which set of Rosary mysteries includes the Nativity?', 'Joyful', 'Sorrowful', 'Glorious', 'Luminous', 'rosary'],
      ['Which set of mysteries includes the Crucifixion?', 'Sorrowful', 'Joyful', 'Luminous', 'Glorious', 'rosary'],
      ['Which set of mysteries includes the Resurrection?', 'Glorious', 'Joyful', 'Sorrowful', 'Luminous', 'rosary'],
      ['Which set of mysteries includes the Transfiguration?', 'Luminous', 'Sorrowful', 'Joyful', 'Glorious', 'rosary'],
      ['In Catholic prayer, what is intercession?', 'Praying on behalf of others', 'Reading only in silence', 'Naming a church building', 'Preparing a liturgical calendar', 'faith'],
    ] },
    { title: 'Mary and the Gospels', category: 'scripture', checkpoint: 'The Gospel links emerge', feedback: 'Mary and the Gospels: {profile}. Explore how Scripture fits together.', teaser: 'Connect books, writers and key biblical moments.', questions: [
      ['Which angel brings the Annunciation to Mary?', 'Gabriel', 'Michael', 'Raphael', 'Uriel', 'luke/1'],
      ['Whom does Mary visit after the Annunciation?', 'Elizabeth', 'Martha', 'Mary Magdalene', 'Anna', 'luke/1'],
      ['Whose song of praise is known as the Magnificat?', 'Mary’s', 'Peter’s', 'Paul’s', 'Thomas’s', 'luke/1'],
      ['At which wedding does Mary tell the servants to follow Jesus’ instructions?', 'Cana', 'Bethany', 'Jericho', 'Emmaus', 'john/2'],
      ['Who is the earthly spouse of Mary?', 'Joseph', 'Zechariah', 'Simeon', 'Cleopas', 'matthew/1'],
      ['Who baptises Jesus?', 'John the Baptist', 'Peter', 'Andrew', 'James', 'mark/1'],
      ['Which two figures appear with Jesus at the Transfiguration?', 'Moses and Elijah', 'Abraham and Isaac', 'David and Solomon', 'Peter and Paul', 'matthew/17'],
    ] },
    { title: 'Scripture Connections', category: 'scripture', checkpoint: 'Scripture takes shape', feedback: 'Scripture: {profile}. See how Church communities are organised.', teaser: 'Match the roles with the responsibilities.', questions: [
      ['Which names belong to the four Gospel writers?', 'Matthew, Mark, Luke and John', 'Peter, Paul, James and Jude', 'Moses, David, Isaiah and Jeremiah', 'Luke, Acts, Romans and James', 'faith'],
      ['Which book follows the Gospels in the New Testament?', 'Acts of the Apostles', 'Genesis', 'Psalms', 'Revelation', 'acts/0'],
      ['Which apostle writes to the Christians in Rome?', 'Paul', 'Andrew', 'Thomas', 'Philip', 'romans/1'],
      ['Which book contains many of the Bible’s prayers and songs?', 'Psalms', 'Numbers', 'Judges', 'Acts', 'psalms/0'],
      ['Which apostle is given the keys of the kingdom in Matthew 16?', 'Peter', 'James', 'John', 'Thomas', 'matthew/16'],
      ['In John 6, what does Jesus call himself?', 'The bread of life', 'The tower of Babel', 'The king of Egypt', 'The stone tablets', 'john/6'],
      ['Who recognises the risen Jesus by saying “My Lord and my God”?', 'Thomas', 'Judas Iscariot', 'Pilate', 'Herod', 'john/20'],
    ] },
    { title: 'Church Life', category: 'church_leadership', checkpoint: 'The roles connect', feedback: 'Church life: {profile}. Bring the wider picture together.', teaser: 'A mix of belief, worship and tradition awaits.', questions: [
      ['What is a diocese ordinarily entrusted to a bishop called?', 'A local Church community', 'A single prayer service', 'A collection of hymns', 'A religious medal', 'code'],
      ['Who ordinarily leads a diocese?', 'A bishop', 'A sacristan', 'A choir director', 'A parish secretary', 'code'],
      ['What is a parish?', 'A stable local community within a diocese', 'A type of chalice', 'A set of Rosary beads', 'A season before Easter', 'parish'],
      ['Which ordained minister is normally entrusted with a parish’s pastoral care?', 'A priest', 'A reader', 'A choir director', 'A catechist without ordination', 'parish'],
      ['Which ministry is one of the three degrees of Holy Orders?', 'Deacon', 'Sacristan', 'Organist', 'Reader', 'faith'],
      ['What does apostolic succession refer to?', 'Bishops succeeding the apostles in their ministry', 'The order of readings in a service', 'The order of churches along a pilgrimage', 'The sequence of hymns during Mass', 'faith'],
      ['Which title refers to the bishop’s principal church, containing his chair?', 'Cathedral', 'Convent', 'Hermitage', 'Seminary', 'church'],
    ] },
    { title: 'Faith and Tradition', category: 'prayer_devotion', checkpoint: 'Your Catholic result is ready', questions: [
      ['Which theological virtue joins faith and hope?', 'Charity', 'Prudence', 'Fortitude', 'Temperance', 'faith'],
      ['Which term means a journey made for a religious purpose?', 'Pilgrimage', 'Ordination', 'Absolution', 'Confirmation', 'faith'],
      ['Which event is remembered at the institution of the Eucharist?', 'The Last Supper', 'The flight into Egypt', 'The finding in the Temple', 'The Visitation', 'luke/22', 'worship_sacraments'],
      ['Which pair of sacraments is described as the sacraments of healing?', 'Penance and Anointing of the Sick', 'Baptism and Matrimony', 'Confirmation and Holy Orders', 'Eucharist and Matrimony', 'sacraments', 'worship_sacraments'],
      ['In Catholic teaching, what does the Assumption concern?', 'Mary being taken into heavenly glory', 'Jesus being born in Bethlehem', 'Peter receiving the keys', 'Moses receiving the Law', 'rosary'],
      ['Which Gospel scene is linked to the first Joyful Mystery?', 'The Annunciation', 'The Crucifixion', 'The Ascension', 'The Transfiguration', 'rosary'],
      ['Which of these is a Luminous Mystery of the Rosary?', 'The baptism of Jesus in the Jordan', 'The birth of Jesus', 'The carrying of the cross', 'The coronation of Mary', 'rosary'],
    ] },
  ],
};
