export default {
  slug: 'chef',
  summary: 'Test your kitchen instincts with tools, ingredients, cooking methods and practical decisions.',
  about: 'Move from familiar kitchen tools to ingredients, baking, recipe calculations and practical cooking decisions. Each set tests a different part of kitchen knowledge.\n\nChoose one answer, see your topic profile at the checkpoint and continue to a fresh challenge. Reveal your overall score and optionally review missed answers at the end.\n\nMeasurements state their units explicitly. Food-safety questions use broad principles rather than country-specific rules. Your result describes this quiz attempt and is not a practical cooking assessment.',
  sources: {
    methods: 'https://www.ciafoodies.com/the-essential-cooking-techniques/',
    pastry: 'https://www.kingarthurbaking.com/learn/guides/pie-crust',
    butter: 'https://www.kingarthurbaking.com/blog/2020/08/31/why-does-butter-temperature-matter-in-pastry',
    yeast: 'https://www.kingarthurbaking.com/learn/bread',
    safety: 'https://www.who.int/activities/promoting-safe-food-handling/five-key-to-safer-food',
    crosscontact: 'https://www.foodallergy.org/resources/avoiding-cross-contact',
  },
  rounds: [
    { title: 'Kitchen Tools', category: 'kitchen_fundamentals', checkpoint: 'Your kitchen snapshot', feedback: 'Kitchen tools: {profile}. Take your skills to the prep bench.', teaser: 'Small preparation choices make a big difference.', questions: [
      ['Which tool is designed to grip and turn hot pieces of food?', 'Tongs', 'Whisk', 'Ladle', 'Peeler'],
      ['Which tool is best suited to beating air into cream by hand?', 'Whisk', 'Colander', 'Rolling pin', 'Ladle'],
      ['Which tool drains water from cooked pasta?', 'Colander', 'Measuring jug', 'Mixing bowl', 'Funnel'],
      ['Which tool removes a thin layer of skin from a carrot?', 'Peeler', 'Whisk', 'Ladle', 'Pastry brush'],
      ['Which tool is used to roll dough into a flat sheet?', 'Rolling pin', 'Potato masher', 'Colander', 'Zester'],
      ['Which tool measures the mass of flour most directly?', 'Kitchen scale', 'Timer', 'Measuring jug alone', 'Thermometer'],
      ['Which tool is designed to lift and serve soup?', 'Ladle', 'Slotted turner', 'Tongs', 'Pastry scraper'],
    ] },
    { title: 'The Prep Bench', category: 'kitchen_fundamentals', checkpoint: 'Prep decisions made', feedback: 'Preparation: {profile}. Now turn up the heat.', teaser: 'Match the cooking method to the result.', questions: [
      ['A recipe is ready. What makes the cooking steps easier to follow?', 'Measure and arrange ingredients first', 'Mix every ingredient together first', 'Skip the timings until the end', 'Heat every pan before reading'],
      ['Why cut vegetables into similar-sized pieces for the same pan?', 'They cook at a more similar rate', 'They all develop the same taste', 'They no longer need seasoning', 'They stop releasing moisture', 'methods'],
      ['What does it mean to zest a lemon?', 'Remove the thin outer coloured layer', 'Remove only the seeds', 'Squeeze out all the juice', 'Cut the whole lemon into slices'],
      ['Which preparation gives garlic a finer texture?', 'Mincing it', 'Leaving the cloves whole', 'Cutting it in half', 'Separating the bulb only'],
      ['Why dry washed leaves before dressing a salad?', 'So excess water does not dilute the dressing', 'So the leaves become sweeter', 'So the dressing turns solid', 'So the leaves need no washing next time'],
      ['A recipe needs sliced onion first and fresh herbs last. How should they be prepared?', 'Keep them separate for their different timings', 'Mix them together and add both first', 'Cook the herbs before slicing the onion', 'Add both only after cooking'],
      ['What does “fold in” usually ask you to do?', 'Combine gently to retain air', 'Beat at maximum speed', 'Press firmly until dense', 'Knead until elastic'],
    ] },
    { title: 'Heat and Methods', category: 'heat_methods', checkpoint: 'Heat under control', feedback: 'Cooking methods: {profile}. Follow your taste buds next.', teaser: 'Spot the ingredient that changes the balance.', questions: [
      ['Which method cooks food in water vapour above hot water?', 'Steaming', 'Roasting', 'Grilling', 'Shallow-frying', 'methods'],
      ['Which method surrounds food with hot, dry oven air?', 'Roasting', 'Poaching', 'Steaming', 'Boiling', 'methods'],
      ['Which method uses gentle liquid heat below a vigorous boil?', 'Poaching', 'Deep-frying', 'Roasting', 'Searing', 'methods'],
      ['Which surface best describes a gentle simmer?', 'Small bubbles rise occasionally', 'Large bubbles break violently everywhere', 'The liquid is completely frozen', 'The liquid has evaporated entirely', 'methods'],
      ['A crowded pan of vegetables becomes wet instead of browning. Why?', 'Released moisture is trapped and steaming the food', 'Crowding removes water instantly', 'The vegetables have become oil', 'The pan is producing extra salt', 'methods'],
      ['Braising usually combines browning with which next step?', 'Gentle cooking with some liquid in a covered pot', 'Freezing without liquid', 'Whisking over an ice bath', 'Drying without heat', 'methods'],
      ['Why can a rolling boil damage delicate pieces of fish?', 'Strong movement can break them apart', 'It turns the bones into steam', 'It removes all the protein', 'It makes water stop transferring heat', 'methods'],
    ] },
    { title: 'Taste and Balance', category: 'ingredients_flavour', checkpoint: 'Your taste instincts', feedback: 'Taste and balance: {profile}. Turn those ideas into sauces.', teaser: 'Emulsions, thickness and texture are on the menu.', questions: [
      ['A rich sauce tastes heavy. Which small addition can add acidity?', 'Lemon juice', 'Unsalted butter', 'Cream', 'More oil'],
      ['Which ingredient is strongly associated with savoury umami taste?', 'Mushrooms', 'Granulated sugar', 'Lemon juice', 'Plain water'],
      ['Which ingredient usually adds sweetness?', 'Honey', 'Vinegar', 'Salt', 'Lemon zest alone'],
      ['A sauce is too salty. Which addition can dilute the salt concentration?', 'Unsalted stock', 'More salt', 'Soy sauce', 'Salted butter'],
      ['Why are delicate fresh herbs often added near the end of cooking?', 'To retain more of their fresh aroma', 'To make them absorb all the salt', 'To stop the dish containing water', 'To turn them into a thickener'],
      ['Which ingredient contributes acidity to a basic vinaigrette?', 'Vinegar', 'Oil', 'Sugar', 'Butter'],
      ['Which tasting approach best controls seasoning?', 'Add a little, mix, then taste again', 'Add the full salt supply at once', 'Season only by the colour of the pan', 'Taste only before any ingredients are mixed'],
    ] },
    { title: 'Sauces and Texture', category: 'heat_methods', checkpoint: 'The texture test', feedback: 'Sauces and texture: {profile}. The baking bench is ready.', teaser: 'Discover what helps dough rise and pastry stay light.', questions: [
      ['What happens when a sauce is reduced by simmering?', 'Water evaporates and flavours become more concentrated', 'More water enters the pan', 'All seasoning disappears', 'The sauce becomes raw'],
      ['What is an emulsion in cooking?', 'One liquid dispersed as droplets in another', 'A dry mixture of whole spices', 'A layer of ice on a sauce', 'A cut of meat'],
      ['Which pair of liquids forms the basis of a simple vinaigrette?', 'Oil and vinegar', 'Water and milk', 'Stock and water', 'Juice and water'],
      ['What is a roux usually made from?', 'Fat and flour cooked together', 'Oil and vinegar whisked cold', 'Sugar and water frozen', 'Salt and pepper toasted'],
      ['Why mix starch with a little cold liquid before adding it to a hot sauce?', 'To help disperse it and reduce lumps', 'To remove its thickening ability', 'To make the sauce freeze', 'To turn starch into oil'],
      ['What does deglazing a pan help collect?', 'The browned bits stuck to the pan', 'Only the steam above the pan', 'The raw flour still in its bag', 'The moisture inside a closed jar'],
      ['A sauce needs a smooth finish without solid pieces. Which method fits?', 'Pass it through a fine sieve', 'Add more chopped vegetables', 'Freeze it in large blocks', 'Leave the pieces unstrained'],
    ] },
    { title: 'The Baking Bench', category: 'baking_pastry', checkpoint: 'Baking clues solved', feedback: 'Baking: {profile}. Put the recipe numbers to work.', teaser: 'Scale portions using the quantities given.', questions: [
      ['Which ingredient produces gas as it ferments in bread dough?', 'Yeast', 'Salt', 'Butter', 'Water alone', 'yeast'],
      ['Why can mixing wheat-flour muffin batter too much make it tough?', 'More gluten structure develops', 'All the flour disappears', 'The sugar becomes salt', 'The oven temperature drops', 'pastry'],
      ['Why keep pieces of butter cold when making flaky pastry?', 'They help create separate layers during baking', 'They dissolve all the flour immediately', 'They stop any steam forming', 'They remove all moisture', 'butter'],
      ['Which ingredient helps an egg custard set as it heats?', 'Eggs', 'Water', 'Vanilla extract', 'Salt'],
      ['What does kneading wheat bread dough mainly help develop?', 'A gluten network', 'Ice crystals', 'A caramel coating', 'A layer of burnt sugar', 'yeast'],
      ['What is blind baking?', 'Baking a pastry case before adding its filling', 'Baking without measuring ingredients', 'Baking only with steam', 'Freezing dough before serving it', 'pastry'],
      ['A bread dough grows during its warm resting period. What is happening?', 'Fermentation produces gas', 'The flour is turning into salt', 'The bowl is creating extra dough', 'The water has become solid', 'yeast'],
    ] },
    { title: 'Recipe Numbers', category: 'kitchen_maths', checkpoint: 'The quantities add up', feedback: 'Recipe calculations: {profile}. A good kitchen needs good habits too.', teaser: 'Spot the choices that protect the food.', questions: [
      ['A recipe uses 300 g of rice for 4 portions. How much for 10 equal portions?', '750 g', '600 g', '900 g', '1,200 g'],
      ['You need 3 portions of 175 g each. What is the total mass?', '525 g', '350 g', '475 g', '575 g'],
      ['Divide 1.5 L equally between 3 containers. How much goes in each?', '500 mL', '250 mL', '450 mL', '750 mL'],
      ['Flour and sugar are mixed in a 2:1 ratio by mass. For 600 g flour, how much sugar?', '300 g', '200 g', '600 g', '1,200 g'],
      ['A recipe needs 240 g of butter. You are making half. How much is needed?', '120 g', '60 g', '180 g', '480 g'],
      ['A dish goes into the oven at 14:10 for 25 minutes. When is that time up?', '14:35', '14:25', '14:45', '15:10'],
      ['You have 2 kg of dough. Each portion uses 125 g. How many full portions?', '16', '8', '12', '20'],
    ] },
    { title: 'Kitchen Safety', category: 'safety_service', checkpoint: 'Good habits count', feedback: 'Kitchen safety: {profile}. Bring timing into the picture.', teaser: 'Keep the kitchen moving with a clear sequence.', questions: [
      ['Raw chicken and ready-to-eat salad need preparation. Which setup reduces contamination?', 'Separate clean equipment for the salad', 'The same unwashed board for both', 'A shared cloth to wipe both foods', 'The raw chicken placed over the salad', 'safety'],
      ['What should happen before preparing food after handling waste?', 'Wash hands appropriately', 'Wipe hands on clothing', 'Only rinse the food', 'Continue if the waste looked clean', 'safety'],
      ['Why keep raw and cooked foods separate?', 'To reduce transfer of harmful microorganisms', 'To make all food taste the same', 'To prevent cooked food losing its colour', 'To avoid measuring portions', 'safety'],
      ['Which water should be used to wash produce eaten raw?', 'Water that is safe to drink', 'Water from an unknown source', 'Water used to rinse raw meat', 'Any water if it looks clear', 'safety'],
      ['Which tool measures a food’s internal temperature?', 'A suitable food thermometer', 'A kitchen timer', 'A weighing scale', 'A measuring spoon', 'safety'],
      ['A guest reports a food allergy. What is the best general approach?', 'Check ingredients and prevent allergen cross-contact', 'Remove only visible pieces after cooking', 'Assume heat removes every allergen', 'Guess from the dish’s name', 'crosscontact'],
      ['Why can a used utensil transfer an allergen into another dish?', 'Small residues can remain on it', 'Allergens only spread through air', 'Metal creates new allergens', 'Allergens disappear when food is mixed', 'crosscontact'],
    ] },
    { title: 'Timing and Service', category: 'kitchen_fundamentals', checkpoint: 'The kitchen comes together', feedback: 'Timing and service: {profile}. Use the clues in a final mix.', teaser: 'Combine technique, timing and recipe logic.', questions: [
      ['One component takes 20 minutes and another takes 5. To finish together, start which first?', 'The 20-minute component', 'The 5-minute component', 'Both only after 20 minutes', 'Neither until the other is ready'],
      ['A recipe says to rest dough for 30 minutes before rolling. What belongs in the plan?', 'The resting time as well as active preparation', 'Only the time spent rolling', 'Only the oven heating time', 'No time for the rest'],
      ['A sauce must simmer while vegetables roast. What helps avoid missing either task?', 'Separate labelled timers', 'One timer with no task label', 'Guessing from the room temperature', 'Checking only the vegetables'],
      ['Six plates need two identical pieces each. How many pieces should be ready?', '12', '6', '8', '14'],
      ['A recipe lists onions before garlic in the pan. Which approach follows it?', 'Add the onions first, then the garlic at the stated step', 'Add the garlic only after serving', 'Reverse the order without checking', 'Mix them into the dessert'],
      ['A dish needs a crisp topping at service. When is the topping best added?', 'Close to serving so it stays crisp', 'Before a long soak in the sauce', 'While the ingredients are being washed', 'Before the sauce is made'],
      ['A plate looks unfinished. What is the purpose of a suitable edible garnish?', 'Support the dish’s appearance and taste', 'Hide an uncorrected safety problem', 'Replace all seasoning automatically', 'Make every portion heavier than planned'],
    ] },
    { title: 'Kitchen Decisions', category: 'heat_methods', checkpoint: 'Your chef result is ready', questions: [
      ['Vegetables need browning but steam in a crowded pan. Which change addresses the cause?', 'Cook in smaller batches', 'Pack in more vegetables', 'Add more water and cover tightly', 'Reduce the space between pieces', 'methods'],
      ['A reduced sauce is too strong and thick. What can help restore balance?', 'Add a little suitable unsalted liquid and taste', 'Reduce it much further', 'Add salt without tasting', 'Discard only the spoon'],
      ['A recipe for 12 equal portions uses 1,800 g of an ingredient. How much for 18?', '2,700 g', '2,100 g', '2,400 g', '3,600 g', undefined, 'kitchen_maths'],
      ['A pastry recipe requires 200 g flour and 100 g butter. You used 200 g of each. What changed?', 'The butter-to-flour ratio doubled', 'The flour-to-butter ratio doubled', 'Both amounts halved', 'The ratio stayed the same', undefined, 'baking_pastry'],
      ['A soup is boiling hard and losing liquid too quickly. What addresses both issues?', 'Lower the heat to a gentle simmer', 'Raise the heat further', 'Use a wider pan on maximum heat', 'Continue until the pan is dry', 'methods'],
      ['One task takes 12 minutes and must finish before a 6-minute task starts. What is the minimum total?', '18 minutes', '6 minutes', '12 minutes', '24 minutes', undefined, 'kitchen_maths'],
      ['An oil-and-vinegar dressing separates after standing. What best explains it?', 'The liquids are not held in a stable emulsion', 'The vinegar has become solid salt', 'The oil has turned into water', 'The bowl has removed all the acidity'],
    ] },
  ],
};
