import {q, universityPack} from './university-shared.mjs';
export default universityPack('harvard', 'Read the evidence, compare the numbers and make decisions that stand up to scrutiny.', [
  ['Read the Situation', 'analytical_reasoning', 'Your first case snapshot', 'A small calculation can change the best choice.', [
    q('Every approved proposal has a budget. This proposal is approved. What must it have?', 'A budget', 'A profit', 'A new building', 'Exactly two authors', 'The proposal meets the stated condition for every approved proposal.'),
    q('A meeting needs both a room and a speaker. The room is confirmed, but no speaker is confirmed. What is true?', 'One requirement remains unconfirmed', 'The meeting has already happened', 'Both requirements are confirmed', 'A speaker is unnecessary', 'Only the room requirement is confirmed.'),
    q('A rule says a permit is required to enter. Lee has a permit. What does that tell us?', 'Lee meets the permit requirement', 'Lee has already entered', 'Everyone has a permit', 'Lee owns the building', 'Possessing a permit meets a condition; it does not prove entry occurred.'),
    q('All urgent messages are flagged. This message is not flagged. Under the rule, what follows?', 'It is not urgent', 'It has been read', 'It was sent yesterday', 'It must be urgent', 'An urgent message would have a flag; the flag is absent.'),
    q('Three reports are due in order: A before B, and B before C. Which must come first?', 'A', 'B', 'C', 'B and C together', 'The conditions require A, then B, then C.'),
    q('A team can choose exactly one location: north, south or east. North and east are unavailable. Which remains?', 'South', 'North', 'East', 'None', 'South is the only location not excluded.'),
    q('A label says “at least 12 seats”. Which seat count would break that description?', '11', '12', '15', '20', 'At least 12 includes 12 and every larger count, but not 11.'),
  ]],
  ['Numbers in Practice', 'quantitative_reasoning', 'The quantities connect', 'A convincing story still needs the right evidence.', [
    q('A team completes 24 tasks in 6 hours at a constant rate. How many tasks per hour?', '4', '3', '6', '8', '24 ÷ 6 = 4.'),
    q('A project has 200 credits. It spends 35% of them. How many credits remain?', '130', '70', '165', '135', '200 × 0.65 = 130.'),
    q('Three equal payments total 84 credits. What is one payment?', '28 credits', '21 credits', '24 credits', '42 credits', '84 ÷ 3 = 28.'),
    q('A price rises from 50 credits to 60 credits. What is the percentage increase?', '20%', '10%', '16%', '25%', 'The increase of 10 is 20% of the original 50.'),
    q('A plan costs 8 credits per week plus a one-time fee of 12 credits. What is the total for 4 weeks?', '44 credits', '32 credits', '48 credits', '80 credits', '4 × 8 + 12 = 44.'),
    q('Six identical machines finish a job in 4 hours. With equal constant rates, how long would three machines take?', '8 hours', '2 hours', '6 hours', '12 hours', 'The job takes 24 machine-hours; 24 ÷ 3 = 8.'),
    q('A bag has 18 blue and 12 red tokens. What fraction of all tokens is red?', '2/5', '3/5', '1/3', '2/3', '12 out of 30 simplifies to 2/5.'),
  ]],
  ['Test the Evidence', 'evidence_judgement', 'The evidence has a shape', 'The wording can be as important as the numbers.', [
    q('Sales rose after a new sign appeared. What does that fact alone establish?', 'The rise followed the sign change', 'The sign caused the entire rise', 'Every customer saw the sign', 'Sales will keep rising', 'The timing is observed; causation and future outcomes are not established.'),
    q('A survey asks only people leaving a cinema whether they enjoy films. What is its main limit?', 'The sample may overrepresent film fans', 'The answers must all be false', 'Films cannot be studied', 'The sample includes everyone', 'People at a cinema are not a representative sample of the whole population.'),
    q('Which observation disproves “Every delivery arrived before noon”?', 'One delivery arrived at 13:00', 'Most arrived at 10:00', 'Two arrived at 09:00', 'One arrived at 11:59', 'A single arrival after noon is a counterexample.'),
    q('Two teams try different tools but also receive different training. Why is comparison difficult?', 'Training could also affect the outcome', 'Tools never affect outcomes', 'The larger team must win', 'Both tools must be identical', 'The tool and training differences are competing explanations.'),
    q('Which best tests whether a new queue system reduces waiting time?', 'Compare waiting times in similar conditions with and without it', 'Ask its designer if it looks good', 'Count the letters in its name', 'Measure the entrance width only', 'A comparable outcome measurement addresses the actual claim.'),
    q('A report names its source, date and sample size. What does this primarily help a reader do?', 'Check how the claim was produced', 'Prove every claim is true', 'Ignore the original data', 'Guarantee the sample is unbiased', 'Transparency supports scrutiny but does not guarantee accuracy.'),
    q('A claim rests on one customer review. What would most strengthen a broad conclusion about customers?', 'A larger representative sample', 'The same review in a larger font', 'Removing the review date', 'Repeating the claim twice', 'A representative sample gives stronger evidence about a population.'),
  ]],
  ['Words That Matter', 'verbal_reasoning', 'The wording is clearer', 'Now look at what the figures actually show.', [
    q('A report calls a result “tentative”. How should it be treated?', 'As provisional', 'As impossible', 'As permanent', 'As unanimous', 'Tentative means not yet final or certain.'),
    q('Which wording is most precise?', 'Attendance rose from 40 to 52', 'Attendance was quite good', 'Attendance changed somehow', 'Attendance felt different', 'The stated counts specify both the starting and ending values.'),
    q('A proposal is “feasible” if it is…', 'Practical to carry out', 'Certain to be popular', 'Already complete', 'Free of all costs', 'Feasible refers to practical possibility, not popularity or zero cost.'),
    q('“Some proposals were accepted.” What is guaranteed?', 'At least one proposal was accepted', 'Every proposal was accepted', 'Exactly half were accepted', 'No proposal was accepted', 'Some establishes at least one, without specifying a total.'),
    q('Which sentence states a cause rather than just a sequence?', 'The training caused the improvement', 'Training began in May', 'Scores rose after May', 'Training ended before June', 'Only the first sentence explicitly claims causation.'),
    q('A decision is “reversible”. What does that mean?', 'It can be undone', 'It cannot be explained', 'It must be repeated', 'It is always correct', 'Reversible means capable of being reversed.'),
    q('Which is the clearest summary of “The cheaper plan saves money but takes longer”?', 'It trades lower cost for more time', 'It is cheaper and faster', 'It costs more but is faster', 'Both plans take the same time', 'The sentence explicitly presents a cost-versus-time trade-off.'),
  ]],
  ['Read the Data', 'data_interpretation', 'The data tells its story', 'Which choice fits the goal that was actually set?', [
    q('Weekly visitors are 20, 30 and 40. What is the mean?', '30', '20', '35', '90', '(20 + 30 + 40) ÷ 3 = 30.'),
    q('Team A completes 18 of 20 tasks; Team B completes 24 of 30. Which has the higher completion rate?', 'Team A', 'Team B', 'They are equal', 'The rates cannot be compared', 'A completes 90%; B completes 80%.'),
    q('A chart shows 45 visits on Monday and 60 on Tuesday. How many more visits were on Tuesday?', '15', '25', '45', '105', '60 − 45 = 15.'),
    q('A group has 80 members. Of them, 60 answered a survey. What percentage responded?', '75%', '60%', '80%', '25%', '60 ÷ 80 × 100 = 75%.'),
    q('The values are 2, 3, 3, 4 and 18. What is the median?', '3', '4', '6', '18', 'The middle value in the sorted list is 3.'),
    q('A result says “40 of 50 respondents agreed”. Which statement adds an unsupported claim?', '80% of all residents agree', '40 respondents agreed', '10 respondents did not agree', '80% of respondents agreed', 'The respondents are not established as representing all residents.'),
    q('A rate changes from 10% to 15%. What is the increase in percentage points?', '5', '15', '50', '150', '15 − 10 = 5 percentage points; the relative increase is 50%.'),
  ]],
  ['Choose the Priority', 'decision_making', 'Your decision profile', 'A few rules can narrow the options sharply.', [
    q('Choose the cheapest plan that finishes within 3 days. A costs 40 and takes 4 days; B costs 60 and takes 3; C costs 80 and takes 2. Which wins?', 'B', 'A', 'C', 'All are equally suitable', 'A misses the deadline; B is the cheaper of the two valid options.'),
    q('A task must be finished before any others can begin. What makes it a priority?', 'It blocks the remaining tasks', 'Its name comes first alphabetically', 'It uses the most colours', 'It is the newest task', 'Its dependency prevents all subsequent work until completion.'),
    q('A team wants fewer errors. Which measure most directly tracks that goal?', 'Errors per completed task', 'Number of meetings', 'Desk size', 'Length of the project name', 'An error rate directly measures the stated outcome.'),
    q('Only one option is affordable and meets every required feature. Which is justified by those rules?', 'Choose that option', 'Choose the most expensive option', 'Ignore the required features', 'Choose an option over budget', 'It is the sole option satisfying the stated constraints.'),
    q('You can run a small reversible trial before a costly uncertain decision. What is the main benefit?', 'Learning before committing fully', 'Guaranteeing success', 'Removing every future cost', 'Proving no risks exist', 'The trial provides information while limiting commitment.'),
    q('Two plans give the same stated benefit. A costs 30 credits; B costs 45. If cost is the only other criterion, which is better?', 'A', 'B', 'Neither can be compared', 'The more expensive one by definition', 'Equal benefit and lower cost favour A under the stated criterion.'),
    q('A decision depends on whether demand exceeds 100 units. Which missing fact matters most?', 'The expected demand', 'The office wall colour', 'The plan’s font', 'The author’s favourite meal', 'Demand determines whether the decision condition is met.'),
  ]],
  ['Work Within the Rules', 'analytical_reasoning', 'The options narrow', 'Every attractive option gives something up.', [
    q('A pass requires both a photo and a signature. Jo supplies a photo only. What is true?', 'The requirements are not yet met', 'The pass must be issued', 'A signature is optional', 'Jo supplied neither item', 'Both items are required; one is missing.'),
    q('Choose two different projects costing at most 10 credits together. A costs 7, B costs 4 and C costs 3. Which pair works?', 'A and C, or B and C', 'Only A and B', 'Every pair', 'No pair', 'A+C=10 and B+C=7; A+B=11 is over budget.'),
    q('A workshop holds no more than 18 people. Four groups of 5 arrive. How many people exceed capacity?', '2', '3', '5', '7', '4 × 5 − 18 = 2.'),
    q('X must happen after Y and before Z. Which order satisfies both rules?', 'Y, X, Z', 'X, Y, Z', 'Y, Z, X', 'Z, X, Y', 'Y precedes X, and X precedes Z.'),
    q('A room is available only after 14:00. Which start time is allowed?', '14:30', '13:30', '12:00', '09:00', 'Only 14:30 is later than 14:00.'),
    q('Exactly one of two switches must be on. Switch A is on. What must be true of B?', 'It is off', 'It is on', 'It has been removed', 'It is broken', 'Exactly one on excludes B being on when A is on.'),
    q('A rule requires a score of at least 75. Which pair both meet it?', '75 and 81', '74 and 81', '73 and 74', '70 and 75', 'Both 75 and 81 are at or above the threshold.'),
  ]],
  ['Compare the Trade-offs', 'decision_making', 'The trade-offs are visible', 'Put the numbers and the evidence together.', [
    q('You spend an hour on Plan A instead of Plan B. What is the opportunity cost?', 'The benefit you give up from Plan B', 'Every past expense', 'The cost of both plans combined', 'A guaranteed financial loss', 'Opportunity cost is the value of the best alternative forgone.'),
    q('A route takes 20 minutes and costs 8 credits; another takes 35 minutes and costs 3. What does the first route buy?', '15 minutes saved for 5 extra credits', '5 minutes saved for 15 credits', '15 minutes saved at no extra cost', 'More time and a lower cost', '35−20=15 minutes; 8−3=5 credits.'),
    q('A team has already paid a non-refundable fee. What should guide whether to continue now?', 'The future benefits and future costs', 'Only the money already lost', 'The original name of the plan', 'The fee alone, regardless of outcomes', 'A sunk payment cannot change; the current choice concerns future consequences.'),
    q('Plan A is faster; Plan B is cheaper. Neither goal is ranked. What is needed to choose between them?', 'The relative importance of time and cost', 'The number of letters in each name', 'Proof that both are identical', 'A guarantee that speed never matters', 'The criteria conflict, so priorities are needed.'),
    q('A backup costs 5 credits and prevents a stated 50-credit loss if a failure occurs. What extra fact is needed to compare expected costs?', 'The probability of failure', 'The colour of the backup', 'The day the plan was named', 'The number of desks nearby', 'Expected avoided loss depends on loss size multiplied by failure probability.'),
    q('Two offers have identical total cost, speed and quality. Only their labels differ. Based on those criteria, what follows?', 'Neither is better on the stated criteria', 'The shorter label must be better', 'The newer label is cheaper', 'One must have higher quality', 'All criteria given are equal.'),
    q('A trial can be expanded later if it works. Which feature makes that possible?', 'The plan allows a staged commitment', 'The full budget is spent immediately', 'The outcome is certain', 'The trial cannot be changed', 'A staged commitment preserves the option to expand after learning.'),
  ]],
  ['Connect the Findings', 'data_interpretation', 'The case comes together', 'The last cases combine rules, quantities and judgement.', [
    q('One trial has 30 successes in 40 attempts. A second trial has 21 in 30. Which has the higher success rate?', 'The first trial', 'The second trial', 'Both have 70%', 'Both have 75%', 'The first has 75%; the second has 70%.'),
    q('A plan needs 120 credits. Funding provides 45 and 55 credits. What is the shortfall?', '20 credits', '10 credits', '25 credits', '100 credits', '120 − (45 + 55) = 20.'),
    q('A survey has 200 responses, 60% positive. How many are positive?', '120', '60', '80', '140', '200 × 0.60 = 120.'),
    q('Two equal-sized groups average 60 and 80 points. What is their combined mean?', '70', '60', '80', '140', 'Equal group sizes make the combined mean (60+80) ÷ 2.'),
    q('A target is 90 tasks. The team completes 28, 31 and 26. How many more are needed?', '5', '4', '6', '15', '28+31+26=85; 90−85=5.'),
    q('An estimate is revised from 400 to 360 units. What percentage decrease is that?', '10%', '9%', '11%', '40%', 'The fall of 40 is 10% of 400.'),
    q('Demand is 70 units. Each full pack contains 12 units, and only whole packs can be ordered. How many packs are needed?', '6', '5', '7', '12', 'Five packs hold 60; six hold 72, enough to meet demand.'),
  ]],
  ['The Final Case', 'analytical_reasoning', 'Your case result is ready', '', [
    q('A choice must cost at most 50 and score at least 8. A is 45/7; B is 55/9; C is 50/8. Which qualifies?', 'C only', 'A only', 'B only', 'A and C', 'Only C meets both the cost and score requirements.'),
    q('A shop earns 6 credits per item after variable costs. Fixed costs are 48 credits. How many items cover those costs exactly?', '8', '6', '12', '48', '48 ÷ 6 = 8.', 'quantitative_reasoning'),
    q('A study changes both the price and the packaging, then sales rise. Which conclusion is warranted?', 'Their separate effects are not established', 'Packaging caused the whole rise', 'Price had no effect', 'Both changes had equal effects', 'Changing both together does not isolate their individual contributions.', 'evidence_judgement'),
    q('A task takes 2 hours, then a second takes 3 hours. They cannot overlap. Starting at 09:30, when do they finish?', '14:30', '12:30', '13:30', '15:30', 'Sequential duration is 5 hours; 09:30 + 5 hours = 14:30.', 'quantitative_reasoning'),
    q('A report says the evidence is “consistent with” a theory. What is the careful reading?', 'The evidence fits, without proving it uniquely', 'The theory is proven beyond all doubt', 'Every alternative is impossible', 'The theory has been disproved', 'Compatibility does not establish that only one explanation can fit.', 'verbal_reasoning'),
    q('Plan A costs 20 now and 5 per use. Plan B costs 8 per use with no initial fee. At 10 uses, which costs less?', 'Plan A, by 10 credits', 'Plan B, by 10 credits', 'They cost the same', 'Plan A, by 20 credits', 'A costs 20+50=70; B costs 80.', 'quantitative_reasoning'),
    q('A recommendation requires reliable demand data and an affordable plan. The plan is affordable; the demand data are missing. What should the conclusion be?', 'The recommendation is not yet established', 'The recommendation is certainly wrong', 'Affordability proves demand', 'Both conditions have been met', 'One required condition remains unverified.', 'evidence_judgement'),
  ]],
]);
