const q = (prompt, answer, b, c, d, reason) => [prompt, answer, b, c, d, undefined, undefined, reason];
export default {
  slug: 'iq',
  summary: 'Follow patterns, compare codes and connect the clues in a varied reasoning challenge.',
  about: 'Explore number patterns, word relationships, logic, directions and attention to detail. Each set changes the kind of thinking involved.\n\nEvery question provides the rule or the clues needed to choose an answer. Take the time you need; there is no speed score. Checkpoints reflect the topic you just completed, followed by an overall result and optional answer review.\n\nThis entertainment challenge gives a quiz score. It is not a standardised IQ test and does not measure clinical or professional cognitive ability.',
  note: 'All puzzles are authored. The answer key states the rule or deduction for every question. Alphabet puzzles use the English A–Z alphabet; directions refer to the displayed page or the compass directions stated. No cultural trivia, currencies or regional word meanings are required.',
  rounds: [
    { title: 'Find the Pattern', category: 'pattern', checkpoint: 'Your pattern snapshot', feedback: 'Patterns: {profile}. Put the numbers to work next.', teaser: 'Small calculations hide clear connections.', questions: [
      q('The shapes alternate: circle, triangle, circle, triangle. What comes next?', 'Circle','Square','Triangle','Diamond','The alternating pair begins again with circle.'),
      q('Add 3 each time: 2, 5, 8, 11. What comes next?', '14','12','13','15','11 + 3 = 14.'),
      q('Double each number: 3, 6, 12, 24. What comes next?', '48','30','36','42','24 × 2 = 48.'),
      q('Subtract 4 each time: 25, 21, 17, 13. What comes next?', '9','7','8','11','13 − 4 = 9.'),
      q('The group repeats: red, blue, green, red, blue. What comes next?', 'Green','Red','Blue','Yellow','Green completes the repeating group.'),
      q('Add one side each time: triangle, square, pentagon. What comes next?', 'Hexagon','Octagon','Circle','Triangle','The side counts are 3, 4, 5, then 6.'),
      q('The dots increase by one each time: 1, 2, 3, 4. How many come next?', '5','4','6','8','4 + 1 = 5.'),
    ] },
    { title: 'Number Connections', category: 'numerical', checkpoint: 'The numbers connect', feedback: 'Number reasoning: {profile}. Change from quantities to words.', teaser: 'Find the relationship that fits both sides.', questions: [
      q('A square stands for 5 and a triangle for 3. What is triangle × square?', '15','8','12','20','3 × 5 = 15.'),
      q('Three boxes contain 24 balls in total. A has 6 and B has twice A. How many are in C?', '6','4','8','12','24 − 6 − 12 = 6.'),
      q('A machine doubles a number, then adds 3. Which input gives 17?', '7','5','6','8','(17 − 3) ÷ 2 = 7.'),
      q('Four equal packets contain 28 cards altogether. How many cards are in each?', '7','4','6','8','28 ÷ 4 = 7.'),
      q('A timer starts at 45 seconds. After 18 seconds pass, how many remain?', '27','23','33','63','45 − 18 = 27.'),
      q('What is one quarter of 36?', '9','6','12','18','36 ÷ 4 = 9.'),
      q('A shelf holds 8 red books and 12 blue books. What fraction are red?', '2/5','1/5','3/5','2/3','8 ÷ 20 simplifies to 2/5.'),
    ] },
    { title: 'Word Connections', category: 'verbal', checkpoint: 'The words fit together', feedback: 'Word relationships: {profile}. Follow the logic in the next clues.', teaser: 'Work out what must be true.', questions: [
      q('A bird uses a nest. A bee colony uses a…', 'Hive','Web','Burrow','Kennel','Hive is the matching home for a bee colony.'),
      q('A thermometer measures temperature. A clock measures…', 'Time','Distance','Mass','Volume','The relationship is instrument to the quantity it measures.'),
      q('Hand is to glove as foot is to…', 'Shoe','Hat','Scarf','Sleeve','A glove covers a hand; a shoe covers a foot.'),
      q('Which word completes both: snow___ and ___room?', 'Ball','Cold','White','Ice','Snowball and ballroom are the two words.'),
      q('Which word completes both: home___ and ___shop?', 'Work','Play','Time','Light','Homework and workshop are the two words.'),
      q('Which pair has the same individual-to-group relationship as bird → flock?', 'Fish → school','Lion → den','Bee → honey','Horse → stable','A school is a group of fish.'),
      q('Which pair are opposites?', 'Expand and shrink','Start and begin','Silent and quiet','Small and tiny','Only expand and shrink express opposite changes.'),
    ] },
    { title: 'Follow the Logic', category: 'logic', checkpoint: 'The logic is clearer', feedback: 'Logical deduction: {profile}. Turn the clues around.', teaser: 'Directions and reflections put space to the test.', questions: [
      q('All blue keys open Gate A. This key is blue. What must be true?', 'It opens Gate A','It opens every gate','It cannot open Gate A','Its colour is unknown','The key belongs to the stated class of keys that open Gate A.'),
      q('All NIM are TOV. No TOV are RAK. Can any NIM be RAK?', 'No','Yes, all of them','Exactly one must be','Exactly two must be','NIM are contained in TOV, which is disjoint from RAK.'),
      q('All glens are quiet. Some parks are glens. What must be true?', 'Some parks are quiet','All parks are quiet','No parks are quiet','All quiet places are parks','The parks that are glens must also be quiet.'),
      q('If the alarm is on, the lamp is lit. The lamp is not lit. What follows?', 'The alarm is not on','The alarm is definitely on','The lamp must be broken','Every other lamp is off','The contrapositive of alarm on implies lamp lit.'),
      q('Every box on Shelf A is sealed. This box is unsealed. What must be true?', 'It is not on Shelf A','It is empty','It is on Shelf A','It is red','An unsealed box cannot belong to the stated set.'),
      q('Only members may enter a club room. Noor entered with permission. What follows?', 'Noor is a member','Noor owns the club','Every member entered','Noor arrived first','Permission to enter requires membership under the stated rule.'),
      q('Some red objects are round. Which claim is guaranteed?', 'At least one round object is red','All red objects are round','All round objects are red','No red objects are square','The overlap exists, but neither whole class is contained in the other.'),
    ] },
    { title: 'Turns and Directions', category: 'spatial', checkpoint: 'A new perspective', feedback: 'Spatial reasoning: {profile}. Look closely at the next details.', teaser: 'Tiny changes in codes can make the difference.', questions: [
      q('You face north and turn right twice, by 90° each time. Which way do you face?', 'South','North','East','West','North → east → south.'),
      q('An arrow points up-right. Reflect it left to right. Where does it point?', 'Up-left','Down-left','Down-right','Up-right','Only the horizontal direction is reversed.'),
      q('An arrow points left. Turn it 90° clockwise. Where does it point?', 'Up','Down','Right','Left','A clockwise quarter-turn takes left to up.'),
      q('Start at a point. Move 3 squares right and 1 square left. Where do you finish?', '2 squares right','2 squares left','4 squares right','At the start','3 − 1 = 2 squares right.'),
      q('A dot is in a square’s top-left corner. Turn the square 180°. Where is the dot?', 'Bottom right','Top right','Bottom left','Top left','A half-turn moves the dot to the opposite corner.'),
      q('An arrow points down-right. Flip it top to bottom. Where does it point?', 'Up-right','Up-left','Down-left','Down-right','Only the vertical direction is reversed.'),
      q('Face east. Turn left 90°, then right 180°. Which way do you face?', 'South','North','East','West','East → north → south.'),
    ] },
    { title: 'Code Detective', category: 'attention', checkpoint: 'The details stand out', feedback: 'Attention to detail: {profile}. Put the clues into order.', teaser: 'A few constraints can reveal the whole arrangement.', questions: [
      q('Which code is an exact copy of K7M2-Q9?', 'K7M2-Q9','K7N2-Q9','K7M2-Q8','K7M3-Q9','Only K7M2-Q9 matches every position.'),
      q('Which copy of K7M2-Q9 changes exactly one character?', 'K7N2-Q9','K7M2-P8','K1M2-Q8','K7N3-Q9','Only M changes to N in the correct copy.'),
      q('Compare 847196 with 847916. Which positions swapped?', '4th and 5th','2nd and 3rd','3rd and 4th','5th and 6th','The 1 and 9 in positions four and five exchange places.'),
      q('Read 6173 in reverse order. What do you get?', '3716','3761','3176','7316','Reversing all four digits gives 3716.'),
      q('Which character appears twice in AB7C2B9?', 'B','A','7','C','B occurs in the second and sixth positions.'),
      q('How many positions differ between R4N7-X2 and R4M7-X9?', '2','1','3','4','N becomes M and the final 2 becomes 9.'),
      q('Swap only the first and last letters of CANDLE. What results?', 'EANDLC','EANDCL','ECNDLA','ELDNAC','C and E swap; A, N, D and L keep their positions.'),
    ] },
    { title: 'Put It in Order', category: 'logic', checkpoint: 'The order emerges', feedback: 'Ordering clues: {profile}. Try the next rule machine.', teaser: 'Work forward—or reverse the steps.', questions: [
      q('Mara is before Leo, and Leo is before Nia. Which order works?', 'Mara, Leo, Nia','Leo, Mara, Nia','Mara, Nia, Leo','Nia, Leo, Mara','Both before-relations are satisfied only by Mara, Leo, Nia.'),
      q('Ana is taller than Ben. Ben is taller than Cleo. Who is shortest?', 'Cleo','Ana','Ben','They are all equal','Ana > Ben > Cleo.'),
      q('Four runners finish without ties. Lee is ahead of Kai; Kai is ahead of Jo; Sam is behind Jo. Who is second?', 'Kai','Lee','Jo','Sam','The full order is Lee, Kai, Jo, Sam.'),
      q('Three books stand left to right. Red is left of blue, and green is right of blue. Which is in the middle?', 'Blue','Red','Green','None','Red, blue, green is the only valid order.'),
      q('Task A must finish before B, and B before C. Which task must be first?', 'A','B','C','All start together','The required sequence is A then B then C.'),
      q('Seats are numbered 1 to 4 from left to right. Kim sits in seat 2. Jo sits immediately to Kim’s right. Where is Jo?', 'Seat 3','Seat 1','Seat 2','Seat 4','Kim is in seat 2, so the adjacent seat on the right is 3.'),
      q('Only W, X, Y and Z are possible. It is not W or Z. If it were X, an alarm would sound. No alarm sounds. Which is it?', 'Y','W','X','Z','W and Z are excluded directly; X is excluded by the silent alarm.'),
    ] },
    { title: 'Rule Machines', category: 'numerical', checkpoint: 'The rule works', feedback: 'Rule machines: {profile}. Watch for rules that run together.', teaser: 'Alternating patterns call for a closer look.', questions: [
      q('A machine multiplies by 3, then subtracts 2. What does input 6 produce?', '16','12','18','20','6 × 3 − 2 = 16.'),
      q('A machine adds 5, then doubles. What does input 4 produce?', '18','13','14','20','(4 + 5) × 2 = 18.'),
      q('A machine divides by 4, then adds 7. What does input 20 produce?', '12','9','11','27','20 ÷ 4 + 7 = 12.'),
      q('A machine triples an input and gives 27. What was the input?', '9','6','8','12','27 ÷ 3 = 9.'),
      q('Use first × second + first. What does the pair 4 and 5 produce?', '24','20','25','28','4 × 5 + 4 = 24.'),
      q('Each upper block is the sum of two below it. Bottom row: 3, 5, 4. Middle: 8, 9. What is the top?', '17','15','16','18','8 + 9 = 17.'),
      q('A machine subtracts 4, then doubles. Which input produces 18?', '13','7','9','11','18 ÷ 2 + 4 = 13.'),
    ] },
    { title: 'Two Rules at Once', category: 'pattern', checkpoint: 'The patterns separate', feedback: 'Combined patterns: {profile}. Bring the whole toolkit together.', teaser: 'A final mix of logic, codes and movement awaits.', questions: [
      q('Alternate adding 1 and 3: 2, 3, 6, 7, 10. What comes next?', '11','12','13','14','The next operation is +1.'),
      q('Odd positions rise by 1; even positions rise by 4: 2, 8, 3, 12, 4, 16, 5, ?. What is missing?', '20','18','22','24','The even-position sequence is 8, 12, 16, 20.'),
      q('Using A–Z, move the first letter forward and second backward by one: AZ, BY, CX. What comes next?', 'DW','DX','EV','CV','C moves to D; X moves back to W.'),
      q('Alternate multiplying by 2 and adding 1: 3, 6, 7, 14, 15. What comes next?', '30','16','28','32','The next operation is ×2.'),
      q('Subtract 1, then 2, then 3, then 4: 20, 19, 17, 14. What comes next?', '10','9','11','12','14 − 4 = 10.'),
      q('Each number is double the previous number minus 1: 2, 3, 5, 9, 17. What comes next?', '33','31','34','35','17 × 2 − 1 = 33.'),
      q('Using A–Z, move ahead by 2, then 3, then 4, then 5 letters: A, C, F, J. What comes next?', 'O','N','P','Q','J is position 10; 10 + 5 = 15, which is O.'),
    ] },
    { title: 'The Final Connections', category: 'logic', checkpoint: 'Your reasoning result is ready', questions: [
      q('Exactly one tells the truth. A says B lies. B says C lies. C says A and B both lie. Who tells the truth?', 'B','A','C','Nobody','Only A false, B true, C false satisfies all three statements and exactly one truth.'),
      q('Use A–Z. Shift DOG by +1, +2, +1 letters respectively. What is the code?', 'EQH','EPH','FQH','ERJ','D→E, O→Q, G→H.'),
      q('Move 2 squares up, 1 right, 1 down and 2 left. Where do you finish relative to the start?', '1 left and 1 up','1 right and 1 up','2 left','Back at the start','Net horizontal movement is 1 − 2 = −1; net vertical movement is 2 − 1 = 1.'),
      q('An arrow points up. Turn it 90° clockwise, then reflect it left to right. Where does it point?', 'Left','Up','Right','Down','Up turns to right, then reflects to left.'),
      q('A machine runs every 3 days, starting on day 2. On which day is its fourth run?', 'Day 11','Day 8','Day 9','Day 12','The runs are on days 2, 5, 8 and 11.'),
      q('A code reverses a word, then replaces A with 4. How does LAMP become coded?', 'PM4L','P4ML','L4MP','4PML','LAMP reverses to PMAL, then A becomes 4.'),
      q('A box has only red and blue balls. There are 12 balls; twice as many are red as blue. How many are blue?', '4','3','6','8','Let blue be b. Then b + 2b = 12, so b = 4.'),
    ] },
  ],
};
