import { sources, infection, communication, records, numbers, makeRound as r, healthNote } from './health-shared.mjs';
export default {
  slug: 'midwifery', sources, note: healthNote,
  summary: 'Connect pregnancy, birth, newborn care and clear communication through practical clues.',
  about: 'Explore pregnancy physiology, birth, newborn wellbeing, observation and respectful care. Each set introduces a new topic and a fresh checkpoint.\n\nChoose the answer best supported by the information given. Your overall result includes topic strengths and an optional review of missed answers.\n\nThe questions use broad principles that do not depend on one country’s maternity pathway. Any real concern needs qualified maternity advice; this entertainment quiz is not a clinical assessment or an accredited entrance examination.',
  rounds: [
    r('Pregnancy Foundations','pregnancy_physiology','Your maternity knowledge snapshot','Pregnancy foundations: {profile}. Look at care before birth.','Notice the changes that deserve attention.',[
      ['Which organ supports exchange between the pregnant person and the developing baby?', 'Placenta', 'Bladder', 'Pancreas', 'Appendix', 'pregnancy'],
      ['Where does a baby normally develop during pregnancy?', 'Uterus', 'Bladder', 'Stomach', 'Kidney', 'pregnancy'],
      ['What connects the baby to the placenta?', 'Umbilical cord', 'Cervix', 'Diaphragm', 'Ureter', 'pregnancy'],
      ['What is one main role of amniotic fluid?', 'Cushion the developing baby', 'Replace the placenta', 'Digest food in the stomach', 'Produce adult teeth', 'pregnancy'],
      ['Which structure is the lower opening of the uterus?', 'Cervix', 'Ovary', 'Ureter', 'Diaphragm', 'pregnancy'],
      ['Before birth, oxygen normally reaches the baby through which route?', 'Placental exchange and the umbilical cord', 'Air breathed directly through the mouth', 'The bladder and ureter', 'The stomach and intestines', 'pregnancy'],
      ['Which organ provides the muscular contractions of childbirth?', 'Uterus', 'Placenta', 'Bladder', 'Ovary', 'birth'],
    ]),
    r('Care Before Birth','antenatal_wellbeing','The changes come into focus','Pregnancy care: {profile}. Put the records under the spotlight.','Spot what a chart says—and what it cannot tell you.',[
      ['What does antenatal or prenatal care mean?', 'Care during pregnancy before birth', 'Care only after birth', 'Care only during surgery', 'Care only for newborns', 'pregnancy'],
      ['A severe new headache occurs with visual changes during pregnancy. What is safest?', 'Seek urgent qualified maternity assessment', 'Wait for the next routine appointment', 'Assume every headache is expected', 'Ignore the visual change', 'maternal'],
      ['A baby’s usual movement pattern slows noticeably. What is the safest response?', 'Contact a qualified maternity service promptly', 'Wait several days to see a pattern', 'Assume all babies stop moving before birth', 'Rely only on another person’s experience', 'maternal'],
      ['Why ask about current medicines at a pregnancy appointment?', 'To support an informed review of their suitability', 'To stop every medicine automatically', 'To replace the rest of the assessment', 'To select treatment from the package colour', 'pregnancy'],
      ['Which report needs urgent attention during pregnancy?', 'Sudden severe chest pain or trouble breathing', 'A request to reschedule a routine class', 'A change in the appointment room', 'A question about the clinic’s opening time', 'maternal'],
      ['A pregnant person reports persistent vomiting and cannot keep fluids down. What is safest?', 'Seek qualified assessment promptly', 'Assume hydration cannot be affected', 'Wait until the next month', 'Treat a normal earlier visit as proof all is well', 'maternal'],
      ['Why should a new concern still be assessed after an earlier normal appointment?', 'The person’s condition can change', 'Earlier results are always incorrect', 'Symptoms matter only at the first visit', 'Every new symptom proves the same diagnosis', 'maternal'],
    ]),
    r('Reading the Record','antenatal_wellbeing','The record tells a story','Reading records: {profile}. Follow the changes during birth.','Connect the stages with what is happening.',records),
    r('Birth and Progress','labour_birth','The birth process connects','Birth knowledge: {profile}. Focus on the baby’s first moments.','Warmth, breathing and early observation come next.',[
      ['What does cervical dilation describe?', 'The cervix opening', 'The placenta growing', 'The uterus moving upward', 'The bladder filling', 'birth'],
      ['What does cervical effacement describe?', 'The cervix thinning', 'The placenta separating', 'The baby beginning to feed', 'The umbilical cord lengthening', 'birth'],
      ['Which stage of childbirth ends when the cervix is fully dilated?', 'The first stage', 'The second stage', 'The third stage', 'The postnatal period', 'birth'],
      ['Which stage runs from full cervical dilation to the baby’s birth?', 'The second stage', 'The first stage', 'The third stage', 'The antenatal period', 'birth'],
      ['The baby is born but the placenta has not yet been delivered. Which stage is this?', 'The third stage', 'The first stage', 'The second stage', 'The antenatal stage', 'birth'],
      ['Which description is most useful when recording contractions?', 'Their frequency, duration and strength', 'Only the blanket colour', 'Only the room number', 'Only the person’s shoe size', 'birth'],
      ['Constant severe pain with faintness replaces previously comfortable pauses. What is safest?', 'Seek urgent qualified assessment of the change', 'Assume every later change must be expected', 'Wait for a planned routine check', 'Choose a diagnosis before reporting anything', 'maternal'],
    ]),
    r('The First Moments','newborn_care','Your newborn-care snapshot','Newborn foundations: {profile}. Look at feeding and everyday wellbeing.','Small observations can reveal important changes.',[
      ['What helps a stable newborn conserve warmth soon after birth?', 'Thorough drying and supported skin-to-skin care', 'Leaving wet blankets in place', 'A cold bath', 'Unnecessary exposure to a cool room', 'newborn'],
      ['Why can leaving a newborn wet increase heat loss?', 'Evaporation removes heat from the skin', 'Water permanently blocks all heat loss', 'Wet fabric always warms itself', 'Newborns cannot lose body heat', 'newborn'],
      ['Which function needs assessment immediately after birth?', 'Breathing', 'Ability to read', 'Permanent tooth development', 'Walking balance', 'newborn'],
      ['For a stable newborn having skin-to-skin care, what still matters?', 'Observation and keeping the airway clear', 'Covering the face completely', 'Leaving the baby unobserved', 'Assuming position never matters', 'newborn'],
      ['Which concern in a newborn calls for urgent qualified help?', 'Difficulty breathing', 'A need for a clean blanket', 'A parent asking a routine question', 'A label needing a clearer font', 'newbornSigns'],
      ['What is the general aim of thermal care for a newborn?', 'Maintain a safe body temperature', 'Make the baby as hot as possible', 'Keep the skin constantly wet', 'Avoid checking warmth', 'newborn'],
      ['A stable newborn has been dried, but the blanket is now wet. What supports warmth?', 'Replace wet material with suitable dry covering', 'Keep the wet material indefinitely', 'Expose the baby to a cold draft', 'Use cold water to dry the skin', 'newborn'],
    ]),
    r('Feeding and Wellbeing','newborn_care','The small signs matter','Feeding and wellbeing: {profile}. Bring infection prevention into the picture.','Choose the habits that protect clean care.',[
      ['What is colostrum?', 'The early milk produced around the start of breastfeeding', 'A type of amniotic fluid', 'A newborn bone', 'A hormone made only by the placenta', 'feeding'],
      ['Which behaviour can be an early feeding cue?', 'Turning toward touch near the mouth and seeking to suck', 'Becoming completely unresponsive', 'Struggling to breathe', 'Having repeated convulsions', 'feeding'],
      ['A newborn is feeding less and breathing noticeably faster. What is safest?', 'Seek prompt qualified assessment', 'Assume the two changes cancel out', 'Wait until the next routine visit', 'Record only the feeding time', 'newbornSigns'],
      ['A parent is struggling with feeding. What is the most helpful response?', 'Listen and arrange appropriate feeding support', 'Blame the parent for asking', 'Promise one method always works instantly', 'Dismiss the concern without assessment', 'feeding'],
      ['Which sleep position is recommended for most healthy babies?', 'On their back', 'On their stomach', 'Propped on their side with pillows', 'Sitting unsupported in bed', 'sleep'],
      ['Which sleep space supports safer infant sleep?', 'A firm, flat sleep surface without loose soft items', 'A soft pillow nest', 'A sofa cushion with loose blankets', 'An adult armchair', 'sleep'],
      ['A parent says their newborn is much less active than usual. What is appropriate?', 'Take the change seriously and seek qualified assessment', 'Ignore it if the baby was well yesterday', 'Assume all reduced activity is normal sleep', 'Wait for every other symptom to appear', 'newbornSigns'],
    ]),
    r('Clean and Safe Care','infection_safety','Safe care takes shape','Infection prevention: {profile}. Good care also needs clear communication.','Respect choices and make explanations easier to follow.',infection),
    r('Respectful Communication','communication_priorities','The conversation matters','Communication: {profile}. Check the figures behind the care.','Use the stated units and timings.',communication),
    r('Maternity Numbers','antenatal_wellbeing','The figures add up','Measurements: {profile}. Bring the clues together.','Apply careful reasoning to a mix of maternity situations.',numbers(1)),
    r('Putting Care Together','communication_priorities','Your midwifery result is ready',undefined,undefined,[
      ['Which handover puts a new urgent concern first?', '“New severe headache with visual changes; urgent review needed”', '“The room number changed yesterday”', '“The next routine visit is booked”', '“The earlier leaflet was useful”', 'maternal'],
      ['A person asks for time to consider a non-urgent care option. What respects their choice?', 'Explain the options and allow appropriate time for questions', 'Treat the request as automatic agreement', 'Ask a visitor to decide without permission', 'Withhold all further information', 'rights'],
      ['After birth, heavy bleeding occurs with faintness. What is the safest priority?', 'Urgent qualified assessment and help', 'Finish routine paperwork first', 'Wait to see if the next day is better', 'Assume bleeding cannot become serious after birth', 'maternal'],
      ['A normal earlier record is followed by new breathing difficulty. Which information guides the response now?', 'The current change alongside the earlier record', 'Only the earlier normal entry', 'Only the appointment date', 'Only the person’s age', 'maternal'],
      ['A clean task follows handling contaminated equipment. What should happen before continuing?', 'Perform appropriate hand hygiene and change equipment or gloves as needed', 'Continue because both tasks are in the same room', 'Wipe used gloves on clothing', 'Move contamination to a different tray', 'precautions'],
      ['A concerned parent describes a change you did not witness. What is the useful response?', 'Listen, clarify the change and arrange assessment when needed', 'Dismiss it because you were not present', 'Record an unconfirmed diagnosis as fact', 'Ask them not to mention changes again', 'rights'],
      ['A fluid record shows 650 mL plus 450 mL. A separate pulse record rises from 74 to 82. Which summary is accurate?', '1,100 mL total; pulse increased', '650 mL total; pulse unchanged', '450 mL total; pulse decreased', '1,650 mL total; pulse unchanged', undefined, 'antenatal_wellbeing', '650 + 450 = 1,100 mL; 82 is greater than 74.'],
    ]),
  ],
};
