import {q, universityPack} from './university-shared.mjs';
export default universityPack('oxford', 'Connect words, test arguments and follow the clues through a varied reasoning challenge.', [
  ['Word Connections', 'verbal_reasoning', 'Your first connections', 'Small changes in wording can change the whole claim.', [
    q('A map represents a place. A portrait represents a…', 'Person', 'Journey', 'Direction', 'Frame', 'The relation is a representation and what it depicts.'),
    q('A chapter is part of a book. A scene is part of a…', 'Play', 'Library', 'Reader', 'Ticket', 'Both pairs relate a component to the work containing it.'),
    q('A thermometer measures temperature. A ruler measures…', 'Length', 'Time', 'Mass', 'Sound', 'Both objects are instruments for measuring the named quantity.'),
    q('Which word is closest in meaning to “concise”?', 'Brief', 'Uncertain', 'Repetitive', 'Decorative', 'Concise means expressing something briefly.'),
    q('Which pair has the same relationship as seed → plant?', 'Egg → bird', 'Bird → nest', 'Plant → soil', 'Leaf → branch', 'The first develops into the second.'),
    q('Which word is the opposite of “expand”?', 'Shrink', 'Extend', 'Increase', 'Enlarge', 'Shrink reverses the change described by expand.'),
    q('A glossary explains words. An index helps you find…', 'Locations of topics', 'The author’s opinions', 'The book’s price', 'The cover’s material', 'An index directs the reader to where topics appear.'),
  ]],
  ['Meaning in the Details', 'verbal_reasoning', 'The meaning comes into focus', 'Can you follow a rule without adding an assumption?', [
    q('“Not all entries were complete.” What must be true?', 'At least one entry was incomplete', 'No entry was complete', 'Exactly half were incomplete', 'Every entry was complete', 'Not all means at least one exception.'),
    q('A claim is described as “plausible”. What does that mean?', 'It could reasonably be true', 'It has been proven', 'It is necessarily false', 'Everyone accepts it', 'Plausibility is reasonableness, not proof.'),
    q('“At most four people may enter.” Which number is allowed?', '4', '5', '6', '8', 'At most four permits any number up to and including four.'),
    q('Which sentence reports a measurement rather than an opinion?', 'The table is 120 cm long', 'The table looks elegant', 'The table is the best', 'The table feels welcoming', 'A stated length is a measurement.'),
    q('“The method may help.” Which rewrite preserves the uncertainty?', 'The method could help', 'The method will help', 'The method always helps', 'The method cannot help', 'May and could both indicate possibility here.'),
    q('An account is “ambiguous” when it…', 'Allows more than one interpretation', 'Contains no words', 'Is necessarily false', 'Gives exactly one clear meaning', 'Ambiguity permits multiple meanings.'),
    q('“Only registered guests entered.” What is guaranteed?', 'Everyone who entered was registered', 'Every registered guest entered', 'No guest was registered', 'Registration happened after entry', 'Only restricts those who entered; it does not say all registered guests did.'),
  ]],
  ['Follow the Rules', 'formal_logic', 'Your logic snapshot', 'Numbers bring a different kind of precision.', [
    q('All poets in a club are readers. Mina is one of those poets. What follows?', 'Mina is a reader', 'All readers are poets', 'Mina wrote every poem', 'Mina is the only reader', 'Mina belongs to the group stated to be readers.'),
    q('No green cards are valid. This card is valid. What must be true?', 'It is not green', 'It is green', 'It is blue', 'It is new', 'A valid card cannot belong to the invalid green group.'),
    q('If a switch is on, its light is on. The light is off. What follows?', 'The switch is off', 'The switch is on', 'The light must be broken', 'The room is empty', 'The contrapositive excludes the switch being on.'),
    q('Some musicians are teachers. Which is guaranteed?', 'Some teachers are musicians', 'All teachers are musicians', 'No musician teaches', 'All musicians are teachers', 'The stated overlap works in both directions.'),
    q('Every sealed envelope has a stamp. This envelope has a stamp. What can you conclude about whether it is sealed?', 'That is not determined', 'It must be sealed', 'It must be open', 'It has no contents', 'A stamp is necessary under the rule, but not sufficient to prove sealing.'),
    q('A rule requires both A and B. A is present, B is absent. Is the rule satisfied?', 'No', 'Yes', 'Only if A came first', 'Only if A is repeated', 'A conjunction requires both conditions.'),
    q('All LUM are PAV. No PAV are ZET. Which must be true?', 'No LUM are ZET', 'All ZET are LUM', 'Some LUM are ZET', 'All PAV are LUM', 'The LUM group lies wholly inside PAV, which excludes ZET.'),
  ]],
  ['Quantities and Proportions', 'quantitative_reasoning', 'The quantities fit', 'What must an argument assume to work?', [
    q('A book costs 24 credits after a 20% discount. What was the original price?', '30 credits', '28 credits', '29 credits', '32 credits', '24 is 80% of 30.'),
    q('Two thirds of 27 people choose option A. How many choose it?', '18', '9', '15', '21', '27 × 2/3 = 18.'),
    q('The mean of 6, 10, 14 and x is 12. What is x?', '18', '12', '14', '16', 'Four values must total 48; the known values total 30.'),
    q('A session begins at 14:35 and lasts 1 hour 45 minutes. When does it finish?', '16:20', '16:00', '16:10', '16:30', '14:35 + 1:45 = 16:20.'),
    q('A reader covers 30 pages a day. How many pages remain in a 240-page book after 5 days?', '90', '100', '110', '120', '240 − 5 × 30 = 90.'),
    q('The ratio of red to blue beads is 2:3. There are 25 beads in total. How many are red?', '10', '5', '15', '20', 'There are five ratio parts, each worth five beads; red gets two parts.'),
    q('A value doubles, then 6 is added, giving 30. What was the original value?', '12', '9', '15', '18', '(30 − 6) ÷ 2 = 12.'),
  ]],
  ['Hidden Assumptions', 'critical_reasoning', 'The assumptions emerge', 'Sometimes the best answer is what we cannot yet know.', [
    q('“Keeping the library open for extra hours will allow more visits.” Which assumption directly supports this?', 'Some people would use the extra hours', 'Every visitor reads fiction', 'All books are new', 'The library has two floors', 'Extra opening hours need additional potential use to increase visits.'),
    q('“This route is shorter, so it will be faster.” Which missing issue matters most?', 'The travel speeds on the routes', 'The route names', 'The colour of the map', 'The date the roads were named', 'Time depends on speed as well as distance.'),
    q('“The same total work can be finished sooner by adding staff.” Which assumption is needed?', 'The extra staff can contribute useful work', 'All staff have identical names', 'The deadline has already passed', 'The work has already finished', 'Additional staff must increase useful capacity for the claim to hold.'),
    q('“Our club is popular because all five people I asked like it.” What is the main gap?', 'Those five may not represent the wider group', 'Five people can never like a club', 'Popularity cannot be discussed', 'The club must be unpopular', 'The sample may not justify a broad claim.'),
    q('Which finding weakens “The new lessons alone caused higher scores”?', 'The test also became easier', 'The lessons had a new title', 'Students used blue pens', 'The classroom had a clock', 'An easier test offers an alternative explanation for higher scores.'),
    q('A seller says a product is reliable because it is expensive. What link is missing?', 'Evidence connecting its price to reliability', 'The exact lettering on its label', 'The date of the next holiday', 'Proof that every product is cheap', 'Price alone does not establish reliability.'),
    q('“The plan worked once, so it will always work.” What is the reasoning problem?', 'One success does not establish every future case', 'Past events never provide evidence', 'The first success must be false', 'A plan can work only once', 'A universal prediction requires more than a single example.'),
  ]],
  ['What Is Missing?', 'information_analysis', 'The evidence has limits', 'A handful of clues can reveal an exact order.', [
    q('Among 100 people, 70 use the library and 50 attend tutorials. Both or neither are possible. Can the exact overlap be found?', 'No, more information is needed', 'Yes, it is exactly 20', 'Yes, it is exactly 50', 'Yes, it is exactly 70', 'The overlap can range from 20 to 50, depending on how many do neither.'),
    q('A box holds 12 red or blue counters. What extra fact would determine the number of red counters?', 'The number of blue counters', 'The box’s colour', 'The counters’ weight', 'The shelf’s height', 'Subtracting the blue count from 12 gives the red count.'),
    q('A headline says “Visits doubled”. Which detail is needed to know the numerical increase?', 'The original number of visits', 'The headline’s font', 'The reporter’s age', 'The entrance colour', 'Doubling adds the original count, which has not been stated.'),
    q('Two classes have average scores of 50 and 80. What is needed to calculate the combined mean?', 'The number of students in each class', 'The order of the class names', 'The colour of their notebooks', 'The classrooms’ floor numbers', 'The combined mean must be weighted by class sizes.'),
    q('A journey is 180 km long. Which extra fact lets you calculate its duration at a constant speed?', 'The speed', 'The number of seats', 'The vehicle’s colour', 'The driver’s first name', 'Time equals distance divided by speed.'),
    q('A survey says most respondents agree. What should you inspect before generalising to a city?', 'How respondents were selected', 'Whether the title is short', 'How many pages the report has', 'Whether the paper is glossy', 'Selection determines how well the sample represents the city.'),
    q('A timetable gives a start but no finish. Which fact would let you find the finish?', 'The duration', 'The room number', 'The speaker’s initials', 'The ticket colour', 'Adding duration to the start time gives the finish.'),
  ]],
  ['Put the Clues in Order', 'formal_logic', 'The order becomes clear', 'Now turn the same precision towards space.', [
    q('Nia finishes before Omar, who finishes before Pia. Who finishes last?', 'Pia', 'Nia', 'Omar', 'All tie', 'The order is Nia, Omar, Pia.'),
    q('Four books stand in order: A immediately before B, B immediately before C, and C immediately before D. Which is third?', 'C', 'A', 'B', 'D', 'The only order is A, B, C, D.'),
    q('Three talks occupy Monday, Tuesday and Wednesday. History is before Music; Music is before Art. When is Music?', 'Tuesday', 'Monday', 'Wednesday', 'It cannot be determined', 'Music must sit between History and Art.'),
    q('Seats are numbered 1 to 5 from left to right. Rae sits at 4. Sol sits two seats to Rae’s left. Which seat is Sol’s?', '2', '1', '3', '5', '4 − 2 = 2.'),
    q('A is heavier than B. C is lighter than B. Which is heaviest?', 'A', 'B', 'C', 'They are equal', 'A > B > C.'),
    q('Only P, Q or R can be chosen. P is excluded. Choosing Q would require a permit, but no permit exists. What remains?', 'R', 'P', 'Q', 'P and Q', 'Both P and Q are excluded by the stated conditions.'),
    q('Only X, Y and Z are scheduled. X and Y must both precede Z; their own order is unspecified. Which is guaranteed?', 'Z is last', 'X is first', 'Y is first', 'X and Y are simultaneous', 'With only X, Y and Z, both preceding Z makes Z last; X and Y may swap.'),
  ]],
  ['Turns and Viewpoints', 'spatial_reasoning', 'A different perspective', 'Which argument still holds when you test it closely?', [
    q('An arrow points northeast. Turn it 90° clockwise. Where does it point?', 'Southeast', 'Northwest', 'Southwest', 'Northeast', 'A clockwise quarter-turn changes northeast to southeast.'),
    q('A mark is at the top-right of a square. Rotate the square 180°. Where is the mark?', 'Bottom-left', 'Top-left', 'Bottom-right', 'Top-right', 'A half-turn sends a corner to its opposite.'),
    q('Move 4 squares left, then 6 right. Where are you relative to the start?', '2 squares right', '2 squares left', '10 squares right', 'At the start', '−4 + 6 = 2.'),
    q('Reflect an up-left arrow across a vertical mirror line. Where does it point?', 'Up-right', 'Down-left', 'Down-right', 'Up-left', 'A vertical mirror reverses left and right only.'),
    q('Face south. Turn left by 90°. Which direction now?', 'East', 'West', 'North', 'South', 'From south, a left quarter-turn points east.'),
    q('A point at (3, 2) moves 2 units right and 1 unit down. What are its new coordinates?', '(5, 1)', '(1, 3)', '(5, 3)', '(1, 1)', 'Right increases x by 2; down decreases y by 1.'),
    q('A shape is reflected across the same mirror line twice. Where does it end?', 'In its original position and orientation', 'Rotated by 90°', 'Twice as large', 'Always upside down', 'Applying the same reflection twice reverses the first reflection.'),
  ]],
  ['Arguments Under Scrutiny', 'critical_reasoning', 'The stronger argument', 'The final clues combine language, logic and numbers.', [
    q('Which is a counterexample to “Every square number is even”?', '9', '4', '16', '36', '9 = 3² and is odd.'),
    q('A conclusion requires P and Q. Only P is established. What is the careful verdict?', 'The conclusion is not yet established', 'The conclusion must be false', 'Q must be true', 'P proves both conditions', 'The required Q remains unknown.'),
    q('Which response addresses an argument’s evidence rather than its author?', 'The sample excludes half the population', 'The author has an unfamiliar name', 'The author dresses casually', 'The author lives far away', 'Sampling criticism concerns the evidence itself.'),
    q('A study finds that two measures rise together. What alone follows?', 'They are associated in the data', 'One definitely causes the other', 'Neither can have another cause', 'They will always rise', 'Association is observed; causal direction is not established.'),
    q('A policy is defended only because it has always been used. What is still missing?', 'Evidence that it serves the current goal', 'Proof of its age', 'A longer policy name', 'A list of past titles', 'Tradition alone does not establish present effectiveness.'),
    q('One explanation fits the observations. What would justify ruling out all alternatives?', 'Evidence excluding those alternatives', 'Repeating the same explanation', 'Giving it a shorter name', 'Knowing who suggested it first', 'A fit alone is not proof of uniqueness.'),
    q('An experiment can produce evidence that would refute a claim. What does that make the claim?', 'Testable in that experiment', 'Automatically true', 'Automatically false', 'Impossible to discuss', 'The possibility of disconfirming evidence makes it testable.'),
  ]],
  ['The Final Tutorial', 'formal_logic', 'Your reasoning result is ready', '', [
    q('Exactly one statement is true. A says “B is true”. B says “A and C are false”. C says “B is false”. Which is true?', 'C', 'A', 'B', 'None', 'Only A false, B false, C true satisfies all three statements and one truth.'),
    q('A fictional course requires Logic at least 80 and Writing at least 70. Ava has 84/68; Bo 79/90; Cy 82/74. Who qualifies?', 'Cy', 'Ava', 'Bo', 'Ava and Cy', 'Only Cy satisfies both inequalities.'),
    q('Of 60 people, 40 use A, 35 use B, and everyone uses at least one. How many use both?', '15', '5', '25', '35', '40 + 35 − 60 = 15.', 'quantitative_reasoning'),
    q('A quantity rises by 20%, then falls by 20%. Starting at 100, where does it finish?', '96', '100', '104', '80', '100 × 1.2 × 0.8 = 96.', 'quantitative_reasoning'),
    q('An upward arrow turns 90° clockwise, then reflects across a vertical line. Where does it point?', 'Left', 'Right', 'Up', 'Down', 'Up turns right, then a vertical mirror sends right to left.', 'spatial_reasoning'),
    q('A library changes its hours and visits rise. Which comparison best checks for a seasonal effect?', 'A similar library with unchanged hours over the same period', 'Its own visits one day after the change only', 'The number of letters in its new timetable', 'The designer’s preferred opening time', 'A contemporaneous comparison helps separate shared seasonal changes.', 'information_analysis'),
    q('“All finalists passed a test” and “Some test passers are not finalists” are both true. Which follows?', 'Passing is necessary but not sufficient to be a finalist', 'Every test passer is a finalist', 'No finalist passed', 'Only finalists took the test', 'Finalists all pass, while some passers do not become finalists.'),
  ]],
]);
