import { sources, body, observation, communication, records, numbers, makeRound as r, healthNote } from './health-shared.mjs';
export default {
  slug: 'paramedic', sources, note: healthNote,
  summary: 'Read the scene, notice changing observations and connect the clues under pressure.',
  about: 'Explore body systems, scene awareness, observations, communication and practical reasoning. Each set brings a different kind of emergency-care clue into focus.\n\nChoose the answer supported by the information shown. Checkpoints describe your performance on the topic just completed, followed by an overall result and optional answer review.\n\nQuestions avoid local emergency numbers, medication doses, clinical algorithms and country-specific professional powers. This entertainment quiz is not an accredited entrance exam, practical assessment or instruction for treating a real emergency.',
  rounds: [
    r('Body Foundations','anatomy_physiology','Your emergency-care snapshot','Body foundations: {profile}. Look beyond the patient to the scene.','Spot the hazards that change the first decision.',body),
    r('Scene Awareness','scene_safety','The scene comes into focus','Scene safety: {profile}. Now watch for changes in the person.','Connect observations without assuming a cause.',[
      ['A live electrical cable blocks the doorway. What comes first?', 'Keep clear and obtain qualified help to make the area safe', 'Step over it while carrying equipment', 'Move it with an ordinary household object', 'Ask an untrained bystander to hold it away', 'emergency'],
      ['A person is beside moving traffic with no protected working area. What is safest?', 'Keep clear and arrange appropriate scene support', 'Walk into traffic without protection', 'Place a bag in the lane as the only barrier', 'Assume drivers have already seen everyone', 'emergency'],
      ['Smoke begins to block an exit that was clear earlier. What matters now?', 'Reassess safety and seek appropriate support', 'Rely only on the earlier safe assessment', 'Ignore the smoke until paperwork is complete', 'Treat the original plan as unchangeable', 'emergency'],
      ['Used needles and broken glass lie on the floor. What is the safe initial response?', 'Keep people away and arrange safe removal', 'Pick them up with bare hands', 'Kick them into a corner', 'Hide them beneath a towel', 'precautions'],
      ['A strong fuel smell is present after a vehicle collision. What does it indicate?', 'A potential hazard requiring scene precautions', 'Proof that no fire risk exists', 'A reason to use a flame for a closer look', 'Permission to ignore vehicle safety', 'emergency'],
      ['A person at the scene becomes violent and blocks the approach. What is appropriate?', 'Keep a safe distance and request suitable support', 'Approach alone to argue', 'Ask a bystander to restrain them without help', 'Ignore the threat because a task is waiting', 'emergency'],
      ['Why should scene safety be reassessed as an incident develops?', 'Hazards can change over time', 'The first impression never matters', 'A uniform removes every hazard', 'A safe entrance guarantees every later area is safe', 'emergency'],
    ]),
    r('Noticing Changes','observation_vitals','The observations tell a story','Observation: {profile}. Put the timings and quantities to work.','Find the answer using the numbers given.',observation),
    r('Time and Quantities','numeracy_measurement','The numbers connect','Calculations: {profile}. Make the next conversation count.','Use clear language and protect dignity.',numbers(3)),
    r('Clear Communication','communication_handover','The message gets through','Communication: {profile}. Choose equipment with purpose.','Match the tool to the information or protection needed.',communication),
    r('Equipment and Protection','scene_safety','The right tool for the task','Equipment knowledge: {profile}. Look closely at the written clues.','Find the missing details and useful comparisons.',[
      ['Which tool is designed to measure body temperature?', 'Thermometer', 'Stethoscope', 'Pulse oximeter', 'Measuring tape'],
      ['Which instrument is used to listen to body sounds?', 'Stethoscope', 'Thermometer', 'Sharps container', 'Measuring jug'],
      ['Which device uses an inflatable cuff to help measure blood pressure?', 'A blood pressure monitor', 'A pulse oximeter', 'An oxygen cylinder alone', 'A thermometer'],
      ['A task risks splashing body fluid into the eyes. What protection addresses that risk?', 'Appropriate eye or face protection', 'Shoe covers alone', 'A hat alone', 'An apron alone', 'precautions'],
      ['A sterile dressing packet is damaged. What is the safe decision?', 'Do not assume the dressing remains sterile', 'Use it because the label is readable', 'Tape the outside and call it sterile', 'Ignore the damage if the packet is dry', 'precautions'],
      ['Why check equipment before it is needed?', 'To identify missing items or faults early', 'To guarantee it can never fail later', 'To replace all training', 'To avoid checking instructions for unfamiliar equipment'],
      ['A device displays an error message. What should guide the response?', 'The instructions and an appropriate assessment of the situation', 'Guessing from the screen colour alone', 'Treating the error as a normal patient value', 'Ignoring all other observations'],
    ]),
    r('Reading the Record','observation_vitals','The record becomes clearer','Records: {profile}. Connect the observations with body functions.','Focus on what the assessment is trying to establish.',records),
    r('Assessment Foundations','anatomy_physiology','The assessment connects','Assessment foundations: {profile}. Put teamwork into the picture.','Choose the information that helps others act.',[
      ['In the WHO Basic Emergency Care ABCDE approach, what does A refer to?', 'Airway', 'Age', 'Appetite', 'Appointment', 'emergency'],
      ['In that ABCDE approach, what does B refer to?', 'Breathing', 'Bone density', 'Body mass alone', 'Birthplace', 'emergency'],
      ['In that ABCDE approach, what does C refer to?', 'Circulation', 'Communication preference alone', 'Calorie intake', 'Clothing size', 'emergency'],
      ['Which observation directly concerns responsiveness?', 'Whether the person responds to a spoken question', 'The colour of the equipment bag', 'The number of available forms', 'The date on a wall calendar', 'emergency'],
      ['Why can ineffective breathing affect body tissues?', 'Less oxygen may reach the blood and tissues', 'Bones immediately replace the lungs', 'The stomach produces extra oxygen', 'Tissues stop needing oxygen', 'anatomy'],
      ['What does circulation transport to body tissues?', 'Blood carrying oxygen and nutrients', 'Air through the bronchi', 'Food through the stomach', 'Urine through the ureters', 'anatomy'],
      ['Why does sudden reduced alertness deserve attention?', 'It may signal a serious change needing assessment', 'It always proves ordinary tiredness', 'It rules out a breathing problem', 'It makes other observations unnecessary', 'emergency'],
    ]),
    r('Team Decisions','reasoning_priorities','The priorities take shape','Teamwork and priorities: {profile}. Bring the whole picture together.','Combine scene clues, observations and clear reasoning.',[
      ['Which first message gives responders the clearest useful scene picture?', '“River Gate: two people, smoke present, access blocked”', '“Something has happened somewhere nearby”', '“The scene is difficult; I have no details”', '“Please come; the colour of the vehicle is blue”'],
      ['A critical instruction is hard to hear over noise. What should the receiver do?', 'Ask for clarification and repeat back the key details', 'Guess the missing words', 'Nod without understanding', 'Replace it with a different instruction'],
      ['A new urgent concern develops during a routine equipment check. What should guide the priority?', 'The immediate risk and the need for qualified help', 'Finishing every routine item first', 'Whichever task is nearest', 'The order written on an old list', 'emergency'],
      ['Several people assume someone else has requested help. What is missing?', 'Clear assignment and confirmation of the task', 'A longer list of unrelated facts', 'A new colour for the radio', 'An extra unverified assumption'],
      ['A colleague reports a sudden change. What makes the handover more useful?', 'Ask what changed, when and what was observed', 'Ask only about the room number', 'Assume a diagnosis without details', 'Ignore it because the person was stable earlier'],
      ['A task requires skills you do not have. What is appropriate?', 'Request qualified assistance and follow the relevant guidance', 'Attempt it because someone is watching', 'Use an unrelated technique from memory', 'Ask an untrained bystander to perform it', 'rights'],
      ['Two sources give conflicting incident times. What should be recorded?', 'The discrepancy and the need to clarify it', 'A guessed time presented as certain', 'No record of either source', 'Whichever time looks neater'],
    ]),
    r('The Combined Picture','reasoning_priorities','Your paramedic result is ready',undefined,undefined,[
      ['Person A has a sore wrist and speaks normally. Person B is newly confused and struggling to breathe. Who needs urgent attention?', 'Person B', 'Person A because the wrist is visible', 'Whichever person is closest to a chair', 'Neither until a diagnosis is confirmed', 'emergency'],
      ['A call is logged at 14:35 and arrival is at 15:12. How much time has passed?', '37 minutes', '27 minutes', '47 minutes', '57 minutes', undefined, 'numeracy_measurement', '25 minutes to 15:00 plus 12 minutes = 37.'],
      ['Breathing becomes faster while the person becomes harder to engage. Which conclusion is supported?', 'There is deterioration needing prompt qualified assessment', 'The person is clearly improving', 'One named diagnosis is proven', 'No concern exists without a device reading', 'emergency'],
      ['A route becomes unsafe while a person needs assistance. Which response considers both needs?', 'Reassess the route and arrange appropriate help', 'Use the unsafe route regardless of the hazard', 'Send an untrained bystander into the danger', 'Ignore the new hazard because the task began earlier', 'emergency', 'scene_safety'],
      ['A record contains 0.65 L plus 350 mL. What is the combined volume?', '1,000 mL', '415 mL', '650 mL', '3,565 mL', undefined, 'numeracy_measurement', '650 + 350 = 1,000 mL.'],
      ['Which sentence distinguishes an observation from an unconfirmed cause?', '“New confusion began at 10:20; the cause is not yet established”', '“One change proves every possible diagnosis”', '“The person is confused because they are difficult”', '“No confirmed cause means the change is harmless”'],
      ['A scene update reports a blocked exit and a person becoming less responsive. Which handover preserves both priorities?', 'Report the access hazard and the person’s deterioration', 'Report only the original safe route', 'Report only the person’s clothing', 'Omit both until a diagnosis is confirmed', 'emergency'],
    ]),
  ],
};
