// The four source columns are warmth, considered detail, adventure and balance.
// The builder shuffles them while retaining their existing country-style IDs.
const rounds = [
  ['First Impressions', 'Your first style snapshot', 'The small choices in your day tell their own story.', [
    ['You arrive at a small gathering. What draws you in first?', 'A warm conversation', 'An interesting detail in the room', 'An activity I can join', 'A quiet spot beside someone I know'],
    ['A new neighbour introduces themselves. What feels natural?', 'Invite them to stay and talk', 'Remember a detail they mention', 'Suggest exploring the area together', 'Offer a friendly welcome without pressure'],
    ['Which invitation would you open first?', 'Dinner with a lively group', 'A demonstration by a skilled maker', 'A day out somewhere new', 'A relaxed afternoon with a close friend'],
    ['What makes a place feel welcoming to you?', 'People who include me in the conversation', 'Thoughtful details that show care', 'Space to move and try things', 'A calm atmosphere where I can settle'],
    ['Someone asks what you enjoy. Which answer feels closest?', 'Bringing people together', 'Getting deeply interested in something', 'Finding the next experience', 'Making everyday life feel balanced'],
    ['Which first impression stays with you longest?', 'Someone’s warmth', 'Someone’s quiet attention', 'Someone’s sense of possibility', 'Someone’s reassuring ease'],
    ['You have a free seat beside you. What do you hope happens?', 'An easy conversation begins', 'Someone shares an unusual insight', 'A spontaneous plan takes shape', 'We enjoy comfortable silence'],
  ]],
  ['Your Daily Rhythm', 'Your everyday style', 'Your favourite people may recognise the next answers.', [
    ['There is no rush this morning. What comes first?', 'Breakfast with someone I enjoy', 'A small ritual done with care', 'Fresh air and a change of scene', 'A peaceful start at my own pace'],
    ['A short break appears in your day. How do you use it?', 'Check in with someone', 'Focus on a small personal interest', 'Get outside and move', 'Sit somewhere calm'],
    ['Which kind of routine suits you best?', 'One with regular shared moments', 'One with meaningful little rituals', 'One with room for surprises', 'One that leaves enough breathing space'],
    ['You are choosing a route for a walk. Which appeals most?', 'Past familiar faces and meeting places', 'Past something interesting to examine', 'Along a path I have not tried', 'Through a quiet green space'],
    ['What makes an ordinary weekday feel satisfying?', 'A good conversation', 'Doing one thing with real care', 'Trying something different', 'A comfortable balance of effort and rest'],
    ['An unexpected hour becomes free. Your first instinct is to…', 'Find someone to spend it with', 'Return to a project I care about', 'See what is happening nearby', 'Enjoy having nothing urgent to do'],
    ['Which evening rhythm sounds best?', 'Food and stories around a table', 'Time for a focused hobby', 'An outing that could go anywhere', 'A gentle routine before bed'],
  ]],
  ['People and Connection', 'Your connection snapshot', 'What would a space designed around you look like?', [
    ['A friend has good news. How would you celebrate?', 'Bring people together to share it', 'Prepare a thoughtful personal gesture', 'Suggest a memorable experience', 'Make time for a relaxed conversation'],
    ['Your group is choosing an activity. Which would you suggest?', 'Cooking something together', 'Learning a careful craft', 'Exploring somewhere outdoors', 'A gentle walk and a quiet meal'],
    ['What do you value most in shared time?', 'Warmth and expression', 'Attention and thoughtfulness', 'Playfulness and freedom', 'Ease and mutual space'],
    ['A friend visits after a long time away. What do you plan?', 'A meal with plenty of time to talk', 'Something linked to an interest they mentioned', 'A new place we can discover', 'An unhurried afternoon with no demands'],
    ['Which compliment would feel most like you?', 'You make people feel included', 'You notice what others miss', 'You make life feel full of possibility', 'You make things feel calmer'],
    ['At a group meal, which role do you drift towards?', 'Keeping the conversation flowing', 'Noticing who might need something', 'Suggesting what we could do afterwards', 'Helping everyone feel at ease'],
    ['What kind of friendship moment stays with you?', 'Laughing over a story we all remember', 'A small gesture that showed real understanding', 'An adventure we had not planned', 'Being together without needing to fill the silence'],
  ]],
  ['A Space That Fits', 'Your surroundings speak', 'Comfort and curiosity can pull in different directions.', [
    ['Which room would you choose for a free afternoon?', 'A welcoming room made for conversation', 'A space full of carefully chosen details', 'An open room leading straight outdoors', 'A simple room with a restful atmosphere'],
    ['You can add one thing to a room. What do you choose?', 'A table that brings people together', 'A beautifully made object', 'Something for an active hobby', 'Soft lighting and a comfortable seat'],
    ['What catches your eye at a small market?', 'Something with a story to share', 'An object made with great precision', 'Something I have never tried', 'Something simple I would use every day'],
    ['Which view would you like from a window?', 'A lively square', 'A carefully tended garden', 'A wide coastline', 'A peaceful forest'],
    ['What makes a temporary place feel like yours?', 'Sharing it with good company', 'Arranging a few personal details', 'Using it as a base to explore', 'Finding a comfortable routine'],
    ['You are choosing a keepsake. Which matters most?', 'The people and moments it represents', 'The skill that went into making it', 'The adventure it reminds me of', 'How naturally it fits into daily life'],
    ['How would you describe your ideal surroundings?', 'Full of character and welcome', 'Thoughtfully arranged', 'Open and full of possibilities', 'Calm and easy to live in'],
  ]],
  ['Follow Your Curiosity', 'A curious side appears', 'The next choices bring everyone to the table.', [
    ['You discover an unfamiliar hobby. What makes you try it?', 'I can enjoy it with others', 'I want to understand how it works', 'It looks like a new adventure', 'It could become a relaxing part of life'],
    ['Which workshop would you book?', 'Making a meal to share', 'Learning a precise handcraft', 'Trying an outdoor skill', 'Creating something useful and simple'],
    ['A museum gives you a free hour. Where do you begin?', 'With stories about people’s lives', 'With the finest details of one object', 'With something completely unfamiliar', 'With a quiet area I can enjoy slowly'],
    ['What keeps you interested in a new project?', 'The chance to share it', 'The satisfaction of improving it', 'The surprises along the way', 'How well it fits my own pace'],
    ['Which kind of question do you ask most naturally?', 'Who is part of this story?', 'How was this made?', 'What could we try next?', 'How could this make daily life easier?'],
    ['A guide offers several optional stops. Which do you choose?', 'A place where we can meet local people', 'A place with a detailed tradition to learn', 'A place away from the usual route', 'A quiet place with time to take it in'],
    ['You find something you love. What happens next?', 'I tell someone who might love it too', 'I learn more about its details', 'I look for another experience like it', 'I make room for it in my routine'],
  ]],
  ['Around the Table', 'Your shared moments', 'Your approach to a project reveals another side.', [
    ['What makes a meal memorable?', 'The conversation around it', 'The care in its preparation', 'Trying a flavour I have never known', 'Feeling comfortable and unhurried'],
    ['You are planning a meal for friends. What gets your attention first?', 'Making everyone feel welcome', 'Adding a thoughtful personal touch', 'Trying something new together', 'Keeping it simple enough to enjoy'],
    ['Which place would you choose for a relaxed lunch?', 'A lively place with familiar faces', 'A small place known for careful preparation', 'Somewhere new on an unplanned outing', 'A calm place with a comfortable atmosphere'],
    ['A shared recipe needs one final touch. What do you suggest?', 'Something that makes it feel generous', 'A small detail that brings it together', 'An unexpected flavour to try', 'Keeping what already works well'],
    ['What is your favourite part of hosting?', 'Bringing different people together', 'Remembering what each guest likes', 'Seeing an ordinary evening become an adventure', 'Creating a setting where nobody feels rushed'],
    ['A meal runs longer than planned. How does that feel?', 'Good conversation is worth the time', 'I enjoy noticing how the evening unfolds', 'I wonder where we could go next', 'I am happy if everyone feels comfortable'],
    ['You can choose a food-related experience. Which one?', 'A long meal with stories and laughter', 'Learning a technique from a skilled cook', 'Exploring unfamiliar dishes', 'Making a simple favourite at home'],
  ]],
  ['Make Something Happen', 'Your working style', 'What you choose when nobody is directing you matters too.', [
    ['You begin a small project with friends. What role feels natural?', 'Build a shared sense of excitement', 'Work through the details', 'Get the first experiment moving', 'Keep the plan manageable'],
    ['A project goes well. Which part gives you most satisfaction?', 'The shared feeling of achievement', 'The care visible in the result', 'The new ground we explored', 'The way it fitted around real life'],
    ['You need to explain an idea. How do you begin?', 'Tell a story people can relate to', 'Choose one clear example with useful detail', 'Show what we could try', 'Keep the explanation simple and calm'],
    ['An afternoon of work is yours to arrange. What appeals most?', 'Time to exchange ideas with others', 'A quiet stretch for careful focus', 'A mix of tasks with room to improvise', 'A steady pace with proper breaks'],
    ['What usually draws you into a shared plan?', 'The people involved', 'The chance to do something well', 'The possibility of something new', 'A clear plan that feels sustainable'],
    ['A small obstacle appears. What is your first instinct?', 'Talk it through together', 'Look closely at what caused it', 'Try another route', 'Pause and find the simplest next step'],
    ['Which result would make you proud?', 'Something people enjoyed together', 'Something made with real care', 'Something we had never attempted', 'Something useful that makes life easier'],
  ]],
  ['Time That Is Yours', 'Your free-time signature', 'A change of plan can reveal a fresh preference.', [
    ['A whole afternoon is free. What sounds best?', 'Spend it with people I enjoy', 'Give a favourite interest my full attention', 'Head out without a fixed route', 'Enjoy a peaceful day at home or nearby'],
    ['Which small escape would you choose?', 'A place with warmth and lively conversation', 'A place with art and traditions to explore', 'A place with open paths and new experiences', 'A place with quiet nature and a gentle pace'],
    ['You have one extra day on a trip. What do you do?', 'Return to people or places that welcomed me', 'Explore one subject in more depth', 'Go somewhere we did not plan to visit', 'Slow down and enjoy where I already am'],
    ['Which activity helps a day feel like your own?', 'Sharing something I love', 'Losing myself in a careful task', 'Trying a new route or activity', 'Having time without demands'],
    ['A friend offers to plan your day. What would you ask for?', 'Good company and places to talk', 'Something thoughtful and interesting', 'A surprise with room for adventure', 'A relaxed plan with space between things'],
    ['What do you most enjoy bringing back from a day out?', 'A story about someone I met', 'A new detail or skill I learned', 'A memory of something unexpected', 'A feeling of being refreshed'],
    ['Your ideal free day ends with…', 'One more good conversation', 'A moment to appreciate what I discovered', 'An idea for the next outing', 'A sense of calm and enough rest'],
  ]],
  ['When Plans Change', 'A different side of you', 'A few final instincts will complete your match.', [
    ['Rain changes an outdoor plan. What would you suggest?', 'Find somewhere welcoming to gather', 'Try an interesting indoor activity', 'Turn it into a different adventure', 'Enjoy a slower day without pressure'],
    ['A familiar place changes. What do you notice first?', 'How people respond to it', 'The new details', 'The new possibilities', 'Whether it still feels comfortable'],
    ['Someone suggests doing things differently. What interests you most?', 'How it could bring people together', 'The thinking behind the idea', 'The chance to experiment', 'Whether it makes things simpler'],
    ['You have to choose at the last minute. What guides you?', 'What would create a good shared moment', 'The detail that feels most meaningful', 'The option I have not tried before', 'What feels calm and manageable'],
    ['A day takes an unexpected turn. What helps you enjoy it?', 'The company I am with', 'Finding something interesting in it', 'Treating it as a new experience', 'Letting go of unnecessary demands'],
    ['A plan has too many competing ideas. What do you contribute?', 'A conversation that brings everyone in', 'A careful comparison of the details', 'A suggestion to test something quickly', 'A simpler plan with room to breathe'],
    ['Which kind of change would you welcome most?', 'More meaningful time with people', 'More room to explore an interest deeply', 'More chances to try new things', 'A better balance in everyday life'],
  ]],
  ['Your Final Instincts', 'Your country match is ready', '', [
    ['Which invitation feels most like your next chapter?', 'Come and share the moment', 'Take a closer look', 'See where this leads', 'Make yourself comfortable'],
    ['Choose the memory you would most like to create.', 'A table full of people laughing', 'A small discovery that stays with me', 'A day that went somewhere unexpected', 'A peaceful moment I can return to'],
    ['What would you want more of in an ordinary week?', 'Connection', 'Meaningful attention', 'Possibility', 'Balance'],
    ['Which kind of place could you return to again and again?', 'Somewhere I feel warmly included', 'Somewhere that rewards a closer look', 'Somewhere with another path to explore', 'Somewhere I can slow down'],
    ['Which quality would you want a visitor to notice about your life?', 'Its warmth', 'Its thoughtfulness', 'Its openness', 'Its ease'],
    ['A day has gone exactly your way. What mattered most?', 'I felt connected to people', 'I gave something my full attention', 'I discovered something new', 'I had room to enjoy the pace'],
    ['Choose the phrase that feels most like you today.', 'Life is richer when it is shared', 'Small details give life meaning', 'There is always something new to discover', 'Enough space makes the good things clearer'],
  ]],
];

export default {
  summary: 'Explore the preferences behind your everyday choices and discover your country-inspired personality match.',
  about: 'Explore how you connect with people, arrange your day, follow your curiosity and respond when plans change. Choose what feels natural, without trying to earn a particular result.\n\nEach checkpoint shows the country-inspired style leading that topic. Your final match combines all your choices, with an optional preference breakdown. A short rewarded ad opens the quiz, with another opportunity at each checkpoint and for the optional breakdown. Your progress is saved on this device.\n\nThe questions are authored for this entertainment challenge. Italy, Japan, Australia and Sweden name playful lifestyle archetypes; the result does not determine nationality, ancestry, cultural identity or where anyone should live.',
  rounds: rounds.map(([title, checkpoint, teaser, questions]) => ({title, checkpoint, teaser, questions, feedback: 'This side of you leans towards: {profile}.'})),
};
