export const additionalTitles = {
  personality: {
    fr: 'Premières impressions|Ton rythme quotidien|Les liens avec les autres|Un espace à ton image|Suivre ta curiosité|Autour de la table|Faire avancer les choses|Du temps pour toi|Quand les plans changent|Tes derniers réflexes',
    de: 'Erste Eindrücke|Dein Tagesrhythmus|Menschen und Nähe|Ein Ort, der zu dir passt|Deiner Neugier folgen|Gemeinsam am Tisch|Etwas bewegen|Zeit für dich|Wenn Pläne sich ändern|Dein letzter Impuls',
    it: 'Prime impressioni|Il tuo ritmo quotidiano|Persone e legami|Uno spazio che ti somiglia|Segui la curiosità|Intorno alla tavola|Far succedere le cose|Il tempo per te|Quando i piani cambiano|Gli ultimi istinti',
    nl: 'Eerste indrukken|Je dagelijkse ritme|Mensen en verbinding|Een plek die bij je past|Volg je nieuwsgierigheid|Samen aan tafel|Iets in beweging brengen|Tijd voor jezelf|Als plannen veranderen|Je laatste gevoel',
    es: 'Primeras impresiones|Tu ritmo diario|Personas y vínculos|Un espacio a tu medida|Sigue tu curiosidad|Alrededor de la mesa|Poner las cosas en marcha|Tiempo para ti|Cuando cambian los planes|Tus últimos instintos',
    pt: 'Primeiras impressões|O ritmo do dia a dia|Pessoas e relações|Um espaço à sua medida|Seguir a curiosidade|À volta da mesa|Fazer acontecer|Tempo para si|Quando os planos mudam|Os últimos instintos',
    ar: 'الانطباعات الأولى|إيقاع يومك|الأشخاص والروابط|مساحة تناسبك|اتبع فضولك|حول المائدة|تحويل الأفكار إلى واقع|وقت لنفسك|عندما تتغير الخطط|اختياراتك الأخيرة',
  },
  harvard: {
    fr: 'Comprendre la situation|Les nombres en pratique|Évaluer les preuves|Les mots qui comptent|Lire les données|Choisir les priorités|Respecter les règles|Comparer les compromis|Relier les résultats|Le dernier cas',
    de: 'Die Situation verstehen|Zahlen in der Praxis|Belege prüfen|Auf die Worte kommt es an|Daten lesen|Prioritäten setzen|Innerhalb der Regeln|Vor- und Nachteile abwägen|Ergebnisse verbinden|Der letzte Fall',
    it: 'Capire la situazione|I numeri in pratica|Valutare le prove|Le parole contano|Leggere i dati|Scegliere le priorità|Rispettare le regole|Confrontare i compromessi|Collegare i risultati|L’ultimo caso',
    nl: 'Begrijp de situatie|Getallen in de praktijk|Bewijs beoordelen|Woorden doen ertoe|Gegevens lezen|Prioriteiten kiezen|Binnen de regels|Voor- en nadelen afwegen|Bevindingen verbinden|De laatste casus',
    es: 'Entender la situación|Números en la práctica|Evaluar las pruebas|Las palabras importan|Leer los datos|Elegir prioridades|Respetar las reglas|Comparar ventajas y costes|Relacionar los resultados|El último caso',
    pt: 'Compreender a situação|Números na prática|Avaliar as provas|As palavras importam|Ler os dados|Escolher prioridades|Respeitar as regras|Pesar vantagens e custos|Relacionar os resultados|O último caso',
    ar: 'افهم الموقف|الأرقام في الواقع|قيّم الأدلة|الكلمات تصنع فرقًا|اقرأ البيانات|اختر الأولويات|ضمن القواعد|وازن بين الخيارات|اربط النتائج|الحالة الأخيرة',
  },
  oxford: {
    fr: 'Les liens entre les mots|Le sens des détails|Suivre les règles|Quantités et proportions|Les suppositions cachées|Que manque-t-il ?|Mettre les indices en ordre|Rotations et points de vue|Les arguments à l’épreuve|Le dernier défi',
    de: 'Wörter verknüpfen|Bedeutung im Detail|Den Regeln folgen|Mengen und Verhältnisse|Verborgene Annahmen|Was fehlt?|Hinweise ordnen|Drehungen und Blickwinkel|Argumente auf dem Prüfstand|Die letzte Denkaufgabe',
    it: 'Relazioni tra parole|Il significato nei dettagli|Seguire le regole|Quantità e proporzioni|Le ipotesi nascoste|Che cosa manca?|Mettere gli indizi in ordine|Rotazioni e punti di vista|Argomenti alla prova|L’ultima sfida',
    nl: 'Verbanden tussen woorden|Betekenis in de details|Volg de regels|Hoeveelheden en verhoudingen|Verborgen aannames|Wat ontbreekt?|Zet de aanwijzingen op volgorde|Draaien en gezichtspunten|Argumenten onderzoeken|De laatste redeneeruitdaging',
    es: 'Relaciones entre palabras|El significado en los detalles|Seguir las reglas|Cantidades y proporciones|Los supuestos ocultos|¿Qué falta?|Ordenar las pistas|Giros y puntos de vista|Argumentos a prueba|El último reto',
    pt: 'Relações entre palavras|O significado nos detalhes|Seguir as regras|Quantidades e proporções|As suposições escondidas|O que falta?|Ordenar as pistas|Rotações e pontos de vista|Argumentos à prova|O último desafio',
    ar: 'علاقات بين الكلمات|المعنى في التفاصيل|اتبع القواعد|الكميات والنسب|الافتراضات الخفية|ما الذي ينقص؟|رتّب الأدلة|الدوران وزوايا النظر|الحجج تحت الاختبار|تحدي الاستدلال الأخير',
  },
  cambridge: {
    fr: 'Trouver la règle|Mesurer le changement|Construire un test équitable|Lire les résultats|Espace et mouvement|Les machines à calculer|Causes et preuves|Taux et proportions|Mettre le modèle à l’épreuve|Le dernier système',
    de: 'Das Muster finden|Veränderungen messen|Einen fairen Versuch planen|Ergebnisse lesen|Raum und Bewegung|Rechenmaschinen|Ursachen und Belege|Raten und Verhältnisse|Das Modell prüfen|Das letzte System',
    it: 'Trovare la regola|Misurare il cambiamento|Progettare un confronto equo|Leggere i risultati|Spazio e movimento|Le macchine di calcolo|Cause e prove|Tassi e proporzioni|Mettere alla prova il modello|L’ultimo sistema',
    nl: 'Vind het patroon|Meet de verandering|Een eerlijke proef opzetten|Resultaten lezen|Ruimte en beweging|Rekenmachines|Oorzaak en bewijs|Snelheden en verhoudingen|Het model toetsen|Het laatste systeem',
    es: 'Encontrar el patrón|Medir el cambio|Diseñar una prueba justa|Leer los resultados|Espacio y movimiento|Las máquinas de cálculo|Causas y pruebas|Tasas y proporciones|Poner el modelo a prueba|El último sistema',
    pt: 'Encontrar o padrão|Medir a mudança|Preparar uma comparação justa|Ler os resultados|Espaço e movimento|Máquinas de cálculo|Causas e provas|Taxas e proporções|Pôr o modelo à prova|O último sistema',
    ar: 'اكتشف النمط|قِس التغيّر|صمّم تجربة عادلة|اقرأ النتائج|المكان والحركة|آلات الحساب|الأسباب والأدلة|المعدلات والنسب|اختبر النموذج|النظام الأخير',
  },
};

export const additionalTeasers = {
  fr: {
    personality: 'Tes petites habitudes racontent leur propre histoire.|Tes proches reconnaîtront peut-être les prochaines réponses.|À quoi ressemble un espace qui te correspond ?|Confort et curiosité ne te mènent pas toujours au même endroit.|Les prochains choix se font autour de la table.|Ta façon d’aborder un projet révèle une autre facette.|Que choisis-tu quand ton temps t’appartient ?|Un changement de programme peut révéler une préférence.|Quelques derniers réflexes vont compléter ton portrait.',
    harvard: 'Un petit calcul peut changer le meilleur choix.|Une histoire convaincante a aussi besoin de preuves.|Les mots peuvent compter autant que les nombres.|Que montrent réellement les chiffres ?|Quel choix répond à l’objectif annoncé ?|Quelques règles suffisent à réduire les possibilités.|Chaque option intéressante implique aussi un renoncement.|Réunissez les nombres et les preuves.|Les derniers cas croisent règles, quantités et jugement.',
    oxford: 'Un mot différent peut changer toute l’affirmation.|Suivre une règle sans ajouter de supposition : le défi commence.|Les nombres demandent une autre forme de précision.|De quelle supposition l’argument a-t-il besoin ?|Parfois, la réponse tient à ce qu’on ignore encore.|Quelques indices peuvent révéler un ordre précis.|Appliquez maintenant cette précision à l’espace.|Quel argument résiste à un examen attentif ?|Les derniers indices mêlent mots, logique et nombres.',
    cambridge: 'Place au sens des mesures.|Deux résultats différents ne suffisent pas à faire une comparaison équitable.|Que montrent les résultats avant toute explication ?|Tournez, réfléchissez les formes et suivez le mouvement.|Une machine simple peut cacher une règle en plusieurs étapes.|Un résultat soutient-il une explication ou la prouve-t-il ?|Les proportions révèlent ce que les totaux cachent.|Le modèle correspond-il aux mesures réelles ?|Les derniers problèmes combinent plusieurs règles.',
  },
  de: {
    personality: 'Deine kleinen Alltagsentscheidungen erzählen ihre eigene Geschichte.|Vertraute Menschen könnten dich in den nächsten Antworten erkennen.|Wie sieht ein Ort aus, der zu dir passt?|Komfort und Neugier führen nicht immer in dieselbe Richtung.|Die nächsten Entscheidungen bringen alle an einen Tisch.|Deine Herangehensweise an ein Projekt zeigt eine weitere Seite.|Was wählst du, wenn du ganz frei entscheiden kannst?|Ein geänderter Plan kann eine neue Vorliebe zeigen.|Ein paar letzte Impulse vervollständigen dein Bild.',
    harvard: 'Eine kleine Rechnung kann die beste Wahl verändern.|Auch eine überzeugende Geschichte braucht Belege.|Worte können ebenso wichtig sein wie Zahlen.|Was zeigen die Zahlen tatsächlich?|Welche Wahl erfüllt das genannte Ziel?|Wenige Regeln können die Möglichkeiten stark einschränken.|Jede attraktive Option hat auch ihren Preis.|Zahlen und Belege zusammenbringen.|Die letzten Fälle verbinden Regeln, Mengen und Urteilsvermögen.',
    oxford: 'Ein anderes Wort kann die ganze Aussage verändern.|Einer Regel folgen, ohne etwas hinzuzudichten.|Zahlen verlangen eine andere Art von Genauigkeit.|Welche Annahme braucht das Argument?|Manchmal ist entscheidend, was noch unbekannt ist.|Wenige Hinweise können eine genaue Reihenfolge verraten.|Jetzt geht es mit derselben Genauigkeit um den Raum.|Welches Argument hält einer genauen Prüfung stand?|Die letzten Hinweise verbinden Sprache, Logik und Zahlen.',
    cambridge: 'Als Nächstes zählen die Messwerte.|Zwei unterschiedliche Ergebnisse ergeben noch keinen fairen Vergleich.|Was zeigen die Ergebnisse, bevor wir sie erklären?|Drehen, spiegeln und der Bewegung folgen.|Eine einfache Maschine kann mehrere Rechenschritte verbergen.|Stützt ein Ergebnis eine Erklärung oder beweist es sie?|Verhältnisse zeigen, was Gesamtsummen verbergen.|Wie gut passt das Modell zu den Messwerten?|Die letzten Aufgaben kombinieren mehrere Regeln.',
  },
  it: {
    personality: 'Le piccole scelte quotidiane raccontano la loro storia.|Le persone vicine potrebbero riconoscere le prossime risposte.|Come sarebbe uno spazio pensato per te?|Comodità e curiosità possono portarti in direzioni diverse.|Le prossime scelte riuniscono tutti a tavola.|Il tuo modo di affrontare un progetto rivela un altro lato.|Che cosa scegli quando il tempo è tutto tuo?|Un cambio di programma può svelare una preferenza.|Gli ultimi istinti completeranno il tuo ritratto.',
    harvard: 'Un piccolo calcolo può cambiare la scelta migliore.|Anche una storia convincente ha bisogno di prove.|Le parole possono contare quanto i numeri.|Che cosa mostrano davvero i dati?|Quale scelta risponde all’obiettivo dichiarato?|Poche regole possono restringere molto le possibilità.|Ogni opzione interessante comporta anche una rinuncia.|Metti insieme numeri e prove.|Gli ultimi casi combinano regole, quantità e giudizio.',
    oxford: 'Una parola diversa può cambiare tutta l’affermazione.|Sai seguire una regola senza aggiungere supposizioni?|I numeri richiedono un altro tipo di precisione.|Di quale ipotesi ha bisogno l’argomento?|A volte conta capire che cosa ancora non sappiamo.|Pochi indizi possono rivelare un ordine esatto.|Ora applica la stessa precisione allo spazio.|Quale argomento resiste a un esame attento?|Gli ultimi indizi uniscono parole, logica e numeri.',
    cambridge: 'Ora dai un significato alle misure.|Due risultati diversi non bastano per un confronto equo.|Che cosa mostrano i risultati prima di spiegarli?|Ruota, rifletti le forme e segui il movimento.|Una macchina semplice può nascondere più passaggi.|Un risultato sostiene una spiegazione o la dimostra?|Le proporzioni rivelano ciò che i totali nascondono.|Quanto corrisponde il modello alle misure reali?|Gli ultimi problemi combinano più regole.',
  },
  nl: {
    personality: 'Je kleine dagelijkse keuzes vertellen hun eigen verhaal.|Mensen om je heen herkennen misschien de volgende antwoorden.|Hoe ziet een plek eruit die helemaal bij je past?|Gemak en nieuwsgierigheid kunnen je verschillende kanten op trekken.|De volgende keuzes brengen iedereen aan tafel.|Je aanpak van een project laat nog een kant van je zien.|Wat kies je als je tijd helemaal van jou is?|Een gewijzigd plan kan een nieuwe voorkeur laten zien.|Een paar laatste keuzes maken je profiel compleet.',
    harvard: 'Een kleine berekening kan de beste keuze veranderen.|Ook een overtuigend verhaal heeft bewijs nodig.|Woorden kunnen net zo belangrijk zijn als getallen.|Wat laten de cijfers echt zien?|Welke keuze past bij het genoemde doel?|Een paar regels kunnen veel opties uitsluiten.|Bij elke aantrekkelijke optie geef je ook iets op.|Breng de getallen en het bewijs bij elkaar.|De laatste casussen combineren regels, hoeveelheden en afwegingen.',
    oxford: 'Een ander woord kan de hele bewering veranderen.|Kun je een regel volgen zonder iets aan te nemen?|Getallen vragen om een ander soort precisie.|Welke aanname heeft het argument nodig?|Soms draait het om wat we nog niet kunnen weten.|Een paar aanwijzingen kunnen een exacte volgorde geven.|Gebruik dezelfde precisie nu voor ruimte.|Welk argument blijft overeind als je het nauwkeurig onderzoekt?|De laatste aanwijzingen combineren taal, logica en getallen.',
    cambridge: 'Geef nu betekenis aan de metingen.|Twee verschillende uitkomsten maken nog geen eerlijke vergelijking.|Wat tonen de resultaten voordat we ze verklaren?|Draai, spiegel en volg de beweging.|Een eenvoudige machine kan meerdere stappen verbergen.|Ondersteunt een resultaat de verklaring of bewijst het die?|Verhoudingen tonen wat ruwe totalen verbergen.|Hoe goed past het model bij de metingen?|De laatste problemen combineren meerdere regels.',
  },
  es: {
    personality: 'Tus pequeñas decisiones diarias cuentan su propia historia.|Las personas cercanas quizá reconozcan las próximas respuestas.|¿Cómo sería un espacio diseñado para ti?|La comodidad y la curiosidad pueden llevarte por caminos distintos.|Las próximas decisiones reúnen a todos alrededor de la mesa.|Tu forma de abordar un proyecto revela otra faceta.|¿Qué eliges cuando el tiempo es todo tuyo?|Un cambio de planes puede revelar una preferencia.|Unos últimos instintos completarán tu retrato.',
    harvard: 'Un pequeño cálculo puede cambiar la mejor elección.|Una historia convincente también necesita pruebas.|Las palabras pueden importar tanto como los números.|¿Qué muestran realmente los datos?|¿Qué elección cumple el objetivo planteado?|Unas pocas reglas pueden reducir mucho las opciones.|Cada opción atractiva también implica renunciar a algo.|Reúne los números y las pruebas.|Los últimos casos combinan reglas, cantidades y criterio.',
    oxford: 'Una palabra distinta puede cambiar toda la afirmación.|¿Puedes seguir una regla sin añadir suposiciones?|Los números exigen otra forma de precisión.|¿Qué supuesto necesita el argumento?|A veces importa saber qué es lo que aún ignoramos.|Unas pocas pistas pueden revelar un orden exacto.|Aplica ahora esa precisión al espacio.|¿Qué argumento resiste un examen cuidadoso?|Las últimas pistas combinan lenguaje, lógica y números.',
    cambridge: 'Ahora interpreta las mediciones.|Dos resultados distintos no bastan para una comparación justa.|¿Qué muestran los resultados antes de explicarlos?|Gira, refleja las formas y sigue el movimiento.|Una máquina sencilla puede esconder varios pasos.|¿Un resultado apoya la explicación o la demuestra?|Las proporciones revelan lo que ocultan los totales.|¿Hasta qué punto coincide el modelo con las mediciones?|Los últimos problemas combinan varias reglas.',
  },
  pt: {
    personality: 'As pequenas escolhas diárias contam a sua própria história.|As pessoas próximas talvez reconheçam as respostas seguintes.|Como seria um espaço pensado à sua medida?|O conforto e a curiosidade podem apontar caminhos diferentes.|As próximas escolhas juntam todos à mesa.|A forma de abordar um projeto revela outro lado.|O que escolhe quando o tempo é todo seu?|Uma mudança de planos pode revelar uma preferência.|Alguns instintos finais vão completar o retrato.',
    harvard: 'Um pequeno cálculo pode mudar a melhor escolha.|Uma história convincente também precisa de provas.|As palavras podem contar tanto como os números.|O que mostram realmente os dados?|Que escolha cumpre o objetivo apresentado?|Poucas regras podem reduzir bastante as opções.|Cada opção atraente também implica uma renúncia.|Reúna os números e as provas.|Os últimos casos combinam regras, quantidades e decisões.',
    oxford: 'Uma palavra diferente pode mudar toda a afirmação.|Consegue seguir uma regra sem acrescentar suposições?|Os números exigem outro tipo de precisão.|De que suposição precisa o argumento?|Às vezes, importa perceber o que ainda não sabemos.|Poucas pistas podem revelar uma ordem exata.|Aplique agora essa precisão ao espaço.|Que argumento resiste a uma análise cuidadosa?|As últimas pistas combinam linguagem, lógica e números.',
    cambridge: 'Agora, interprete as medições.|Dois resultados diferentes não bastam para uma comparação justa.|O que mostram os resultados antes de os explicar?|Rode, espelhe as formas e acompanhe o movimento.|Uma máquina simples pode esconder vários passos.|Um resultado apoia a explicação ou comprova-a?|As proporções revelam o que os totais escondem.|Até que ponto corresponde o modelo às medições?|Os últimos problemas combinam várias regras.',
  },
  ar: {
    personality: 'اختياراتك اليومية الصغيرة تروي حكايتها.|قد يتعرّف المقرّبون منك على الإجابات التالية.|كيف تبدو مساحة صُمّمت لتناسبك؟|قد تقودك الراحة والفضول في اتجاهين مختلفين.|الاختيارات التالية تجمع الجميع حول المائدة.|طريقتك في تنفيذ مشروع تكشف جانبًا آخر منك.|ماذا تختار عندما يكون الوقت ملكك؟|قد يكشف تغيّر الخطط عن تفضيل جديد.|اختيارات أخيرة ستكمل صورتك.',
    harvard: 'حساب بسيط قد يغيّر الاختيار الأفضل.|حتى الرواية المقنعة تحتاج إلى أدلة.|قد تكون الكلمات بأهمية الأرقام.|ماذا تُظهر الأرقام فعلًا؟|أي اختيار يحقق الهدف المذكور؟|قواعد قليلة قد تقلّص الخيارات كثيرًا.|كل خيار جذاب قد يتطلب التنازل عن شيء آخر.|اجمع بين الأرقام والأدلة.|الحالات الأخيرة تجمع القواعد والكميات وحسن التقدير.',
    oxford: 'تغيير كلمة قد يغيّر معنى الادعاء كله.|هل تتبع القاعدة دون إضافة افتراض؟|الأرقام تتطلب نوعًا آخر من الدقة.|على أي افتراض تقوم الحجة؟|أحيانًا تبدأ الإجابة بمعرفة ما نجهله.|أدلة قليلة قد تكشف ترتيبًا دقيقًا.|استخدم الدقة نفسها في التصور المكاني.|أي حجة تصمد أمام الفحص؟|الأدلة الأخيرة تجمع اللغة والمنطق والأرقام.',
    cambridge: 'حان وقت فهم القياسات.|اختلاف نتيجتين لا يكفي لجعل المقارنة عادلة.|ماذا تُظهر النتائج قبل أن نفسّرها؟|دوّر الأشكال واعكسها وتتبع الحركة.|قد تخفي آلة بسيطة عدة خطوات.|هل تدعم النتيجة التفسير أم تثبته؟|تكشف النسب ما قد تخفيه المجاميع.|إلى أي حد يوافق النموذج القياسات الفعلية؟|المسائل الأخيرة تجمع أكثر من قاعدة.',
  },
};
