// Police-specific observation and evidence terminology.
// Columns: fr, de, it, nl, es, pt, ar.
const phrases = {
  'At a reported incident, why first assess immediate dangers?': [null,null,null,null,null,'Qual é o motivo de avaliar primeiro os perigos imediatos num incidente comunicado?',null],
  'To establish guilt from the scene alone': [null,'Um allein anhand der Situation am Ort des Geschehens Schuld festzustellen',null,null,'Para determinar la culpabilidad solo por la situación en el lugar','Para estabelecer a culpa apenas com base no local do incidente',null],
  'To avoid gathering any information': [null,null,null,null,null,'Para evitar reunir qualquer informação',null],
  'To guarantee no assistance is needed': [null,null,'Per garantire che non serva alcuna assistenza','Om te garanderen dat er geen hulp nodig is','Para garantizar que no se necesita ayuda',null,null],
  'Two witnesses are discussing their memories together. What risk should an investigator recognise?': [null,null,null,null,null,'Duas testemunhas conversam sobre o que recordam de um acontecimento. Que risco deve um investigador reconhecer?',null],
  'Their memories automatically become independent': ['Leurs souvenirs deviennent automatiquement indépendants',null,null,null,null,null,null],
  'To avoid identifying who handled it': [null,'Um nicht feststellen zu müssen, wer den Gegenstand gehandhabt hat',null,'Om niet te hoeven vaststellen wie het voorwerp in handen heeft gehad',null,'Para evitar identificar quem manuseou o objeto','لتجنّب تحديد من تعامل مع العنصر'],
  'To make the item heavier': ['Pour rendre l’objet plus lourd',null,null,null,null,null,null],
  'What does chain of custody document?': ['Que documente la chaîne de traçabilité des éléments de preuve ?','Was dokumentiert die Nachverfolgung von Beweismitteln (Chain of Custody)?',null,'Wat documenteert de bewijsketen (chain of custody)?',null,null,'ما الذي توثّقه سلسلة حيازة الأدلة؟'],
  'The handling and transfer of an item of evidence': [null,'Den Umgang mit einem Beweisstück und seine Weitergabe',null,null,null,'O tratamento e a transferência de um elemento de prova',null],
  'A person is distressed and struggling to follow questions. What can help?': [null,null,null,null,null,'Uma pessoa está angustiada e tem dificuldade em acompanhar as perguntas. O que pode ajudar?',null],
  'Treating distress as proof of guilt': [null,'Die Verzweiflung als Schuldbeweis behandeln',null,'Van streek zijn opvatten als bewijs van schuld',null,null,null],
  'Why avoid announcing an unverified claim as an established fact?': [null,null,null,null,null,'Qual é o problema de apresentar uma afirmação não verificada como informação comprovada?',null],
  'Unverified claims are always correct': [null,null,null,null,null,'Afirmações não verificadas estão sempre corretas',null],
  'Only written claims can cause confusion': [null,'Nur schriftliche Behauptungen können Verwirrung stiften','Solo le affermazioni scritte possono creare confusione',null,'Solo las afirmaciones escritas pueden causar confusión','Apenas as afirmações por escrito podem causar confusão','الادعاءات المكتوبة وحدها قد تسبب الالتباس'],
  'Confidence turns a claim into proof': ['L’assurance transforme une affirmation en preuve','Selbstsicherheit macht eine Behauptung zum Beweis','La sicurezza di chi parla trasforma un’affermazione in una prova','Zelfverzekerdheid verandert een bewering in bewijs',null,null,'الثقة بالنفس تحوّل الادعاء إلى دليل'],
  'Many vehicles may share that colour': [null,null,null,null,null,'Muitos veículos podem ter essa cor',null],
  'No further detail can ever help': [null,null,null,null,'Ningún detalle adicional puede ayudar en ningún caso','Nenhum detalhe adicional pode ajudar em caso algum','لا يمكن لأي تفصيل إضافي أن يفيد في أي حال'],
  'The report proves who was driving': [null,null,null,null,null,'O relatório comprova quem conduzia',null],
  'A note says the person turned left while facing east. Which direction did they then face?': ['Une note indique qu’une personne regardait vers l’est et a tourné à gauche. Dans quelle direction regardait-elle ensuite ?','Laut einer Notiz schaute eine Person nach Osten und drehte sich dann nach links. In welche Richtung blickte sie danach?','Una nota indica che una persona era rivolta verso est e ha girato a sinistra. In quale direzione era rivolta dopo?','Volgens een notitie keek iemand naar het oosten en draaide toen naar links. In welke richting keek die persoon daarna?','Una nota indica que una persona miraba hacia el este y giró a la izquierda. ¿Hacia qué dirección miraba después?',null,'تذكر ملاحظة أن شخصًا كان يتجه بوجهه شرقًا ثم استدار يسارًا. إلى أي اتجاه أصبح وجهه؟'],
  'A receipt is timed 14:10; a verified entry record is timed 14:35 on the same clock. Which happened first?': ['Un reçu indique 14 h 10 et un relevé d’entrée vérifié indique 14 h 35. Les deux heures proviennent de la même horloge. Qu’est-ce qui s’est passé en premier ?','Auf einer Quittung steht 14:10 Uhr. Ein überprüfter Zutrittsnachweis nennt 14:35 Uhr. Beide Zeiten stammen von derselben Uhr. Was geschah zuerst?','Una ricevuta riporta le 14:10 e un ingresso verificato è registrato alle 14:35. I due orari provengono dallo stesso orologio. Quale evento è avvenuto prima?','Een ontvangstbewijs vermeldt 14.10 uur en een gecontroleerde toegangsregistratie vermeldt 14.35 uur. Beide tijden komen van dezelfde klok. Wat gebeurde eerst?','Un recibo indica las 14:10 y un registro de entrada verificado indica las 14:35. Ambas horas proceden del mismo reloj. ¿Qué ocurrió primero?',null,'يشير إيصال إلى الساعة 14:10، ويشير سجل دخول تم التحقق منه إلى الساعة 14:35. التوقيتان من الساعة نفسها. أي الحدثين وقع أولًا؟'],
  'The entry event': ['L’entrée consignée dans le registre','Der dokumentierte Zutritt','L’ingresso registrato','De geregistreerde binnenkomst','La entrada registrada','A entrada documentada','الدخول المدوّن في السجل'],
  'The receipt event': ['L’opération indiquée sur le reçu','Der Vorgang auf der Quittung','L’evento indicato sulla ricevuta','De gebeurtenis op het ontvangstbewijs','El hecho indicado en el recibo',null,'الحدث المدوّن في الإيصال'],
  'The times cannot be ordered': ['On ne peut pas déterminer l’ordre chronologique','Die Zeiten lassen sich nicht chronologisch ordnen',null,'De tijden kunnen niet in volgorde worden gezet',null,null,null],
  'A location is 2 blocks north and then 1 block west of a starting point. In which general direction is it?': [null,null,null,null,null,null,'يقع مكان على بعد مربعين سكنيين شمالًا ثم مربع سكني واحد غربًا من نقطة البداية. في أي اتجاه عام يقع؟'],
  'Northeast': [null,null,null,null,null,null,'الشمال الشرقي'],
  'A record describes a blue jacket and black bag. Which description changes only the bag?': [null,null,null,'Een document beschrijft een blauwe jas en een zwarte tas. Welke beschrijving verandert alleen de tas?','Un registro describe una chaqueta azul y un bolso negro. ¿Qué descripción cambia solo el bolso?',null,null],
  'Blue jacket and red bag': [null,null,null,'Blauwe jas en rode tas',null,null,null],
  'Red jacket and red bag': [null,null,null,null,null,'Casaco vermelho e bolsa vermelha',null],
  'Red jacket and black bag': [null,null,null,null,null,'Casaco vermelho e bolsa preta',null],
  'A camera clock is known to be 3 minutes slow. It displays 12:27. What is the actual time?': ['L’horloge d’une caméra retarde de 3 minutes. Elle affiche 12 h 27. Quelle heure est-il réellement ?','Die Uhr einer Kamera geht 3 Minuten nach. Sie zeigt 12:27 Uhr an. Wie spät ist es tatsächlich?','L’orologio di una videocamera è indietro di 3 minuti. Segna le 12:27. Qual è l’ora reale?','Een cameraklok loopt 3 minuten achter en toont 12:27. Hoe laat is het werkelijk?',null,null,'ساعة كاميرا متأخرة بمقدار 3 دقائق، وهي تعرض 12:27. ما الوقت الحقيقي؟'],
  'Keep only evidence that agrees': [null,'Nur Beweise behalten, die die Theorie stützen',null,'Bewaar alleen bewijs dat de theorie ondersteunt','Conservar solo las pruebas que apoyan la teoría','Manter apenas as provas que apoiam a teoria','احتفظ فقط بالأدلة التي تدعم النظرية'],
  'Why should questions avoid assuming facts that have not been established?': [null,null,null,'Waarom mogen vragen niet uitgaan van feiten die nog niet zijn vastgesteld?',null,'Qual é o problema de formular perguntas que pressupõem algo ainda não comprovado?',null],
  'The wording can influence the answer': [null,null,null,null,null,'A formulação pode influenciar a resposta',null],
  'A crowd gives conflicting descriptions. What is a useful next step?': [null,null,null,null,null,'Várias pessoas dão descrições contraditórias. Qual é o próximo passo útil?',null],
  'Choose the most repeated story as proven': ['Considérer le récit le plus répété comme prouvé','Die am häufigsten wiederholte Darstellung als bewiesen ansehen','Considerare dimostrata la versione più ripetuta','Beschouw het vaakst vertelde verhaal als bewezen','Considerar probada la historia más repetida','Tratar a versão mais repetida como comprovada','اعتبر الرواية الأكثر تكرارًا ثابتة'],
  'Observed actions, location and time': [null,null,'Azioni osservate, luogo e ora',null,null,null,'الأفعال التي لوحظت والمكان والوقت'],
  'A guessed personality type': [null,null,null,null,null,'Um tipo de personalidade presumido','نوع شخصية مفترض'],
  'A conclusion based only on clothing': [null,null,null,null,null,null,'استنتاج مبني على الملابس وحدها'],
  'Investigative aims do not remove the duty to respect human dignity': [null,'Ermittlungsziele heben die Pflicht zur Achtung der Menschenwürde nicht auf',null,null,null,null,'أهداف التحقيق لا تلغي واجب احترام كرامة الإنسان'],
  'A decision must follow a specified procedure. What should uncertainty trigger?': ['Une décision doit respecter une procédure précise. Quelle réaction est appropriée si un point n’est pas clair ?','Eine Entscheidung muss einem festgelegten Verfahren folgen. Was ist bei Unklarheiten angebracht?','Una decisione deve seguire una procedura specifica. Come è opportuno reagire in caso di dubbi?','Een besluit moet een vastgestelde procedure volgen. Wat is de juiste reactie bij onduidelijkheid?','Una decisión debe seguir un procedimiento específico. ¿Cómo conviene actuar si hay dudas?','Uma decisão deve seguir um procedimento específico. Como proceder em caso de dúvida?',null],
  'Clarification through the appropriate authority or guidance': ['Demander des précisions à l’autorité compétente ou consulter les consignes applicables','Klärung durch die zuständige Stelle oder anhand der geltenden Vorgaben','Chiedere chiarimenti all’autorità competente o consultare le indicazioni pertinenti','Opheldering vragen bij de bevoegde instantie of de geldende richtlijnen raadplegen','Pedir aclaraciones a la autoridad competente o consultar las instrucciones pertinentes','Pedir esclarecimentos à entidade competente ou consultar as orientações aplicáveis','طلب توضيح من الجهة المختصة أو الرجوع إلى الإرشادات المناسبة'],
  'A hidden shortcut': ['Un contournement discret de la procédure','Ein heimliches Umgehen des Verfahrens',null,'Een verborgen manier om de procedure te omzeilen',null,null,null],
  'To make an error impossible': [null,null,null,null,null,null,'لجعل ارتكاب أي خطأ مستحيلًا'],
  'To guarantee the decision can never be questioned': [null,null,null,null,null,null,'لضمان ألا يمكن التشكيك في القرار أبدًا'],
  'THE POLICE OFFICER APTITUDE TEST': [null,null,'IL TEST ATTITUDINALE PER LA POLIZIA',null,null,null,null],
  'Explore observation and investigative judgement through clues, practical situations and fresh challenges.': ['Explorez l’observation et le raisonnement d’enquête à travers des indices, des situations pratiques et de nouveaux défis.','Erkunden Sie Beobachtungsgabe und Urteilsvermögen bei Ermittlungen anhand von Hinweisen, praktischen Situationen und neuen Herausforderungen.','Esplora l’osservazione e il ragionamento investigativo attraverso indizi, situazioni pratiche e nuove sfide.','Ontdek hoe je observeert en afwegingen maakt bij onderzoek, met aanwijzingen, praktijksituaties en nieuwe uitdagingen.','Explora la observación y el razonamiento en la investigación con pistas, situaciones prácticas y nuevos desafíos.','Explore a observação e o raciocínio na investigação através de pistas, situações práticas e novos desafios.','استكشف الملاحظة وحسن التقدير أثناء التحقيق من خلال القرائن والمواقف العملية والتحديات الجديدة.'],
  'Listen closely. Think clearly.\nFollow the facts.': [null,null,null,null,null,'Ouça com atenção. Pense com clareza.\nSiga as provas.','استمع بانتباه. فكّر بوضوح.\nاتبع الحقائق.'],
  'YOUR POLICE APTITUDE SCORE': [null,'IHR ERGEBNIS IM POLIZEIQUIZ','IL TUO PUNTEGGIO NEL TEST DI POLIZIA',null,'TU PUNTUACIÓN DE APTITUD POLICIAL','RESULTADO NO TESTE DE APTIDÃO POLICIAL','نتيجتك في اختبار الاستعداد للعمل الشرطي'],
  'The Entrance Exam Standout': ['L’as des épreuves',null,'Il candidato brillante','De uitblinker in de toelatingstest','El aspirante destacado',null,null],
  'The Calm Problem Solver': [null,null,'La mente lucida',null,null,null,'الهادئ في حلّ المشكلات'],
  'The First-Day Cadet': [null,'Der Kadett am ersten Tag','Il cadetto al primo giorno','De beginnende kadet',null,'O cadete no primeiro dia','المتدرّب في يومه الأول'],
  'Situational judgment': [null,null,null,null,null,'Avaliação de situações','تقييم المواقف'],
  'Communication': ['Communication',null,null,null,'Comunicación',null,'التواصل'],
  'Evidence handling': [null,null,null,'Omgaan met bewijsmateriaal',null,'Tratamento de provas',null],
  'Strongest policing area': ['Votre point fort dans le quiz','Ihr stärkstes Thema im Polizeiquiz','Il tuo punto forte nel quiz','Je sterkste onderwerp in de politiequiz','Tu punto fuerte en el test',null,'أقوى موضوعات الشرطة لديك'],
  'Trickiest policing area': ['Le thème qui vous a le plus posé problème','Ihr schwierigstes Thema im Polizeiquiz','L’argomento del quiz più difficile per te','Je lastigste onderwerp in de politiequiz','El tema del test que más te ha costado',null,'أكثر موضوعات الشرطة تحدّيًا لك'],
};

phrases['For entertainment and general learning only. This is not an official police recruitment, legal, fitness, medical, psychological or employment assessment. Laws and operational procedures vary by jurisdiction.'] = [
  'À des fins ludiques et pédagogiques uniquement. Ce quiz n’est pas une épreuve officielle de recrutement dans la police ni une évaluation juridique, physique, médicale, psychologique ou professionnelle. Les lois et les procédures d’intervention varient selon les juridictions.',
  'Nur zur Unterhaltung und zum allgemeinen Lernen. Dies ist kein offizieller Einstellungstest der Polizei und keine rechtliche, medizinische, psychologische oder berufliche Beurteilung. Auch die körperliche Fitness wird damit nicht geprüft. Gesetze und Einsatzverfahren unterscheiden sich je nach Rechtsordnung.',
  'Solo per intrattenimento e cultura generale. Non è una prova ufficiale per entrare in polizia né una valutazione giuridica, fisica, medica, psicologica o professionale. Le leggi e le procedure operative variano a seconda della giurisdizione.',
  'Alleen voor plezier en algemene kennis. Dit is geen officiële selectietest voor de politie en geen juridische, medische, psychologische of beroepsbeoordeling. Het is ook geen fitheidstest. Wetten en operationele procedures verschillen per rechtsgebied.',
  'Solo para entretenimiento y aprendizaje general. No es una prueba oficial de acceso a la policía ni una evaluación jurídica, física, médica, psicológica o laboral. Las leyes y los procedimientos operativos varían según la jurisdicción.',
  'Apenas para entretenimento e aprendizagem geral. Este teste não é uma prova oficial de acesso à polícia nem uma avaliação jurídica, física, médica, psicológica ou profissional. As leis e os procedimentos operacionais variam de acordo com a jurisdição.',
  'للترفيه والتعلّم العام فقط. هذا ليس اختبارًا رسميًا للقبول في الشرطة، ولا تقييمًا قانونيًا أو طبيًا أو نفسيًا أو مهنيًا أو للياقة البدنية. تختلف القوانين والإجراءات الميدانية بحسب الجهة القضائية المختصة.',
];
const topics = {
  'At the scene': ['Sur les lieux','Am Einsatzort','Sul posto','Ter plaatse','En el lugar de los hechos','No local','في موقع الحادث'],
  'Listen and clarify': ['Écouter et clarifier','Zuhören und Klarheit schaffen','Ascoltare e chiarire','Luisteren en verduidelijken','Escuchar y aclarar','Ouvir e esclarecer','الاستماع والتوضيح'],
  'Follow the evidence': ['Suivre les éléments de preuve','Den Belegen folgen','Seguire le prove','Het bewijs volgen','Seguir las pruebas','Seguir as provas','تتبّع الأدلة'],
  'Integrity in practice': ['L’intégrité dans la pratique','Integrität in der Praxis','Integrità nella pratica','Integriteit in de praktijk','Integridad en la práctica','Integridade na prática','النزاهة في الممارسة العملية'],
  'Accurate records': ['Une documentation précise','Präzise Dokumentation','Documentazione accurata','Nauwkeurige verslaglegging','Registros precisos','Documentação precisa','التوثيق الدقيق'],
  'Details and timelines': ['Détails et chronologie','Details und zeitliche Abläufe','Dettagli e cronologia','Details en tijdlijnen','Detalles y cronología','Detalhes e cronologia','التفاصيل وتسلسل الأحداث'],
  'Reasoning from rules': ['Raisonner à partir de règles','Aus Regeln Schlussfolgerungen ziehen','Ragionare a partire dalle regole','Redeneren vanuit regels','Razonar a partir de reglas','Raciocínio a partir de regras','الاستدلال من القواعد'],
  'Numbers and distances': ['Nombres et distances','Zahlen und Entfernungen','Numeri e distanze','Aantallen en afstanden','Números y distancias','Números e distâncias','الأرقام والمسافات'],
  'Investigative judgement': ['Le raisonnement d’enquête','Urteilsvermögen bei Ermittlungen','Il ragionamento investigativo','Afwegingen bij onderzoek','El criterio en la investigación','O raciocínio na investigação','التقدير في التحقيق'],
  'Review and follow-up': ['Réexamen et suivi','Überprüfung und Nachbereitung','Revisione e verifiche successive','Beoordelen en opvolgen','Revisión y seguimiento','Revisão e acompanhamento','المراجعة والمتابعة'],
};
for (const [source, row] of Object.entries(topics)) {
  phrases[source] = row;
  phrases[source.toUpperCase()] = row.map(text => text.toLocaleUpperCase());
  const leads = ['Prochain défi : ', 'Als Nächstes: ', 'Prossima sfida: ', 'Hierna: ', 'Próximo reto: ', 'A seguir: ', 'التحدي التالي: '];
  const teasers = row.map((text, column) => `${leads[column]}${text}.`);
  phrases[`Explore ${source.toLowerCase()} next.`] = teasers;
  phrases[`Up next: ${source}.`] = teasers;
}
export const editorialPoliceFamily = {slugs: ['police'], phrases};
